### ISSUE TITLE
Question: determining whether or not a type name is a class.

### ISSUE THREAD

**Issue by ezequiel-umu** [dsherret/ts-morph#108]
Hi, people from ts-simple-ast.

I am trying to determine if an expression is a class name by using the vanilla TS compiler I have the following problem. When I ask for the definition of `Date`, because `Date` is defined as a mix of `DateConstructor` const variable and `Date` interface, is _quite hard_ to determine whether or not `Date` is a class.

Does `ts-simple-ast` provide a mechanism to solve this problem?

Thank you,
Ezequiel.

**Comment by dsherret** [comment]
Hi ezequiel-umu, once you get the type, I believe you could check if `type.getConstructSignatures().length > 0`.

Alternatively, if that isn't sufficient, I believe this might work:

```typescript
// untested code... not sure if this works
function isClassType(type: ts.Type) {
    const tsSymbol = type.getSymbol();
    const declarations = tsSymbol.getDeclarations() || [];
    return declarations.some(d => d.kind === ts.SyntaxKind.ClassDeclaration);
}
```

...essentially, get the symbol of the type then check all its declarations for a class declaration.

There might be some combination of `TypeFlags` that signify a class is a type (see `type.flags` property). You might want to look into that as well.

I'll look into this later and see about adding a `type.isClass()` method in ts-simple-ast.

**Comment by ezequiel-umu** [comment]
The snippet code would only work when the type is declared using `class` keyword, right? Otherwise, `type.getConstructSignatures().length > 0` should do the trick?

**Comment by dsherret** [comment]
Yes, exactly. I believe that's the case.

**Comment by ezequiel-umu** [comment]
It fails for `Map`:

```ts
console.log(((type.getSymbol() as AstSymbol).getDeclarations() || []).some((d) => d.getKind() === ts.SyntaxKind.ClassDeclaration));
console.log("Object not parsed: " + objectFlags);
console.log("Object's name: " + (type.getSymbol() as AstSymbol).getName());
```

```js
true
Object not parsed: 4
Object's name: Type
Type not parsed: 16384
Type not parsed: 16384
false
Object not parsed: 4
Object's name: Map
```

**Comment by dsherret** [comment]
I'll look into this later. I'd have to play around with it to find out how to get it to work in this scenario.

Maybe looking at the source for `Map` might help in the meantime though:

```typescript
interface Map<K, V> {
    clear(): void;
    delete(key: K): boolean;
    forEach(callbackfn: (value: V, key: K, map: Map<K, V>) => void, thisArg?: any): void;
    get(key: K): V | undefined;
    has(key: K): boolean;
    set(key: K, value: V): this;
    readonly size: number;
}

interface MapConstructor {
    new (): Map<any, any>;
    new <K, V>(entries?: [K, V][]): Map<K, V>;
    readonly prototype: Map<any, any>;
}
declare var Map: MapConstructor;
```

**Comment by ezequiel-umu** [comment]
As I said earlier: a mix of an interface with the info and an interface with the Constructor. Map by itself has no constructor signatures but is construct-able.

**Comment by dsherret** [comment]
@ezequiel-umu here's some code that works for `Map`:

```typescript
function isClassType(type: Type) {
    if (type.getConstructSignatures().length > 0)
        return true;

    const symbol = type.getSymbol();
    if (symbol == null)
        return false;

    for (const declaration of symbol.getDeclarations()) {
        if (TypeGuards.isClassDeclaration(declaration))
            return true;
        if (TypeGuards.isVariableDeclaration(declaration) && declaration.getType().getConstructSignatures().length > 0)
            return true;
    }

    return false;
}
```

Btw, you can write `type.getSymbol()!.getDeclarations()` instead of `(type.getSymbol() as AstSymbol).getDeclarations()`. I'll update `Type` to have a `getSymbolOrThrow()` method.

**Comment by dsherret** [comment]
Closing for now. Please reopen if the above doesn't solve the problem.

**Comment by Crusader4Christ** [comment]
export type Constructor<T extends object = object> = new (...args: any[]) => T;
I don,t have a class, but type.getConstructSignatures().length > 0 works for this type.
