### ISSUE TITLE
Question: injecting arbitrary JavaScript after class compilation.

### ISSUE THREAD

**Issue by ezequiel-umu** [dsherret/ts-morph#109]
Hello world! 

I would like to inject arbitrary JavaScript between the compilation of a class and its decorators.

This TypeScript code:

```ts
function Test<T, K>(target: T, propertyKey: K) {

}

class C {
    @Test
    method() {
        return "Hello, " + " world";
    }
}
``` 

Is compiled as:

```js
function Test(target, propertyKey) {
}
class C {
    method() {
        return "Hello, " + " world";
    }
}
// HERE <--------------- I want to inject arbitrary JavaScript.
__decorate([
    Test,
    __metadata("design:type", Function),
    __metadata("design:paramtypes", []),
    __metadata("design:returntype", void 0)
], C.prototype, "method", null);
```

Does this project offer any mechanism to do so?

Thank you,
Ezequiel.

**Comment by dsherret** [comment]
Not really. At the current moment, you could open up the emitted .js file and edit that though. You'd have to use `sourceFile.insertText()` though, because #101 is not implemented yet.

It would be nice to have this ability and I don't believe it would be challenging to add. Perhaps some way to emit files in memory, then navigate and manipulate files within that emit result. Something like:

```typescript
// but different method name
const emitResult = ast.softEmit();
const sourceFile = emitResult.getSourceFileOrThrow("SomeFile.js");
sourceFile.insertStatements(sourceFile.getClassorThrow("C").getChildIndex() + 1, "// code to insert would go here");
await emitResult.save();
```

**Comment by ezequiel-umu** [comment]
It is possible to add a decorator to the TypeScript source code before compile it? Because there is a workaround. Adding a specific decorator will end up injecting `__decorator` call where I need it in the final JavaScript.

**Comment by dsherret** [comment]
Yup, you could do:

```typescript
const sourceFile = ast.getSourceFileOrThrow("SomeFile.ts");
sourceFile.getClassOrThrow("C").addDecorator({
    name: "decoratorName",
    // ...other properties...
});
ast.emit();
```

Just don't call `.save()` on the files before emitting.

**Comment by dsherret** [comment]
Closing. I've opened #126.
