### ISSUE TITLE
Provide an API to load all types available in `node_modules/`

### ISSUE THREAD

**Issue by wojpawlik** [dsherret/ts-morph#1144]
**Is your feature request related to a problem? Please describe.**

I hoped https://npm.im/deno2node could `sourceFile.fixMissingImports()` to import `fetch` and `AbortController` ponyfills, but:

![obraz](https://user-images.githubusercontent.com/23058303/114060166-62332480-9895-11eb-96ae-30e14c813f9a.png)

> the JS language service doesn't aggressively include types for packages it can't tell you're using yet, because doing so would be a fairly substantial perf hit for not a lot of gain. (https://github.com/microsoft/TypeScript/issues/29039#issuecomment-474628577)

**Describe the solution you'd like**

Provide a (`Project`) method for loading all types from all packages at the top-level of `node_modules/`.

**Comment by dsherret** [comment]
I'm not sure how to do this with the TS compiler and it would take some investigative work. A hacky way around this might be to temporarily add `import "abort-controller";`-like dummy imports then do `fixMissingImports()` then remove them (I'm not sure it would work though).

**Comment by wojpawlik** [comment]
I no longer need this: https://github.com/wojpawlik/deno2node/issues/4
