### ISSUE TITLE
emitToMemory() no longer supported?

### ISSUE THREAD

**Issue by peterje** [dsherret/ts-morph#1147]
Version: 0.9.1
**Bug**

The following example code provided [here](https://ts-morph.com/emitting#emitting-to-memory) does not compile:

**To Reproduce**

```ts
const project = new Project({ compilerOptions: { outDir: "dist" } });
project.createSourceFile("MyFile.ts", "const num = 1;");
const result = project.emitToMemory();

// output the emitted files to the console
for (const file of result.getFiles()) {
    console.log("----");
    console.log(file.filePath);
    console.log("----");
    console.log(file.text);
    console.log("\n");
}
```
**Error**

TypeError: program.emitToMemory is not a function

**Expected behavior**

 Successful compilation

**Comment by dsherret** [comment]
Should be. There is a passing test here: https://github.com/dsherret/ts-morph/blob/1dc592141432f8e0541b7b6211f7edf8ad205e5a/packages/ts-morph/src/tests/projectTests.ts#L1110 and the example code is checked with the type checker.

The error there says “program” instead of “project”. Is that the right code being run?

**Comment by peterje** [comment]
Hmm interesting. It seems that I was having issues because I installed @ts-morph/bootstrap. Not sure if that is completely affiliated with this project. Here is some further information:

```javascript
import { createProject } from "@ts-morph/bootstrap"
import { Project } from "ts-morph"

/*Succeeds*/
const p = new Project()
p.emitToMemory()

/*Fails*/
emitProject()

async function emitProject(){
    const p = await createProject()
    p.emitToMemory()
}
```

After viewing some definitions, the <Project> type in @ts-morph/bootstrap is entirely different than the <Project> type in @ts-morph. Very confusing.
