### ISSUE TITLE
How to set a base directory on the project? or is there no way?

### ISSUE THREAD

**Issue by PhilAndrew** [dsherret/ts-morph#1151]
I see methods like

project.addSourceFilesAtPaths("src/**/*.ts");

Does that mean the project has a project root of the current directory? Will it emit something in the current directory? if so, can it emit to a different directory?

**Comment by dsherret** [comment]
@PhilAndrew it uses the current working directory and will emit based on the `outDir` specified in the tsconfig or provided compiler options.

If you want to work based off a directory, then you can get a directory object and work from there:

```ts
const srcDir = project.getDirectoryOrThrow("src");

srcDir.addSourceFilesAtPath("**/*.ts");

await srcDir.emit({
    outDir: "../src-out" // optionally specify this to control the output directory
});
```
