### ISSUE TITLE
resolving chain exports to their non chain exports

### ISSUE THREAD

**Issue by lillallol** [dsherret/ts-morph#1152]
I am about to publish a typescript documentation generation library. I am looking for a function that does the following:

>Given a chain export statement resolve it to non chain export statements. Each resolved non chain export statement will also have the following data: namespaces (an array of names of the namespace imports encountered while resolving the statement) and the exposed name (the name that the consumer uses for the resolved non chain export statement).

Here are some examples of what an chain export is:

```ts
export * from "./some/where";
export * as x from "./some/where";
export { A, b as B, default as C, default } from "./some/where";
export { A, b as B, c as default };
export default foo;
```

Here are some examples of what an non chain export is:

```ts
export function foo() {}
export class A {
    constructor() {}
}
export const a = 1, b = 2;
export interface I {

}
export type obj = {a : number ,b : string};

export default function foo() {}
export default class A {
    constructor() {}
}
export default const a = 1;
export default interface I {

}
```

Here is an example of what the function I am looking for is doing:

1. ```ts
    //index.ts
    export {a as b} from "./1"; //statement 1

    //./1.ts
    export const a = 1; //statement 2
    ```

    given `statement 1` it will return `statement 2` with exposed name `b` and namespaces an empty array.
2. ```ts
    //index.ts
    export {x as y} from "./1"; //statement 1

    //./1.ts
    export * as x from "./2"; //statement 2

    // ./2.ts
    export const c = 1; //statement 3
    ```

    given `statement 1` it will return `statement 3` with exposed name `c` and namespaces `["y"]`.

I have already created such a functionality (using simple functions from the typescript node module) that works only for ES imports/exports for d.ts files . It required a lot of work and I am sure it has a lot of bugs I have not yet found. I was wondering if your library or the typescript node module provides such a functionality for .ts files.

**Comment by dsherret** [comment]
I think the closest thing is probably `getExportedDeclarations()` (https://github.com/dsherret/ts-morph/blob/1dc592141432f8e0541b7b6211f7edf8ad205e5a/packages/ts-morph/lib/ts-morph.d.ts#L1529)

Worst case scenario is that you could look at the code that was used to implement that in order to help out with your implementation.

**Comment by lillallol** [comment]
Thanks for the answer.

**Comment by lillallol** [comment]
So there is no build in functionality from the typescript node module for such a thing after all?
