### ISSUE TITLE
Example project proposal: automatic log injector based on Log20

### ISSUE THREAD

**Issue by zamber** [dsherret/ts-morph#121]
Found this on The Morning Paper - [Log20: Fully automated optimal placement of log printing statements under specified overhead threshold](https://blog.acolyer.org/2017/11/03/log20-fully-automated-optimal-placement-of-log-printing-statements-under-specified-overhead-threshold/), paper: [http://www.eecg.toronto.edu/~yuan/papers/p125-Zhao.pdf](http://www.eecg.toronto.edu/~yuan/papers/p125-Zhao.pdf)

I started searching for anything like this for TypeScript and found nothing. Then I started searching for a way to analyze and manipulate the AST.

This project seems well suited. I need a secondary opinion ;).

My use case is a way to auto-log a Angular 5 project.

**Comment by dsherret** [comment]
Very cool!! Based on a very brief view of that paper (which I will read more later), I believe this library is suited for that.

**Comment by dsherret** [comment]
Closing this. I hope it goes well if you decide to do it!

One thing I did realize after reading the paper, is that currently it's not possible in this library to insert statements to different blocks. That would be necessary to do what's described. I've opened #131.
