### ISSUE TITLE
Indented comments

### ISSUE THREAD

**Issue by derolf** [dsherret/ts-morph#124]
What‘s the best way to add comments to the AST so that they show up nicely idented and marked with „/*“ in the generated code?

**Comment by derolf** [comment]
Indented, not idented

**Comment by dsherret** [comment]
@derolf what do you mean by "„/*“"?

**JS Docs**

Do you mean like this:

```typescript
/**
 * Some description.
 */
function myFunction() {
}
```

If so, you can get the declaration then call `addDoc({ ... })`. [Read more](https://dsherret.github.io/ts-simple-ast/details/documentation). Currently support isn't that great, but I'll add more in #118.

**Statements**

If you mean just inserting statements with // at the beginning, then you can use the `insertStatements` or `addStatements` methods that appear on nodes that have statements. For example:

```typescript
functionDeclaration.addStatement("// some comment");
```

...will adds the statement indented to the body of the function.

**Comment by dsherret** [comment]
Hi @derolf, if the above doesn't answer your question, then please reopen this issue with a clarification of the question. Thanks!

**Comment by derolf** [comment]
Thanks, the answer is what I was looking for!
