### ISSUE TITLE
Support for Generics

### ISSUE THREAD

**Issue by danimbrogno** [dsherret/ts-morph#134]
Hey, wondering if generics are supported in this library and if not if there are plans to support this.

Right now when I try to do:

```
static interfaces: InterfaceDeclarationStructure[] = [
    {
      name: 'ISegment<T>',
      methods: [
        {
          name: 'loadRawSegment<T>',
          parameters: [
            {
              name: 'segment',
              type: 'TRawSegment'
            }
          ],
          returnType: 'T'
        }
      ],
      isExported: true
    }
  ];
```

I get a cryptic error:
`Could not find file: 'tsSimpleAstTempFile.ts'`

Thanks!

**Comment by dsherret** [comment]
I have to look into that `tsSimpleAstTempFile.ts` bug (opened #135). I've seen that too when things go wrong.

Use the `typeParameters` property. A name doesn't include the type parameters:

```typescript
name: 'ISegment',
typeParameters: [{ name: "T" }]
```

**Comment by danimbrogno** [comment]
Great thanks, that worked perfectly.
