### ISSUE TITLE
Can't set `isOptional` on `PropertySignatureStructure`

### ISSUE THREAD

**Issue by ChuckJonas** [dsherret/ts-morph#146]
trying to do something this:

```
            let ip: PropertySignatureStructure = {
                name: 'foo',
                type: 'string'
                isReadonly: true,
                isOptional: true, 
            }
```

Throws an error:

```
Type '{ name: string; type: string; isReadonly: true; isOptional: boolean; }' is not assignable to type 'PropertySignatureStructure'.
  Object literal may only specify known properties, and 'isOptional' does not exist in type 'PropertySignatureStructure'.
```

The only way I can figure out of to set it, is to do something like this:

```
  let ip = myClass.addProperty({
              name: 'foo',
              type: 'string',
              isReadonly: true,
            });
  ip.setIsOptional(true);
```

**Comment by dsherret** [comment]
Use `{ hasQuestionToken: true }`. That `setIsOptional` method should actually have question token in the name to be consistent. I know it's somewhat not as obvious as `isOptional` in this scenario, but the reason it's `hasQuestionToken` is to prevent confusion with other language features that could make a node optional (ex. an initializer on a parameter or a spread parameter).

**Comment by ChuckJonas** [comment]
thanks!

**Comment by dsherret** [comment]
No problem! :)
