### ISSUE TITLE
Getting the declaration of a type?

### ISSUE THREAD

**Issue by AnyhowStep** [dsherret/ts-morph#202]

**Comment by dsherret** [comment]
A declaration can be retrieved from a type's symbol. For example:

```ts
// assuming the symbol exists... (use getSymbol() otherwise)
const declarations = variableDeclaration.getType().getSymbolOrThrow().getDeclarations();
```

**Comment by brad-jones** [comment]
What exactly is a "symbol"? When would a type have one or wouldn't have one?

`getSymbolOrThrow` is throwing for me.

Actually in my case I have a TypeNode, maybe this is related to #130?

Slightly contrived example but something similar to this is what I am attempting to do:
```ts
for (let srcFile of ast.getSourceFiles())
{
    for (let classDec of srcFile.getClasses())
    {
        let decoratorNode = classDec.getDecorator('foo');
        if (decoratorNode)
        {
            let typeNode = decoratorNode.getTypeArguments()[0];
            let typeDecs = typeNode.getSymbolOrThrow().getDeclarations(); // throws as no symbol

            // For now I have restored to this horrible hack
            // So long as I have no interfaces with the same name this does what I want.
            let interfaceNode = ast.getSourceFiles()
                .map(_ => _.getInterfaces())
                .reduce((c, p) => c.concat(p))
                .find(_ => _.getName() === typeNode.getText());
        }
    }
}
```

Is `getDeclarations()` going to get me what I want or am I going down the wrong path?

**Comment by dsherret** [comment]
@brad-jones I'll explain after work.

Yeah, I think it's related to #130. You should be able to do this workaround in the meantime:

```ts
// using typeNode above
const typeChecker = ast.getTypeChecker();
const type = typeChecker.getTypeAtLocation(typeNode);
const typeDecs = type.getSymbolOrThrow().getDeclarations();
```

**Comment by brad-jones** [comment]
Cheers, worked a treat.

**Comment by AnyhowStep** [comment]
Holy crap. I didn't realize I accidentally submitted this. I am so sorry.

**Comment by dsherret** [comment]
Hey @AnyhowStep, it's really no problem! 😄 It's good to have this somewhere in the issue tracker for people to search for... I should actually update the documentation with more information about this.

**Comment by dsherret** [comment]
@brad-jones in 6.5.0 you can now just do `typeNode.getType()` instead of what's described above.

**Comment by wi-ski** [comment]
Why would a Symbol have more than one declaration? Apologies, Im new

**Comment by dsherret** [comment]
Here's an example (declaration merging):

```ts
interface MyDeclaration {
  prop1: string;
}

interface MyDeclaration {
  prop2: string;
}
```

https://ts-ast-viewer.com/#code/JYOwLgpgTgZghgYwgAgLIE8AiEEBs5RxjAD2IyA3gFDLIAOUJdAjAFzIDOYUoA5gNxUAvlSqhIsRCgzY8BIqXLVaDJgCZ2XHiAHCgA (click on one of the interfaces and see how the symbol has two declarations)

**Comment by wi-ski** [comment]
You're incredible - thank you for your efforts on this project, much respect 🙇
