### ISSUE TITLE
Question - Replace recursively spread elements

### ISSUE THREAD

**Issue by vogloblinsky** [dsherret/ts-morph#238]
Hi,

I am dealing with a scenario for my OS project https://github.com/compodoc/compodoc

I need to replace all spread elements of an array for example with they corresponded value.

```
const OTHERS_PATHS = [
    'file2',
    'file3',
    'file4'
]

const PATHS: Routes = [
    'file1',
    {
        'level2': [
            ...OTHERS_PATHS
        ]
    },
    ...OTHERS_PATHS
]
``` 

Which scenario did you think works best ?

- traverse recursively PATHS AST and try to replace each node who is a SpreadElement
- for each import or variable declaration inside the file, found their reference usage, and replace them

The constraint is that PATHS contains routing definition for Angular.

The problem for me for the second scenario is that there may be a variable declaration after PATHS declaration. Did ts-simple-ast support that ?
For the first scenario, i manage to do that but for the first level of my PATHS array. I had to deal with multiple levels sometimes, and do it recursively will be better.

Thanks by advance.

**Comment by dsherret** [comment]
Hey Vincent, I'm just about to head out so sorry for this really messy reply. I wrote this fast.

First, is that you should use whichever scenario better describes what you're trying to do. I'm not sure which one would be most appropriate in this scenario.

---

Could you provide some expected output just to make sure I'm understanding correctly? I don't have any experience with angular. I'm thinking the expected output is this?

```ts
const PATHS: Routes = [
    'file1',
    {
        'level2': [
            'file2',
            'file3',
            'file4'
        ]
    },
    'file2',
    'file3',
    'file4'
]
```

---

You should be able to get all the descendant spread elements of the variable declaration's initializer by doing:

```ts
const pathsDec = sourceFile.getVariableDeclarationOrThrow("PATHS");
const spreadElements = pathsDec.getInitializerOrThrow().getDescendantsOfKind(ts.SyntaxKind.SpreadElement);
```

---

> The problem for me for the second scenario is that there may be a variable declaration after PATHS declaration. Did ts-simple-ast support that ?

Can you expand on what you mean here? Do you mean having a variable statement with multiple variable declarations? For example:

```ts
const PATHS: Routes = [], OTHER_PATHS: Routes = [];
```

It supports that. Read more [here](https://dsherret.github.io/ts-simple-ast/details/variables).

**Library Problems**

I believe these problems prevent you from being able to do this easily:

1. If you use `.replaceWithText` on `Node`, right now the method only supports replacing with one node. In this case it would have to replace with multiple. I'll open an issue soon to fix this.
2. If you want to use `addElement` on `ArrayLiteralExpression`, it will insert everything on the same line. I would like to add a way to insert each element on a new line... it might be possible right now to manually insert the newline yourself actually, but I'm not sure. Try it out.

**Comment by vogloblinsky** [comment]
Here is an example i need to parse with compodoc

```
const localEmptyPath = '';

import { AboutComponent } from './about.component';

import { pathMatchStrategy } from './paths';

const childs = [{ path: 'about', component: AboutComponent }];

const ABOUT_ROUTES: Routes = [
    {
        path: localEmptyPath, component: AboutComponent,
        children: [
            { path: localEmptyPath, redirectTo: 'todomvc', pathMatch: pathMatchStrategy.path },
            { path: 'todomvc', component: TodoMVCComponent },
            ...childs
        ]
    }
];
```

`ABOUT_ROUTES` is stringified with JSON5 in documentation generation process, and breaks with `pathMatchStrategy.path` and `...childs`

Si i need to parse ABOUT_ROUTES recursively and replace `...childs` and also dynamic variable like `pathMatchStrategy.path`

for having finaly

```
const ABOUT_ROUTES: Routes = [
    {
        path: localEmptyPath, component: AboutComponent,
        children: [
            { path: localEmptyPath, redirectTo: 'todomvc', pathMatch: 'full' },
            { path: 'todomvc', component: TodoMVCComponent },
            { path: 'compodoc', component: CompodocComponent }
        ]
    }
];
```

**Comment by dsherret** [comment]
Hi Vincent,

Given the following input file:

```ts
const pathMatchStrategy = { path: "full" };
const childs = [{ path: 'about', component: AboutComponent }];

const ABOUT_ROUTES: Routes = [
    {
        path: localEmptyPath, component: AboutComponent,
        children: [
            { path: localEmptyPath, redirectTo: 'todomvc', pathMatch: pathMatchStrategy.path },
            { path: 'todomvc', component: TodoMVCComponent },
            ...childs
        ]
    }
];
```

I'm able to do manipulate this file by doing (in version 6.9.0):

```ts
const spreadElements = sourceFile.getDescendantsOfKind(ts.SyntaxKind.SpreadElement)
    .filter(p => TypeGuards.isArrayLiteralExpression(p.getParentOrThrow()));
const propertyAccessExpressions = sourceFile.getDescendantsOfKind(ts.SyntaxKind.PropertyAccessExpression)
    .filter(p => !TypeGuards.isPropertyAccessExpression(p.getParentOrThrow())); // do not get PAEs within PAEs

// inline the ArrayLiteralExpression SpreadElements
for (const spreadElement of spreadElements) {
    const referencedDeclaration = spreadElement.getExpression().getSymbolOrThrow().getValueDeclarationOrThrow();
    if (!TypeGuards.isVariableDeclaration(referencedDeclaration))
        throw new Error(`Not implemented referenced declaration kind: ${referencedDeclaration.getKindName()}`);
    const referencedArray = referencedDeclaration.getInitializerIfKindOrThrow(ts.SyntaxKind.ArrayLiteralExpression);
    const spreadElementArray = spreadElement.getParentIfKindOrThrow(ts.SyntaxKind.ArrayLiteralExpression);
    const insertIndex = spreadElementArray.getElements().indexOf(spreadElement);
    spreadElementArray.removeElement(spreadElement);
    spreadElementArray.insertElements(insertIndex, referencedArray.getElements().map(e => e.getText()));
}

// inline the property access expressions
for (const propertyAccessExpression of propertyAccessExpressions) {
    const referencedDeclaration = propertyAccessExpression.getNameNode().getSymbolOrThrow().getValueDeclarationOrThrow();
    if (!TypeGuards.isPropertyAssignment(referencedDeclaration))
        throw new Error(`Not implemented referenced declaration kind: ${referencedDeclaration.getKindName()}`);
    propertyAccessExpression.replaceWithText(referencedDeclaration.getInitializerOrThrow().getText());
}
```

The actual solution to this is definitely much more complicated because it will need to ensure that the manipulated file has all the correct imports.

Let me know if there's anything specific that you think could be added to this library to make this easier.

**Comment by vogloblinsky** [comment]
Hi David,

Thanks for your answer.

I managed to deal with enum inside an import with more code from `file.getImportDeclarations()`etc.

For property access expression i didn't have any problem, even if the property is directly inside the file or from an import.
