### ISSUE TITLE
Possible Parsing Problem

### ISSUE THREAD

**Issue by kjpou1** [dsherret/ts-morph#246]
Hello David

I was wondering if this is correct and would have something to do with ts-simple-ast.

```
interface foo {
    item(index: number): string; // Return the string at the specified index
}
```

Taking the definition above and viewing it in [ts-ast-viewer](https://dsherret.github.io/ts-ast-viewer/)

We get the parsing output in the middle panel.  If the `CloseBraceToken` is selected and then go to the properties panel we have the following:

```
Full Text

 // Return the string at the specified index
}

Text

}

```

Shouldn't the `// Return the string at the specified index` noted above actually be a trailing comment element for the previous definition and not part of the properties for the `CloseBraceToken`?

Notice the difference between `Full Text` and `Text`.  Of course I may be misunderstanding how the AST is parsed.

Viewing the same here https://astexplorer.net shows the trailing comment as part of the Method definition.

Thanks

**Comment by dsherret** [comment]
Hey @kjpou1, ts-ast-viewer uses the typescript compiler directly. This is working—the value of full text includes the current token text and any leading trivia text (spaces and comments).

I believe the output from `.getFullText()` is the substring of `.getFullStart()` to `.getEnd()`. See here for information about "full start": https://github.com/Microsoft/TypeScript/wiki/Architectural-Overview#full-starttoken-start

**Comment by dsherret** [comment]
By the way, if you find a scenario (there should be plenty of them) where this library doesn't respect this...

>  In general, a token owns any trivia after it on the same line up to the next token. Any comment after that line is associated with the following token. The first token in the source file gets all the initial trivia, and the last sequence of trivia in the file is tacked onto the end-of-file token, which otherwise has zero width.

...then please open up an issue. That would be incredibly helpful. Comments have been an afterthought for the past while.

**Comment by kjpou1** [comment]
Thanks for the information.
