### ISSUE TITLE
Add method that logs any pending changes

### ISSUE THREAD

**Issue by dsherret** [dsherret/ts-morph#257]
Something like `logPendingChanges()`. This would output a top summary of the changes to the console (number of files changed, deleted, created). Then output a diff of all the files changed.

Configuration:

* Max number of files to show in detail (default: 5)
* Line visibility beyond diff... ex. show 5 lines above and below a diff (default: 2)

For diff, it should show new lines in green, old lines in red. It will use + at the start of the line for added, and - for removed. Seems like I could use https://github.com/kpdecker/jsdiff to do this easily.

More in the future, but this is good for now.

**Comment by petebacondarwin** [comment]
When you say pending changes, would this be the nodes that have changed due to a file (that is being watched) changing, and the TS compiler partially recompiling?

**Comment by dsherret** [comment]
I see how this isn't clear... maybe it needs a better name.

Essentially, all changes (source file edits, copies, moves, deletes) aren't propagated to the underlying file system until `.save()` is called on the main ast object (or methods like `sourceFile.moveImmediately(...)`, `sourceFile.deleteImmediately()` or `sourceFile.save()` are called). So after you make a bunch of manipulations, a developer could use this method to output a summary of the changes that were made. This would only be useful during development.

**Example**

```ts
const ast = new Ast({ tsConfigFilePath: "tsconfig.json" });

ast.getSourceFileOrThrow("src/MyClass.ts").getClassOrThrow("MyClass").rename("NewName");
ast.getSourceFileOrThrow("src/FileToMove.ts").move("NewFile.ts");
ast.getSourceFileOrThrow("src/FileToDelete.ts").delete();
ast.createSourceFile("src/CreatedFile.ts");

ast.logPendingChanges();
//ast.save();
```

Outputs:

```
========
Overview
========

Created: 1
Moved:   1
Deleted: 1
Changed: 1

- /MyProject/src/FileToDelete.ts
+ /MyProject/src/CreatedFile.ts
* /MyProject/src/FileToMove.ts -> /MyProject/src/NewFile.ts

=========================
/MyProject/src/MyClass.ts
=========================

  1 import {Something} from "./OtherFile"
  2
- 3 export class MyClass {
+ 3 export class NewName {
  4     private _someProp: string;
  5     private _etc: number;
```

So you would run the code above and get this output, then when satisfied you would change this:

```ts
ast.logPendingChanges();
//ast.save();
```

To:

```ts
ast.save();
```

...which would cause the changes to now be saved to the file system.

**Reason**

The reason for implementing this is to save a slight amount of time and allow viewing changes without touching the file system. I'm trying to eliminate this workflow:

1. Run script to manipulate a code base.
2. Using version control, view the changes and see if they're good.
3. Revert changes in source control if they're not. <-- Can be risky if you accidentally revert the code doing the manipulations :)

Overall, it would be easy to implement this, but I'm not sure it's worth it at this time... at least I would at least find it useful. It would need to be configurable though.
