### ISSUE TITLE
How to generate .ts file by using ts AST?

### ISSUE THREAD

**Issue by MrKou47** [dsherret/ts-morph#267]
```js
import Ast from "ts-simple-ast";

Ast.genCodeByAST(SOME_TS_AST_OBJECT); // generate some code
```

Does `ts-simple-ast` expose an api to do this work like [babel-generator](https://www.npmjs.com/package/babel-generator)?

**Comment by dsherret** [comment]
@MrKou47 do you mean something like `printNode`? See ["Printing a Node"](https://dsherret.github.io/ts-simple-ast/utilities).

Basically, you can separately use the [TypeScript compiler API](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#creating-and-printing-a-typescript-ast) (the `ts` export from this library) and generate an AST using its factory functions. From there, you could print the node and if you wanted you could then add its text as a source file to ts-simple-ast.

**Comment by MrKou47** [comment]
@dsherret Thanks! I got it😄
