### ISSUE TITLE
Get Methods JSDoc

### ISSUE THREAD

**Issue by BeardedDonut** [dsherret/ts-morph#275]
Hi I have read the documentation but I couln't find an answer for my question...
I was wondering how can get JSDoc for a method defined inside a class?
Thanks.

**Comment by dsherret** [comment]
Hey, I’m not at my computer right now, but once you have the MethodDeclaration then you should be able to just call ‘method.getJsDocs()’.

Does that work? If not, let me know and I’ll look into it.

**Comment by navid9675** [comment]
Thanks for the reply.. I've checked what you have suggested but I get `MethodDeclaration.getJsDoc()' is undefined`. I've also tried `getJSDoc()` but it didn't help either.

**Comment by navid9675** [comment]
Thank you it worked very well... 
great job BTW
