### ISSUE TITLE
Get the class where a method is declared

### ISSUE THREAD

**Issue by lazarljubenovic** [dsherret/ts-morph#284]
Given a `MethodDeclaration`, can we get the class it's contained in? `getClasses` tries to get its descendant classes (when it this possible anyway?).

**Comment by dsherret** [comment]
For sure. If you know the parent will be a `ClassDeclaration` (and not something like a `ClassExpression` or `ObjectLIteralExpression`) then use:

```ts
const classDeclaration = method.getParentOrThrow() as ClassDeclaration;
// or even better:
const classDeclaration = method.getParentIfKindOrThrow(SyntaxKind.ClassDeclaration);
```

Also, minor correction: `.getClasses()` will get the child (not descendants) class declarations contained within the `MethodDeclaration`. If you want the descendant classes then use `const classes = method.getDescendantsOfKind(SyntaxKind.ClassDeclaration);`.

**Comment by lazarljubenovic** [comment]
Man, with all these fancy things provided by the wrapper I forget that the basic tree structure is still at play. Thanks!
