### ISSUE TITLE
Constant types break isXType functions

### ISSUE THREAD

**Issue by Gerrit0** [dsherret/ts-morph#290]
I might be missing something obvious here... but getting types for constant variable declarations doesn't work as expected, getting the apparent type doesn't seem to resolve the problem.

Demo: 

```ts
import Project, { TypeGuards } from 'ts-simple-ast'

const project = new Project()

const file = project.createSourceFile('file.ts', `
  export const a = 'hi'
  export const b = 1
`)

file.getExportedDeclarations()
  .filter(TypeGuards.isVariableDeclaration)
  .forEach(declaration => {
    const type = declaration.getType()
    const apparentType = type.getApparentType()
    console.log(declaration.getName())
    console.log(type.getText(), type.isNumberType(), type.isStringType())
    console.log(apparentType.getText(), apparentType.isNumberType(), apparentType.isStringType())
    console.log()
  })
```

Output:
```text
a
"hi" false false // => Expected false, true
String false false // => I'd like to get type string

b
1 false false // => Expected true, false
Number false false // => I'd like to get type number
```

**Comment by dsherret** [comment]
Found it! There's a `getBaseTypeOfLiteralType()` on `ts.TypeChecker`.

If you want, you can temporarily fall back to the compiler API...

```ts
const baseType = project.getTypeChecker().compilerObject.getBaseTypeOfLiteralType(type.compilerType);
```

...but I will open up an issue and wrap this soon.

**Comment by dsherret** [comment]
Ok, I implemented all this. I'll comment back when v10 is released (sometime this week or next... feel free to clone the dev branch in case you need this now).

```ts
// this will work in v10
const numberType = numberLiteralType.getBaseTypeOfLiteralType();
```

I'm going to close this issue for now, but let me know if there's anything else you need.

**Comment by Gerrit0** [comment]
Thanks much! I'm using the code you posted above for now, but will certainly switch to V10 once released. `type.isLiteralType` might be useful, but is also trivial to write myself.

**Comment by dsherret** [comment]
Good point. I meant to add that. Thanks!

That will be in v10 as well.
