### ISSUE TITLE
How to catch errors in file when emitting?

### ISSUE THREAD

**Issue by lazarljubenovic** [dsherret/ts-morph#298]
Check this out:
https://runkit.com/lazarljubenovic/5ac0e65c2fb4d100127222d1

Basically, I've created an invalid file (`Foo` is an unknown type), yet everything goes smoothly. I've seen Type Checked mentioned, but I do not understand what to do with it -- apparently it's a low-level utility and not a global `.typeCheckThisFile()` sort of thing.

Why do I not see error when emitting? The file is emitted as if it would be by TS, but it would show errors. Why can I not see them in diagnostics? Is it a bug or am I missing something?

**Bigger picture**: I've generated some code in a `distProject` (containing a single file) by reading and analyzing code in `srcProject`. I want to check if everything is fine regarding TypeScript, pretty much the same way as if I'd written that code and did a `tsc` from the terminal. If everything is fine, I'd like to get the JavaScript output as a string, to further run it through Uglfy (and the rest of the flow become irrelevant here).

**Comment by dsherret** [comment]
There are emit, syntactic, semantic, and declaration diagnostics. The error with `Foo` being an unknown type is probably a semantic error and so the emitter won't count that as an emit diagnostic.

Try using either `project.getDiagnostics()` or if you just want it for a single file, then use `sourceFile.getDiagnostics()`. That will return all the diagnostics except the pre-emit diagnostics which are available on the `.getPreEmitDiagnostics()` method (I forget why `.getDiagnostics()` doesn't return the pre-emit ones... there must be some reason, but it was probably around a year ago that I worked on that).

Btw, if you want the different kinds of diagnostics individually, then you can get them from the program:

```ts
const program = project.getProgram();
const semanticDiagnostics = program.getSemanticDiagnostics();
// or...
const sourceFileSemanticDiagnostics = program.getSemanticDiagnostics(sourceFile);
```

Perhaps there should be the specific `sourceFile.getSemanticDiagnostics()`, `getSyntacticDiagnostics()`, and `getDeclarationDiagnostics()` methods.

**Comment by dsherret** [comment]
By the way, I just added a `project.createWriter()` method that will return a writer with the current manipulation settings.
