### ISSUE TITLE
How to find method references?

### ISSUE THREAD

**Issue by cowchimp** [dsherret/ts-morph#299]
Hi.
Thanks for this great library.

I'm able to use `findReferences` for classes and parameters, but not for methods.
Am I doing something wrong?

Here's my code:

```typescript
import Project from "ts-simple-ast";

const project = new Project();

const sourceFile = project.addExistingSourceFile("input/example3.ts");

const myClass = sourceFile.getClassOrThrow("Foo");

console.log(myClass.findReferences()); //exists

const method = myClass.getInstanceMethodOrThrow("methodA");

console.log(method.findReferences()); //doesn't exist
const nameNode = method.getNameNode();
console.log(nameNode.findReferences()); //doesn't exist
```

I'm using version 10.1.0.

Please let me know if you need more info.

**Comment by dsherret** [comment]
Hey @cowchimp, I'm going to add a `findReferences()` for nodes that are `PropertyNamedNode`—nodes with a name that can be `Identifier | StringLiteral | NumericLiteral | ComputedPropertyName`. That's something I overlooked so thanks for bringing this to my attention. I just opened #300.

For now, a workaround that should work is to do:

```ts
const languageService = project.getLanguageService();
console.log(languageService.findReferences(method.getNameNode()));

// or if you just care about getting the nodes and don't need all the other details
console.log(languageService.getDefinitionReferencingNodes(method.getNameNode()));
```

**Comment by cowchimp** [comment]
That workaround works. Thanks a lot 👍

**Comment by sagarpanchal** [comment]
@dsherret `findReferences` now works with methods but not when `useInMemoryFileSystem` is true
