### ISSUE TITLE
Default exporting of the class created

### ISSUE THREAD

**Issue by punithnpg** [dsherret/ts-morph#322]
How can we create a Class with default export?

**Comment by dsherret** [comment]
Like so:

```ts
// or use addClases, insertClass, or insertClasses
sourceFile.addClass({
    isDefaultExport: true,
    name: "MyClass",
});
```

You can also similarly insert classes to namespaces, functions, class method declarations, etc..

Let me know if that solves your question or if you have other ones.

**Comment by punithnpg** [comment]
Thank you!
