### ISSUE TITLE
Getting the name of methods inside a class

### ISSUE THREAD

**Issue by punithnpg** [dsherret/ts-morph#323]
`const members =classDeclaration.getMembers();`

How can i get the member name? @dsherret .
Thanks in advance.

**Comment by dsherret** [comment]
Hey @punithnpg, are you using a code environment with code completion/intellisense? That will help understand the possible types returned by `getMembers()` and the other methods available on `ClassDeclaration`. On another note, I'd like to create a documentation page that's generated from the API, but at the moment the documentation generation libraries don't support some of the language features I use in this library.

This is how to get the member names:

```ts
import Project, { TypeGuards } from "ts-simple-ast";

// etc...

for (const member of classDec.getMembers()) {
    if (TypeGuards.isConstructorDeclaration(member))
        console.log("constructor");
    else
        console.log(member.getName());
}
```

Or just the instance method names:

```ts
for (const method of classDec.getInstanceMethods())
    console.log(method.getName());
```

**Comment by dsherret** [comment]
That should be the answer so I'm closing this issue. Let me know if you have any other questions :)
