### ISSUE TITLE
Merging two declaration files in one

### ISSUE THREAD

**Issue by gdavidkov** [dsherret/ts-morph#331]
I have one main module with own declaration file and one submodule with own file too. 

- Is there a way to merge them in one file?

- Is there a way to convert for example ClassDeclaration to ClassDeclarationStructure and etc.?

**Comment by cancerberoSgx** [comment]
I think it's easily doable. 

This file has straight forward examples of how to convert classes, interfaces, functions std to its corresponding Structures: https://github.com/dsherret/ts-simple-ast/blob/master/scripts/common/cloning.ts

My two cents.

**Comment by gdavidkov** [comment]
Thank you very much! Your help is appreciated.

**Comment by dsherret** [comment]
Note that linked to code isn't very good. It's made somewhat specifically for the scenario I'm using it for, but it could be adapted for other scenarios.

> Is there a way to convert for example ClassDeclaration to ClassDeclarationStructure and etc.?

This is coming in #45.

> Is there a way to merge them in one file?

You could just combine the texts directly for now:

```ts
sourceFile.insertText(sourceFile.getFullWidth(), otherSourceFile.getFullText());
```

Or just if you want specific parts of that other file:

```ts
sourceFile.insertText(sourceFile.getFullWidth(), otherSourceFile.getClassOrThrow("SomeClass").getFullText());
```

**Comment by cancerberoSgx** [comment]
what about repeated imports ? I guess at the end you just call organizeImports ?

**Comment by dsherret** [comment]
@cancerberoSgx yes, or copy everything except the imports and then write a script that analyzes the imports in both files and combines them accordingly.

Closing this. Please follow the progress in #45 or do something mentioned above.

**Comment by aleclarson** [comment]
> [dsherret/ts-simple-ast@master/scripts/flattenDeclarationFiles.ts](https://github.com/dsherret/ts-simple-ast/blob/master/scripts/flattenDeclarationFiles.ts)

Is this script available somewhere? Does it perform [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) as well? If not, is there a helper method or guideline for declaration merging with ts-morph?

**edit:** Oh, it seems that `getMembers` handles that for me :)

**Comment by milahu** [comment]
> https://github.com/dsherret/ts-simple-ast/blob/master/scripts/common/cloning.ts

was moved to

https://github.com/dsherret/ts-morph/blob/latest/packages/ts-morph/scripts/common/cloning.ts
