### ISSUE TITLE
How to insert type export

### ISSUE THREAD

**Issue by igor-sky** [dsherret/ts-morph#378]
I have file called **index.d.ts**, want to add type export 

```
const validationsFile = project.getSourceFile('index.d.ts')
const data = 'type Example = { n:number, has:boolean }'
validationsFile.addExportAssignment({ isExportEquals:true, expression:data })
project.save()
```

 Actual:
`export = type Example = { a:number, has:boolean };`
 Expected
`export type Example = { a:number, has:boolean };`

**Comment by dsherret** [comment]
Hey @igor-sky. Try exporting a type alias:

```ts
validationsFile.addTypeAlias({
    isExported: true,
    name: "Example",
    type: "{ n:number; has: boolean; }"
});
````

**Comment by igor-sky** [comment]
@dsherret Thanks for a quick response, it works! :)  
For some reason WebStorm did not show this method in autocompletion list.
