### ISSUE TITLE
Query : How to add JSON object argument in a decorator

### ISSUE THREAD

**Issue by SanthoshHari912** [dsherret/ts-morph#379]
Hi,
 I 'm using ts-simple-ast to generate an angular-component file. I wish to add the below decorator to the class declaration
```
@Component({
	selector: 'my-demo',
	templateUrl: './my-demo.component.html',
	styleUrls: ['./my-demo.component.scss'],
	encapsulation: ViewEncapsulation.None
})
```
If I use the below api, am not able to pass object as argument
 `classDeclaration.addDecorator({ name: "Component", arguments: [{ <json object here>}] });`

Any help is appreciated :-)
Thanks
Santhosh

**Comment by SanthoshHari912** [comment]
I have got it resolved by passing the object as string. It gets resolved as ObjectLiteralExpression in AST

**Comment by dsherret** [comment]
Hi @SanthoshHari912, yes that's correct—you'll need to pass it as a string.

This is a similar problem to #320. I'll be looking at some better solutions than using a string in that issue.
