### ISSUE TITLE
Question : How to create the AST for typescript file content passed as string

### ISSUE THREAD

**Issue by SanthoshHari912** [dsherret/ts-morph#385]
I have an usecase where the ts file is in server and I get the string content of this. Is it possible to build an AST using the string content instead of the file path or tsconfig ?

**Comment by lazarljubenovic** [comment]
I do this all the time in tests.

```ts
export function createProjectFromString (fileContent: string): {
  project: Project,
  sourceFile: SourceFile,
} {
  const project = new Project({
    useVirtualFileSystem: true,
    manipulationSettings: { indentationText: IndentationText.TwoSpaces },
  })
  const sourceFile = project.createSourceFile('__temp__.ts', fileContent)
  return { project, sourceFile }
}
```

**Comment by dsherret** [comment]
Thanks @lazarljubenovic! That's exactly right. You can use the `createSourceFile` function on an instance of the default export—`Project`.

**Comment by SanthoshHari912** [comment]
Thanks a lot @lazarljubenovic  & @dsherret . It worked. My suggestion if this option can be mentioned in https://dsherret.github.io/ts-simple-ast/details/source-files it will be helpful.

**Comment by dsherret** [comment]
@SanthoshHari912 thanks, that makes sense. I will provide a link there to https://dsherret.github.io/ts-simple-ast/setup/adding-source-files -- Opened #387.
