### ISSUE TITLE
Question : Is there an option to add property value while adding property to class declaration

### ISSUE THREAD

**Issue by SanthoshHari912** [dsherret/ts-morph#392]
Am using the below api to add a property to class
```
classDeclaration.addProperty({
					isStatic: false,
					name: propertyName,
					type: propertyType
				})
```

Am not able to specify value for the property. It will be nice if there is an option to  provide value.
I want to achieve the below usecase

```
Class A {
   test = 'myTestString'
}
```

**Comment by lazarljubenovic** [comment]
The prop you're lookin for is called `initializer`.

```ts
    this.classDeclaration.addProperty({
      name: 'test',
      initializer: '"my test string"',
    })
```

**Comment by SanthoshHari912** [comment]
Thanks @lazarljubenovic . How do we update an exisiting property ?

**Comment by lazarljubenovic** [comment]
First get the prop declaration with `getProperty` or similar.

```ts
const propDeclaration = classDeclaration.getPropertyOrThrow('oldName')
```

Then use the method `fill` which accepts the same argument as `ClassDeclaration#addProperty` to change it.

```ts
propDeclaration.fill({
  name: 'newName',
})
```

**Comment by SanthoshHari912** [comment]
Thanks a lot :-)

**Comment by dsherret** [comment]
Thanks @lazarljubenovic for answering this!

@SanthoshHari912 alternatively use `propDeclaration.setInitializer("newName")`.

**Comment by kyyash** [comment]
propertyDecln.fill does not work

with 18.0 version of ts simple ast.

**Comment by dsherret** [comment]
@kyyash `.fill` is now called `.set({ initializer: "newName" })`. For this scenario it's best to use `.setInitializer("newName")` though.

Read the breaking changes document for more info: https://github.com/dsherret/ts-simple-ast/blob/master/breaking-changes.md#fill-methods-are-now-set
