### ISSUE TITLE
Inconsistent/incorrect file path case from getFilePath

### ISSUE THREAD

**Issue by rhys-vdw** [dsherret/ts-morph#394]
**Describe the bug**
Version: 13.0.0

Path returned by `SourceFile.getFilePath()` has incorrect case when retrieved via a `Type` -> `Symbol` -> `InterfaceDeclaration`, but not when retrieved via `Project#getSourceFiles`

Not sure if I'm doing something wrong, I'm very new to this library.

**To Reproduce**

```ts
project.getSourceFiles().forEach(sourceFile => {
    console.log("path " + sourceFile.getFilePath())
    // path /Users/rhys/Projects/ts-auto-guard-test/src/Thing.ts - CORRECT

// ...

if (type.isInterface()) {
    const declarations = type.getSymbol()!.getDeclarations();
    const declaration = declarations.find(TypeGuards.isInterfaceDeclaration)!;
    const sourcePath = declaration.getSourceFile()!.getFilePath()
    console.log("path " + sourcePath)
    // path /Users/rhys/Projects/ts-auto-guard-test/src/thing.ts - INCORRECT
}
```

**Expected behavior**

Paths are same as the file path, maintaining capitalization.

**Comment by dsherret** [comment]
Hey @rhys-vdw, thanks for reporting this! I haven't been able to reproduce it in v13 though.

```ts
import Project from "ts-simple-ast";

const searchingFilePath = "/folder/MyInterface.ts";
const project = new Project({ useVirtualFileSystem: true });
const interfaceSourceFile = project.createSourceFile(searchingFilePath, "export interface MyInterface {}");
const sourceFile = project.createSourceFile("/folder/main.ts", "import { MyInterface } from './MyInterface';\n\nlet myVar: MyInterface;");
const varDeclaration = sourceFile.getVariableDeclarationOrThrow("myVar");
const declarations = varDeclaration.getType().getSymbolOrThrow().getDeclarations();

console.log(declarations[0].getSourceFile().getFilePath());
```

I also tried using a non-virtual file system on a linux machine, but no luck. Would you be able to provide a short example that reproduces it? Also, are you doing any manipulations in between?

Also, perhaps try to see if it still happens for you v14.0.1. I moved some functionality from the compiler api into this library and that might have unintentionally fixed this bug. I suspect it's a downstream problem (unless I missed setting a `useCaseSensitiveFileNames` flag somewhere) because I don't ever change the file name casing.

**Comment by rhys-vdw** [comment]
> I also tried using a non-virtual file system on a linux machine, but no luck. Would you be able to provide a short example that reproduces it? Also, are you doing any manipulations in between?

Sure, I'll do my best. It may be a problem on my end (or an issue with MacOS maybe?), but I'm not sure what I could be doing to have this effect. The code above is the only stuff that's touching file paths.

**Comment by rhys-vdw** [comment]
Yeah, sure. Sorry that I haven't trimmed it down, but if you're interested in having a look you can see the program [here](https://github.com/rhys-vdw/ts-auto-guard/tree/7635fcd280759b7f145b55fe09f6839c39daa985). The problematic line is [here](https://github.com/rhys-vdw/ts-auto-guard/blob/7635fcd280759b7f145b55fe09f6839c39daa985/src/index.ts#L212).

This is the input I used (two files in a `src` folder).

`src/person.ts`
```ts
import Thing from "./thing"

/** @see {isPerson} ts-auto-guard:type-guard */
export interface Person {
    thing: Thing,
}
```

`src/thing.ts`
```ts
/** @see {isThing} ts-auto-guard:type-guard */
interface Thing {
  bar: 5,
}
export default Thing
```

Instructions for running the program are in the README.

**Comment by dsherret** [comment]
Yeah, I was just thinking that. It's definitely related to that.

Thanks for the code! I can reproduce it on windows and I'll start diagnosing why this is happening soon. I have a feeling it might be in the compiler api though.

**Comment by rhys-vdw** [comment]
Thanks, loving your library btw, it's made this project really easy. Open to any feedback on the code too if you see anything I'm doing wrong. I'm new to this.

**Comment by dsherret** [comment]
@rhys-vdw awesome! I'm glad it's working out for you. Also, that's a great idea for a library! It's a scenario this library is perfect for helping out with.

I'll take a deeper look sometime this week. This bug is lower priority than I initially thought.

**Comment by rhys-vdw** [comment]
> I'll take a deeper look sometime this week. This bug is lower priority than I initially thought.

Absolutely. Me too. ;)
