### ISSUE TITLE
Questions: does this support incremental building

### ISSUE THREAD

**Issue by fenduru** [dsherret/ts-morph#398]
I tried code digging a bit, but was unable to tell if this project will use the incremental building features of Typescript language service. For instance, if I call `project.createSourceFile('existingFile.ts', 'newContents', { overwrite: true })`, will this cause recompilation of all unchanged files? Or just the ones that are downstream of the changed file?

I'm really interested in trying to build tooling around Typescript programatically, but am trying to avoid using the compiler API directly as it is a bit arcane

**Comment by dsherret** [comment]
Hey @fenduru, yes, in version 14 it should now properly be using the incremental building features of the language service (assuming this is the way to do it: https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#incremental-build-support-using-the-language-services). Previously it wasn't implemented properly.

Some additional notes:

* When calling `project.createSourceFile(...)` or doing a manipulation, the program and type checker will be marked dirty. The next time they're accessed they'll be recreated behind the scenes and the typescript compiler will attempt to use the previous program to construct the new one. It's not always successful though and sometimes it needs to recreate everything.
* Pre-version 14, it would parse files a second time in the language service, but now in version 14 it's been optimized to share parsed source files between the rest of the library. I'd like to use the incremental parsing sometime in the future, but I'll have to see how well it works.

Hopefully that answers your question. Let me know if you have any more!

**Comment by zxti** [comment]
@dsherret Hi, is this still supported in ts-morph?  I didn't find any trace of file watching in the new codebase....

**Comment by dsherret** [comment]
@zxti are you wondering about the new incremental builds released in ts 3.4? This issue has to do with incremental building within the language service.

For incremental builds as in the `--incremental` flag, that won't be in the compiler API until TS 3.5.

**Comment by dsherret** [comment]
@zxti oh, or are you asking about the ability to have file watching?

**Comment by zxti** [comment]
@dsherret Ah yeah I'm asking about file watching, not the incremental feature in 3.4 - sorry, overloaded terminology!

**Comment by dsherret** [comment]
@zxti yeah, sorry I was confused haha. File watching isn't implemented in the library. I just opened up #608. Take a look at the information in there.
