### ISSUE TITLE
Emit changes without saving to filesystem

### ISSUE THREAD

**Issue by sajal50** [dsherret/ts-morph#403]
Is it possible to `emit()` changes without calling `project.save()`? `save()` commits all the changes to the filesystem. I wish to `emit()` without saving the changes to the filesystem.

**Comment by dsherret** [comment]
I see you found out.

For anyone else: it's actually a commonish question and the answer is yes. Just call `.emit()` without calling `.save()` 😃

**Comment by sajal50** [comment]
Yeah, that was my bad. 
Thanks :smiley:
