### ISSUE TITLE
Possible to change structure of source files in memory

### ISSUE THREAD

**Issue by sajal50** [dsherret/ts-morph#412]
Is it possible to move/copy files around after `project.addExistingSourceFiles("*.ts");` in memory rather than committing to the file system and then build? Current `sourceFile.copyImmediately("foo.ts");` makes changes to the file system.

**Comment by dsherret** [comment]
Yes, use `.copy` instead of `.copyImmediately`.

**Comment by sajal50** [comment]
And `.move()` is available as well?

**Comment by dsherret** [comment]
Yup.

**Comment by sajal50** [comment]
Thanks for the quick reply! :smiley:

**Comment by dsherret** [comment]
No problem! Let me know if you run into any issues or unexpected behaviour. The internals of that part of the library is extremely complex, but it should work well.

**Comment by sajal50** [comment]
Sure, will do!
