### ISSUE TITLE
This code causes unexpected behavior for 'getProperties()' & 'getFullText()'

### ISSUE THREAD

**Issue by ihorskyi** [dsherret/ts-morph#416]
Version: 14.4.3

**To Reproduce**: Run code below 

**Expected behavior**: described in code comments

```typescript
import Project from 'ts-simple-ast'

const project = new Project({ useVirtualFileSystem:true })
const file    = project.createSourceFile('file.ts')

file.addStatements(getFileContents())

const iface = file.getInterfaceOrThrow('SomeThing')
const props = iface.getProperties()

// Logging out to see that result is not as expected
// should be 2 props, but there are 3
props.forEach(prop => {
  console.log(prop.getFullText())
})

// Now some mutations involved for every property
props.forEach(prop => {
  const line = prop.getFullText()
  prop.replaceWithText(line + '                 // "new comment"')
})

console.log('\n'.repeat(3), '-'.repeat(30))

// "new comment" was added in the middle, expected at the end
// in addition there are 6 lines, expected 4
console.log(iface.getFullText())


function getFileContents() {
  return `export interface SomeThing {
uuid: string // .guid(version:uuidv4).trim()
bit: 0 | 1
} `
}

```

**Comment by dsherret** [comment]
@ihorskyi `props.length` returns 2 for me as expected. Are you sure that's the correct code?

Should be `"\nuuid: string"` and `" // .guid(version:uuidv4).trim()\nbit: 0 | 1"`. Note the result of `pos`, `end` and `getFullText()` on the `PropertySignature` nodes after pasting the code into this website: https://ts-ast-viewer.com

Additionally, `.replaceWithText()` will only replace from the position of `.getStart(true)` (the first token or jsdoc) and not `.getPos()`. Instead of `.getFullText()` try using `.getText()` like so:

```ts
props.forEach(prop => {
  const line = prop.getText();
  prop.replaceWithText(line + '                 // "new comment"');
});
```

Should output:

```ts
export interface SomeThing {
    uuid: string                 // "new comment" // .guid(version:uuidv4).trim()
    bit: 0 | 1                 // "new comment"
}
```

Right now there's not much support for comments beyond getting them.

**Comment by dsherret** [comment]
Hmmm... I'm just thinking that it should probably be doing `.getStart()` instead of `.getStart(true)` since `.getText()` only returns the text from `.getStart()` to `.getEnd()` (btw, it having the boolean parameter is copying what's done in the compiler api... I would never choose that).

**Comment by ihorskyi** [comment]
You right, `props.length` returns 2, just `console.log(prop.getFullText())` shows like there 3 lines instead of 2 because it parses it with additional `\n` and chopped up comment.

Thanks for suggestion about `prop.getText()`, it works well for my case :)

I also tried
```javascript
prop.getText(true)
```
but it says `error TS2554: Expected 0 arguments, but got 1.`

and seems that's expected b/c in `main.d.ts` it's declared as
```typescript
/**
 * Gets the text without leading trivia (comments and whitespace).
 */
getText(): string;
```

**Comment by dsherret** [comment]
Yeah, there's no `.getText(true)`. The `.getStart()`, `.getStart(true)`, `.getText()`, `.getFullText()`, and a few other methods just call those exact same methods on the nodes in the compiler api.
