### ISSUE TITLE
How to make getKind() future-proof?

### ISSUE THREAD

**Issue by elclanrs** [dsherret/ts-morph#427]
Version: 14.4.5

I have the following expression:

```typescript
const ts = require('typescript');

return prop.getKind() === ts.SyntaxKind.PropertyDeclaration;
```

Before I upgraded ts-simple-ast and typescript this used to work, and would get inlined as `152 === 152`.

After the latest upgrade this stopped working because now it inlines as `152 === 151`.

I think this is related to a mismatch between the version of TS this library uses VS what my own package.json version is.

How can I make this expression future-proof?

**Comment by Gerrit0** [comment]
You should import everything from `ts-simple-ast`. I'm not on a PC right now but I'm pretty sure it exports the `SyntaxKind` enum that it uses.

There are also type guards `isPropertyDeclaration`

**Comment by elclanrs** [comment]
Thank you! That's just what I needed.
