### ISSUE TITLE
[Doc Request]: Add example how to find reference of a named import in a source file

### ISSUE THREAD

**Issue by bigopon** [dsherret/ts-morph#430]
I tried to look for different parts of the documentation but failed to find the instruction how to find references of `Klass` in a source file, via following example:

```ts
import { Klass } from 'module';

var klass = new Klass();

function config() {
  const klass1 = new Klass();
}
```

Is there a way to find all 2 references to `Klass` ?

**Comment by dsherret** [comment]
@bigopon do you mean something like this?

```ts
const project = new Project({ useVirtualFileSystem: true });

const klassFile = project.createSourceFile("Klass.ts", "export class Klass {\n}\n");
const otherFile = project.createSourceFile("main.ts", `import { Klass } from './Klass';

var klass = new Klass();

function config() {
  const klass1 = new Klass();
}`);

const nodes = klassFile.getClassOrThrow("Klass").findReferencesAsNodes().filter(n => n.getSourceFile() === otherFile);

console.log(nodes); // contains the 3 identifier nodes of Klass in that file
```

Read more on finding references [here](https://dsherret.github.io/ts-simple-ast/navigation/finding-references) and let me know if you have any ideas for how it can be improved.

**Comment by bigopon** [comment]
It works if we control both source file. What I was asking is close to what you shown, but different.
1. Supposed we import something from an external module, we probably don't have the source file to include it in the project, so the above approach is not suitable I guess.
2. We already have `Klass` as "local variable" declared on top of the find, I was thinking maybe there is a way to find all references of that declaration ?

**Comment by bigopon** [comment]
`1.` sounds good, I will need to try `2.`. For me, it's the lack of a way to find references of a local variable within a scope that I think the lib needs to tackle.

**Comment by bigopon** [comment]
@dsherret Another reason to have this is the error resilience, when you specify wrong import name in consumer source file, but all local reference are right. It should work just fine without having to go back to find the class in declaration source file
```ts
import { A } from 'module-without-A-export'

a = new A(); // only import { A } is wrong, a = new A is totally valid.
```

**Comment by dsherret** [comment]
There is now a `const moduleSymbol = project.getAmbientModule("module-name")` method (https://dsherret.github.io/ts-simple-ast/navigation/ambient-modules). From that symbol, the source file or source files can be found.

By the way, it should be possible to do the following:

```ts
// untested
const importDec = sourceFile.getImportDeclarationOrThrow("module-without-A-export");
const namedImport = importDec.getNamedImports().find(i => i.getName() === "A")!;
const nameNode = namedImport.getNameNode();

const nodes = nameNode.findReferencesAsNodes()
    .filter(n => n.getSourceFile() === sourceFile
        && !TypeGuards.isImportSpecifier(n.getParentOrThrow());
```
