### ISSUE TITLE
Rename property renames also destructuring declaration

### ISSUE THREAD

**Issue by maximelkin** [dsherret/ts-morph#434]
**Describe the bug**
Version: latest

**To Reproduce**
```ts
interface A {
 test: 'string';
}
const b = {test: 'str'};
const {test}: A = b;

// rename test in A

const b = {test: 'str'};
const { test_2 } = b;
```
**Expected behavior**
change structure of b variable

**Comment by dsherret** [comment]
Related to #433.

**Comment by maximelkin** [comment]
No, it;s different problem
Bug not reproducing if `const {test} = b;` (removed type declaration for left side)

**Comment by dsherret** [comment]
@maximelkin true, but still related.

I didn't look at this in detail until now, but I'm not sure this is a bug because that's not semantically correct typescript code (it has a compile error in it).

**Comment by maximelkin** [comment]
Sorry, redundant ''
```ts
interface A {
 test: string;
}
const b = {test: 'str'};
const {test}: A = b;
```
After rename test in A test property of b not renamed

**Comment by dsherret** [comment]
@maximelkin ah, ok. Sorry, didn't notice the string literal type (I'm focusing on a different task at the moment). Thanks!

Yeah, this will need to be fixed in the compiler API as well. Same behaviour happens to me in the editor.

**Comment by dsherret** [comment]
See my comment here: https://github.com/dsherret/ts-morph/issues/433#issuecomment-498042194

This now renames that to the following:

```ts
const b = { test: 'str' };
const { test: test_2 } = b;
```
