### ISSUE TITLE
Analysis only version of ts-morph

### ISSUE THREAD

**Issue by vogloblinsky** [dsherret/ts-morph#448]
I tried to use ts-simple-ast in a project in a browser.
I convert it using browserify, and the generated file, minified, is around 4.5Mb.
This issue is here to discuss how we can achieve a lightest build, for example i didn't need the manipulation part of the library.

**Comment by dsherret** [comment]
As discussed earlier, the idea here would be to see if it's worthwhile to produce an analysis only version of the library that only allows adding source files. This process would be automated from the existing library.

Right now on disk, ts-simple-ast itself seems to be 2.14MB unminified so I think the TypeScript compiler itself takes up most of that 4.5MB. Not sure if it's worth it to go through the effort to do this at the moment.

**Comment by dsherret** [comment]
Putting this one on hold for the next while.

**Comment by dsherret** [comment]
Not going to do this anymore. Might be good to use as it's a bit more lightweight: https://github.com/dsherret/ts-morph/tree/latest/packages/bootstrap
