### ISSUE TITLE
How to get method or function name if I know the expression used in it.

### ISSUE THREAD

**Issue by asingh3886** [dsherret/ts-morph#451]
I got the list of all the expressions using below code.
sourceFile.getDescendantsOfKind(SyntaxKind.CallExpression)
How to get the name of method or function from above expression name. In other words, I wanted to know the parent of the expressions used in the method.

**Comment by dsherret** [comment]
Try something like the following:

```ts
for (const callExpr of sourceFile.getDescendantsOfKind(SyntaxKind.CallExpression)) {
    const expr = callExpr.getExpression();
    if (TypeGuards.isIdentifier(expr) || TypeGuards.isPropertyAccessExpression(expr))
        console.log(expr.getText())
    else
        console.warn(`Not implemented call expression expression with kind: ${expr.getKindName()}`);
}
```

Note that call expressions can have expressions that are not just identifiers (ex. `MyIdentifier`) or property access expressions (ex. `MyModule.MyIdentifier`). For example, the following is not handled by the code above: `someObj["someMethod"]()`

Btw, using https://ts-ast-viewer.com is useful to help understand this.
