### ISSUE TITLE
getReturnType().getText() is returning inline import

### ISSUE THREAD

**Issue by vip30** [dsherret/ts-morph#453]
Firstly, this repo is really good. 
It fit my use cases but just one thing I can't figure out.

This is my target class file
```ts
// class.ts
import { Hello } from './somewhere'

export class HelloWorld {
  public async sayHi() {
    const result: Hello = {}
    return result
  }
}
```

This is my pseudo builder file
```ts
// builder.ts
     // some import statement will be generated in newFile
     const namespace = 'abc'
     newFile.addInterface({
        name: className,
        isExported: true,
        methods:
            .
            .
            somefile.getInstanceMethods().forEach(method => {
              return { 
                parameter: method.getParameters().map(para => para.getStructure()),
                name: `"${namespace}/${method.getName()}"`,
                returnType: method.getReturnType().getText()
              }
            }
      )}
```

What I want to do is base on the class, to build a interface with some extra character in the method name

This is what I want
```ts
import statement.....

export interface HelloWorld {
    "abc/sayHi"(): Promise<Hello>;
}
```

This is what I finally get
```ts
import statement.....

export interface HelloWorld {
    "abc/sayHi"(): Promise<import("xxxxxx/xxxx/xxxxx/somewhere").Hello>;
}
```

Sorry about putting a question on here as I don't know where can I put the question.
But can you please suggest some methods to retrieve the Hello only without the inline import statement?
Thanks

**Comment by dsherret** [comment]
Hey @vip30. Thanks! I'm glad it's working out for you.

Yeah, this is because of [import types](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html) introduced in ts 2.9. So it's a compiler api behaviour of getting the type text.

Similarly to #450, it seems it's possible to remove this by passing in the enclosing node to `returnType.getText()`. See this example:

```ts
import { Project, TypeFormatFlags } from "ts-simple-ast";

const project = new Project({ useVirtualFileSystem: true });
const sourceFile = project.createSourceFile("Class.ts", "export class Class { prop: string; }");
const mainFile = project.createSourceFile("main.ts", "import { Class } from './Class'; function myFunc() { return new Class(); }");

const funcDec = mainFile.getFunctionOrThrow("myFunc");
console.log(funcDec.getReturnType().getText()); // outputs: import("/Class").Class
console.log(funcDec.getReturnType().getText(varDec)); // outputs: Class
```

That said, there might be a way to make this work using `TypeFormatFlags` alone (second param of getText), but I'm not sure.

**Comment by dsherret** [comment]
Closing. Let me know if you find a better way of doing this or you have any more questions.

**Comment by yantrab** [comment]
what is 'varDec' in :
console.log(funcDec.getReturnType().getText(varDec));

**Comment by dsherret** [comment]
@yantrab sorry that should be `funcDec`. Updated.

**Comment by aleclarson** [comment]
It should be noted that, if your function returns a type not directly imported, the `import("...").Class` type is not simplified.

Proof: https://codesandbox.io/s/ts-morph-543-viffn

**Comment by aleclarson** [comment]
Passing `TypeFormatFlags.UseAliasDefinedOutsideCurrentScope` to the `getText` method fixes the issue. 🎉 

Source: https://twitter.com/drosenwasser/status/1289640180035403776
