### ISSUE TITLE
Question: How to get the type of an interface property

### ISSUE THREAD

**Issue by calebeby** [dsherret/ts-morph#457]
Say I had this code that I wanted to analyze:

```ts
interface Asdf {
  name: string | number
  id: string
}
```

How would I get a `Type` for each property?

I have tried using `Type.getProperties()` in order to retrieve the types of the properties, but I am given `Symbol`s, with which I am unsure how to get a type from.

```ts
Type.getProperties().forEach(prop => {
  prop.getDeclaredType() // ??? returns a type of any
  prop.getTypeAtLocation(node) // ??? I don't have a node to pass it
})
```

How would this be possible? I couldn't find this in the documentation (maybe I'd be willing to make a PR to the docs for if you explain this :stuck_out_tongue:)

Thanks for this awesome project :tada:

**Comment by dsherret** [comment]
Interesting. Seems like `getDeclaredTypeOfSymbol` is defined this way in the compiler api, so it will always return `any` for properties:

```ts
function getDeclaredTypeOfSymbol(symbol: Symbol): Type {
    return tryGetDeclaredTypeOfSymbol(symbol) || errorType;
}

function tryGetDeclaredTypeOfSymbol(symbol: Symbol): Type | undefined {
    if (symbol.flags & (SymbolFlags.Class | SymbolFlags.Interface)) {
        return getDeclaredTypeOfClassOrInterface(symbol);
    }
    if (symbol.flags & SymbolFlags.TypeAlias) {
        return getDeclaredTypeOfTypeAlias(symbol);
    }
    if (symbol.flags & SymbolFlags.TypeParameter) {
        return getDeclaredTypeOfTypeParameter(symbol);
    }
    if (symbol.flags & SymbolFlags.Enum) {
        return getDeclaredTypeOfEnum(symbol);
    }
    if (symbol.flags & SymbolFlags.EnumMember) {
        return getDeclaredTypeOfEnumMember(symbol);
    }
    if (symbol.flags & SymbolFlags.Alias) {
        return getDeclaredTypeOfAlias(symbol);
    }
    return undefined;
}
```

You could do the following, though I'm not sure if it's the right way of doing things:

```ts
for (const prop of Type.getProperties())
    console.log(prop.getValueDeclarationOrThrow().getType().getText());
```

Alternatively, stick with the interface declaration and iterate over its properties in the ast:

```ts
const interfaceDec = sourceFile.getInterfaceOrThrow("Asdf");
for (const prop of interfaceDec.getProperties())
    console.log(prop.getType().getText());
```

Also, thanks! I'm glad it's working out for you. As for submitting a PR to update the docs... don't worry about it for the moment because it's a little specific. I'll add more docs around symbols in the future.

**Comment by calebeby** [comment]
Ok... I think this will present another problem:

Say I want to loop over the properties of a mapped type:

```ts
interface Asdf {
  name: string | number
  id: string
}

type Something = Partial<Asdf>
```

Now I can't get the value declaration because it is not explicitly created...

I had some luck in getting a type using this:

```ts
Type.getProperties().forEach(prop => {
  console.log(prop.compilerSymbol.type)
})
```

(which seems to not be documented, and also returns a TS type rather than a wapped type)

**Comment by dsherret** [comment]
Yeah, the `compilerSymbol` is the symbol from the compiler api so it will only have compiler api objects on it.

`ts.Symbol` in the compiler API doesn't have that property as part of the public api so it can't be relied on:

```ts
interface Symbol {
    readonly name: string;
    getFlags(): SymbolFlags;
    getEscapedName(): __String;
    getName(): string;
    getDeclarations(): Declaration[] | undefined;
    getDocumentationComment(typeChecker: TypeChecker | undefined): SymbolDisplayPart[];
    getJsDocTags(): JSDocTagInfo[];
}
interface Symbol {
    flags: SymbolFlags;
    escapedName: __String;
    declarations: Declaration[];
    valueDeclaration: Declaration;
    members?: SymbolTable;
    exports?: SymbolTable;
    globalExports?: SymbolTable;
}
```

Try this out. I've found the following code works:

```ts
const somethingTypeAlias = sourceFile.getTypeAliasOrThrow("Something");
const somethingType = somethingTypeAlias.getType();
const properties = somethingType.getProperties();

for (const prop of properties)
    console.log(prop.getTypeAtLocation(somethingTypeAlias).getText());
```

**Comment by calebeby** [comment]
Awesome, that worked, thanks!

**Comment by jingzhou123** [comment]
so i know how to get the value, but how to get the key?

**Comment by jingzhou123** [comment]
oh...i know, that's getName...

**Comment by EmiyaYang** [comment]
marvellous!
