### ISSUE TITLE
Question: get recursively extended class names

### ISSUE THREAD

**Issue by no-more** [dsherret/ts-morph#462]
Hello,

First of all this project is amazing ! Thanks a lot.

I'm building a tool that loads several projects, in those projects I need to identify which file contains a class that extends a named class "MyRootClass", directly or indirectly(through one or more intermediate classes).
For example I have in project A
```
export class MyRootClass{}
...
export class A extends MyRootClass{}
```
in a project B I have
```
export class B extends A{} // A from project A
```
I want to be able to detect that class B extends MyRootClass. How can I do that please ?

on `ClassDeclaration` there's a `getExtends` method but I don't understand how to use it as it does not return a `ClassDeclaration`. The returned object does not contains `getName()` property, and I don't know if it's possible to use `getExtends` recursively.

Thanks for any help.

**Comment by dsherret** [comment]
@no-more sorry for the long response.

Generally, if they are in the same project, this can be done by using `.getDerivedClasses()`:

https://dsherret.github.io/ts-simple-ast/details/classes#derived-classes

```ts
const myRootClass = sourceFile.getClassOrThrow("MyRootClass");
const derivedClassesSet = new Set(myRootClass.getDerivedClasses());
const classB = otherSourceFile.getClassOrThrow("B");

if (derivedClassesSet.has(classB)) {
    // do something
}
```

...or alternatively, recursively calling `.getBaseClass()` on classes like `B` to see if they inherit from `MyRootClass`, but I think that will be a lot slower than the above (I haven't tested it to see though). Side note: I could perhaps add a method to return an array that contains the base class and that base class' base class, etc. `getBaseClasses()`? What do you think?

As for multiple projects, are you using ["project references"](https://www.typescriptlang.org/docs/handbook/project-references.html)? Does calling `.getBaseClass()` on `class B` return anything? If not, then it might not be configured properly.

**Comment by no-more** [comment]
Thanks for you response,

I'll try this later this week and tell you if it's working as expected.

**Comment by dsherret** [comment]
Closing for now. Please reopen if this doesn't work or you need more details.
