### ISSUE TITLE
Blank line between properties

### ISSUE THREAD

**Issue by RWOverdijk** [dsherret/ts-morph#474]
First things first, amazing work 👌 I'm really happy you built this.

That being said, there's one teensy tiny thing that I can't seem to get working.

Whenever I add properties _(or update using `.set()` with a new structure)_ all newlines are removed.

Here's a tiny example:

**testrun.js**

```js
const {Project} = require('ts-simple-ast');

const project = new Project({
  manipulationSettings: {
    indentationText: '  '
  }
});

project.addExistingSourceFiles('User.ts');

const f = project.getSourceFileOrThrow('User.ts');
const c = f.getClass('User');
const s = c.getStructure();

c.set({
  properties: [
    ...s.properties,
    {
      name: "motto",
      type: "string",
      decorators: [
        {
          name: "field",
          arguments: [`{ type: 'string' }`]
        }
      ]
    }
  ]
});

f.formatText();

project.save();
```

And the source file (**User.ts**) I'm manipulating:

```ts
import { field, autoFields, entity, Mapping, MetaData } from 'wetland';

@autoFields()
@entity()
export class User {
  @field({ type: 'string' })
  username: string;

  @field({ type: 'string' })
  password: string;

  @field({ type: 'timestamp', nullable: true })
  lastLogin: number;
}

```

After the save, I end up with the following:

```ts
import { field, autoFields, entity, Mapping, MetaData } from 'wetland';

@autoFields()
@entity()
export class User {
  @field({ type: 'string' })
  username: string;
  @field({ type: 'string' })
  password: string;
  @field({ type: 'timestamp', nullable: true })
  lastLogin: number;
  @field({ type: 'string' })
  motto: string;
}
```

The same happens when I simply use addProperty().

Again, thanks for your amazing work, this is allowing me to make better tools for our open source projects 🙌

**Comment by RWOverdijk** [comment]
**Update:** I found writers, so I could write but I can't get in between properties when creating a class.

`file.insertText(magicalNumberIHaveYetToFind, writer => writer.writeLine('\n));`

So.. I could find the index and write a newline afterwards but I'm confident I'm just missing something.

**Comment by dsherret** [comment]
Hey @RWOverdijk, right now the default setting between properties is for a newline and not a blank line. I'd have to either add a global manipulation setting to control spacing between properties and/or add another parameter to `.addProperty`-like methods that allows you to set the spacing.

For the time being, you could probably use the `appendWhitespace` method that exists on every node.

For example, I believe this will work:

```ts
f.getClass('User').addProperties(...etc...).forEach(p => p.appendWhitespace(writer => writer.newLine()));
```

**Comment by RWOverdijk** [comment]
That does work. Thanks. :)

**Comment by RWOverdijk** [comment]
@dsherret What do you mean? You want me to extract the update, or this snippet?

**Comment by RWOverdijk** [comment]
Ah! Yes that's exactly what I did. 

```ts
classDeclaration
  .addProperties(fields)
  .slice(0, -1)
  .forEach(p => p.appendWhitespace(writer => writer.newLine()));
```

**Comment by dsherret** [comment]
In version 2 it will be possible to do the following:

```ts
classDec.addProperty({
    leadingTrivia: writer => writer.newLine(),
    name: "prop2"
});
```

This can be extracted out to a function:

```ts
function setLeadingNewline<T extends Structure>(structure: T) {
    structure.leadingTrivia = writer => writer.newLine();
    return structure;
}
```

I'd still like a global option to add blank lines between properties though.

**Comment by dsherret** [comment]
I'm going to close this. If anyone wants to do this they can use the solution described above.

I don't believe I will be adding any more configuration for changing how the code looks. I'm currently developing a code formatter that will have a lot of configuration (https://github.com/dsherret/dprint) and that could be used with #664 

Basically, it's extremely hard to get code formatting right and it's better for it to be its own dedicated thing and that will be what dprint is for.
