### ISSUE TITLE
SourceFile top level comment

### ISSUE THREAD

**Issue by sosoba** [dsherret/ts-morph#486]
Hello. I use ts-simple-ast to generate the code like this:
```
const sourceFile = typescriptProject.createSourceFile(...);
...
sourceFile.save();
```
Because output code is not written by man, it should not be analyzed by the linter.
How can I add top level comment like
`// tslint:disable`
to prevent analysis?

**Comment by Gerrit0** [comment]
You can use `addStatements`, `insertStatements` or `addStatement` with a writer. See [docs](https://dsherret.github.io/ts-simple-ast/manipulation/#adding-inserting-and-removing-statements)

```ts
sourceFile.insertStatements(0, "// tslint:disable");

```

**Comment by dsherret** [comment]
Yup that's it. Thanks @Gerrit0!

@sosoba I recommend doing that as the last step because of #189. That has to do with how comments are not stored in the ast.
