### ISSUE TITLE
Can I read/set nested structures?

### ISSUE THREAD

**Issue by mi5ha** [dsherret/ts-morph#496]
For example when I am creating variable with nested object as value, I create VariableStatement node with a structure like this:

```
{
    declarationKind: VariableDeclarationKind.Var,
    declarations: [{name:'foo', initializer:"{\n    bar: 42,\n    mar: {\n        dar: 'Hello'\n    }\n}"}]
}
```

But initializer here is string? Can this initializer be nested structures that describe ObjectLiteralExpression nodes and PropertyAssignment nodes and everything that is needed to construct VariableStatement?

**Comment by dsherret** [comment]
This is somewhat experimental, but see if it works to use `WriterFunctions.object` (`import { WriterFunctions } from "ts-simple-ast"`):

```ts
initializer: WriterFunctions.object({ bar: 42, mar: WriterFunctions.object({ dar: 'Hello' }))
```

If that doesn't work well for you, you could create your own writer function then reuse that throughout your code. See here for how `WriterFunctions.object` is implemented if you want to do that: https://github.com/dsherret/ts-simple-ast/blob/6e189528cef076e31924566c6c8cc081d7d612e6/src/utils/WriterFunctions.ts (the imports used there are found as named exports from the library—`import { CodeBlockWriter, WriterFunction } from "ts-simple-ast";`)

**Comment by mi5ha** [comment]
Thanx for the directions, will try it out!
