### ISSUE TITLE
Question: Compare files ignoring whitespace and comments

### ISSUE THREAD

**Issue by no-more** [dsherret/ts-morph#499]
Hello,

this might be quite weird, but I'm looking for a way to compare two typescript file but ignoring comments and indentations.
I need to do this before saving a file, if no code changes detected I don't want the file to be saved (in same case).
I was wondering if there was any way to achieve this with ast or if I should code something myself.

Thanks.

**Comment by no-more** [comment]
Thanks a lot, I'll try that later today.

**Comment by dsherret** [comment]
@no-more by the way, after reading #502 I realized that this is possible just using the scanner in the compiler api. It's the fastest solution as you wouldn't have to parse the entire file to figure out if they're the same.

For example:

```ts
import * as ts from "typescript";

console.log(areSame(
    { fileName: "./test.ts", text: "/* testing */ const t  :  \tstring;" },
    { fileName: "./test2.ts", text: "const t: string; // testing" }
));

interface FileInfo {
    fileName: string;
    text: string;
}

function areSame(fileInfo1: FileInfo, fileInfo2: FileInfo) {
    const tokens1 = getTokens(fileInfo1);
    const tokens2 = getTokens(fileInfo2);

    while (true) {
        const token1 = tokens1.next();
        const token2 = tokens2.next();

        if (token1.done && token2.done)
            return true;
        if (token1.done || token2.done)
            return false;
        if (token1.value !== token2.value)
            return false;
    }
}

function* getTokens(fileInfo: FileInfo) {
    const lowerCaseFileName = fileInfo.fileName.toLocaleLowerCase();
    const isJsxOrTsxFile = lowerCaseFileName.endsWith(".tsx") || lowerCaseFileName.endsWith(".jsx")
    const scanner = ts.createScanner(ts.ScriptTarget.Latest, true);
    scanner.setText(fileInfo.text);
    scanner.setOnError(message => console.error(message));
    scanner.setLanguageVariant(isJsxOrTsxFile ? ts.LanguageVariant.JSX : ts.LanguageVariant.Standard);

    let token = scanner.scan();
    while (token !== ts.SyntaxKind.EndOfFileToken) {
        const pos = scanner.getTokenPos();
        token = scanner.scan();
        const end = scanner.getStartPos();
        yield fileInfo.text.substring(pos, end);
    }
}
```

**Comment by no-more** [comment]
Sorry for the late response.
Your solution is working great! Thanks a lot!

**Comment by unlight** [comment]
Did not yet tested code above for my needs.
But is this somewhere published as npm module?

**Comment by dsherret** [comment]
I doubt it. Perhaps it would be appropriate to add this into ts-morph as a method. Maybe `Node#areTokensEqual(node)`?

**Comment by unlight** [comment]
It up to you. But I still did not yet test it.
My method should ignore comments, spaces, trailing commas, type of qoutes, other stylistic stuff.

**Comment by nicmr** [comment]
As a note to future readers of this issue, the above snippets will fail on newer typescript versions with the error `error: TS7023 [ERROR]: 'searchNode' implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.`

This is caused by a breaking change in Typescript Generators. I believe the breaking changes were introduced in typescript >= 4.2.

This can be addressed with the following type annotation (thanks to @jeremyFMP for helping me with this):
```typescript
function areSame(sourceFile1: SourceFile, sourceFile2: SourceFile) {
    const leafNodes1 = getLeafNodes(sourceFile1);
    const leafNodes2 = getLeafNodes(sourceFile2);

    while (true) {
        const leaf1 = leafNodes1.next();
        const leaf2 = leafNodes2.next();

        if (leaf1.done && leaf2.done)
            return true;
        if (leaf1.done || leaf2.done)
            return false;
        if (leaf1.value.getText() !== leaf2.value.getText())
            return false;
    }

    function* getLeafNodes(sourceFile: SourceFile){
        yield* searchNode(sourceFile);

/* -> */function* searchNode(node: Node): Generator<Node, void, Node> {
            const children = node.getChildren();
            if (children.length === 0)
                yield node;
            else {
                for (const child of children)
                    yield* searchNode(child);
            }
        }
    }
}
```
My colleague @guidoschmidt was able to get it running using an Iterator annotation when targeting _esnext_ instead.

```typescript
function* getLeafNodes(sourceFile: ts.SourceFile): Iterator<Node> {
    yield* searchNode(sourceFile);
    function* searchNode(node: ts.Node) {
      const children = node.getChildren(sourceFile);
      if (children.length === 0) yield node;
      else {
        for (const child of children) yield* searchNode(child);
      }
    }
  }
}
```
Lastly and most obviously, the name of the project has since changed to ts-morph, which should  be reflected in the import paths:
```typescript
// Node.js
import { Project, SourceFile, Node } from "ts-morph";
// Deno
import { Project, SourceFile, Node } from "https://deno.land/x/ts_morph/mod.ts";
```
