### ISSUE TITLE
Question: Error when add let-kind variableStatement

### ISSUE THREAD

**Issue by qiansc** [dsherret/ts-morph#500]
Hi,
I have to say ts-simple-ast is an excellent project 👍 

And I have two question after using.

Question 1:
Is there any way to add variableStatement whitout declarationKind, just like 

```javascript
num = 1;  // num has been already declared.
```

Question 2:
I want to add [a variable statement](https://dsherret.github.io/ts-simple-ast/details/variables) such as `let key = 1;` , so try following but got an error (in TS 3.1)：

```javascript
const variableStatement = sourceFile.addVariableStatement({
      declarationKind: VariableDeclarationKind.Let, // defaults to "let"
        declarations: [{
            name: "key",
            initializer: "1",
        }]
});
```

Error: Unexpected! Inserting syntax kind of VariableStatement, but ExpressionStatement was inserted.

 (
Const and Var are both ok, just Let not works.
I found a temporary way to avoid: 
using declarationKind Const when add, and then setDeclarationKind(Let) 
)

Thanks: )

**Comment by dsherret** [comment]
Hey @qiansc. Thanks for the compliment!

**Question 1**

`num = 1;` is an expression statement. You can add it by using `.addStatements` in the block of code you want to add it to:

```ts
sourceFile.addStatements("num = 1;");
// or use a writer
sourceFile.addStatements(writer => writer.write("num = 1;"));
```

**Question 2**

That's very strange, I tried the problem you mentioned with the following code, but was unable to reproduce it. What's the value of `console.log(VariableDeclarationKind.Let)`?

```ts
const project = new Project();
const sourceFile = project.createSourceFile("test.ts", ``);

const variableStatement = sourceFile.addVariableStatement({
      declarationKind: VariableDeclarationKind.Let,
        declarations: [{
            name: "key",
            initializer: "1",
        }]
});
```

Also, what version are you using of ts-simple-ast and what version of typescript is it using (`import { ts } from "ts-simple-ast"; console.log(ts);`)?

**Comment by qiansc** [comment]
I tried again today and suddenly found that the second problem did not recur. Maybe I made a mistake since project tsconfig was wrong yesterday and failed to get tips.

Issue can be closed, thanks a lot!

**Comment by dsherret** [comment]
@qiansc Cool, no problem. I'm glad it's working!
