### ISSUE TITLE
Life time of the temp ts file

### ISSUE THREAD

**Issue by kyyash** [dsherret/ts-morph#509]
What is the life time of the temp ts file we create here, how does it gets cleaned and can we expect any concurrency issues if we use the same file name.

const project = new Project({
			useVirtualFileSystem: true,
		});

		let sourceFile = project.createSourceFile('___temp__.ts', fileContent);

**Comment by dsherret** [comment]
@kyyash sorry for my delay in replying to this!

When calling `let sourceFile = project.createSourceFile("myFile.ts", fileContent);`, that file will exist in memory until `project.save()`, `sourceFile.save()`, or an ancestor directory is saved. Once that happens, it will be also written to the underlying file system (by default, the actual computer's file system and not a virtual one).

During all that time the file is considered as being created by the project, so if you call `project.createSourceFile("myFile.ts", "");` again, it will throw an error saying the file already exists. To not get this error, provide the `overwrite` option: `sourceFile = project.createSourceFile("myFile.ts", "", { overwrite: true })`.

Note that you can also call `sourceFile.delete()` on source files that haven't yet been saved to the file system. Doing this will just remove it from the project and cause it to never be saved to the file system.

Let me know if that helps or if there's any more information you would like to know about.
