### ISSUE TITLE
Navigation in type arguments in property declaration

### ISSUE THREAD

**Issue by philipp-sorin** [dsherret/ts-morph#525]
How can I access to ARG1 and ARG2? 
Now it possible only with compiler api, as far as I understand 

`
class A {
    public property: Map<ARG1, ARG2> = new Map();
}
`

**Comment by philipp-sorin** [comment]
Also, this project is awesome :)

**Comment by dsherret** [comment]
Hey @philipp-sorin! It's possible :)

Using just the ast (only the nodes):

```ts
const typeNode = prop.getTypeNode() as TypeReferenceNode;

console.log(typeNode.getTypeArguments().map(a => a.getText()));
```

Or using the type checker (this is useful when the property is implicitly defined):

```ts
const type = prop.getType();

// ensure this is Map<string, number>. If not, make sure you're targeting at least ES2015 or
// ensure the "lib" compiler option is properly configured
console.log(type.getText());
console.log(type.getTypeArguments().map(a => a.getText())); // ["string", "number"]
```

**Comment by dsherret** [comment]
By the way, https://ts-ast-viewer.com is useful for telling that the type of the property is a type reference.

**Comment by philipp-sorin** [comment]
Cool!! 
Seems like I didn't have Map definition on my local. 
Thanks a lot :)

**Comment by dsherret** [comment]
No problem! Yeah, if you ever get a type resolving to `any` you can try doing `sourceFile.getPreEmitDiagnostics()` or `project.getPreEmitDiagnostics()` to see if there are any compiler errors ([read more](https://dsherret.github.io/ts-simple-ast/setup/diagnostics)).
