### ISSUE TITLE
adding types like classes/interfaces

### ISSUE THREAD

**Issue by brianzinn** [dsherret/ts-morph#529]
It's very easy to add classes and interfaces like:
```javascript
let interfaceDeclaration : InterfaceDeclaration = sourceFile.addInterface({
    name: 'InterfaceName',
    ...
})

const interfaceProperty = interfaceDeclaration .addProperty({
    name: 'name',
    type: 'number',
})
interfaceProperty.setHasQuestionToken(true);
InterfaceDeclaration.addExtends('InterfaceToExtend')
```

I am trying to generate Types and finding that it is not as intuitive.  I can use a similar structure to create the type alias, but it is not as easy to build dynamically:
```javascript
let myType = sourceFile.addTypeAlias({...})
```
In the above example the type must be a string (ok, that string can be `{prop1: value, prop2: value2}`), whereas I want to dynamically add to it.  That part is OK, as I can generate the string.  I can't figure out how to do a `union` or `intersection` on another type.  It would be nice if we had a similar syntax to add intersection/union types and also like interface to add properties.
```javascript
 myType.addProperty({
    name: 'name',
    type: 'number',
})
myType.addIntersection('OtherType')
```

Am I missing something or is this a part of your library that could use a contribution?  I'd like to generate something like: `type NewType = { prop1: number, prop2?: string} & OtherType`

**Comment by dsherret** [comment]
@brianzinn yeah, sorry about that. It's not as intuitive because type aliases can have more than just object types (ex. `type MyType = string | number;`).

There is a currently a helper function for writing out object literal expressions (`WriterFunctions .object` [see here](https://github.com/dsherret/ts-morph/blob/d7575778b340a11c5af8fd21e3955783676f8586/src/utils/WriterFunctions.ts#L16)), but it's not as useful for object types because there's no way to add modifiers or question tokens. Perhaps a `WriterFunctions.objectType` function would be useful.

**Comment by brianzinn** [comment]
That helper function looks useful (and 'objectType' perhaps even more so), although I was able to dynamically generate the string equivalent.

My main question was whether or not there was any way to construct `union` or `intersection` on other Types to generate.  Like above, but also to generate intersection on Types like:
```typescript
type C = A & B;
type D = { prop1: number } & C;
```

**Comment by dsherret** [comment]
@brianzinn for the time being, it's probably easiest to use a writer:

```ts
sourceFile.addTypeAlias({
    name: "NewType",
    type: writer => {
        // write the type in here
    }
});
```

Then create your own writer functions to suit your needs similar to what's done in `WriterFunctions.object`.

I'll add some more functions to `WriterFunctions` so that the following could be done:

```ts
const { intersectionType, objectType } = WriterFunctions;

sourceFile.addTypeAlias({
    name: "NewType",
    type: intersectionType(
        objectType({
            properties: [{ name: "prop1", type: "number" }]
        }),
        "C"
    )
});
```

**Comment by dsherret** [comment]
By the way, as you mentioned, this would also be useful (but on the type node so it would work with types anywhere):

```ts
typeAlias.getTypeNode().addIntersection("C");
```

**Comment by brianzinn** [comment]
that was a fast start!  i'll be keeping a watch on this :) thanks.

**Comment by brianzinn** [comment]
I did a comment on your branch commit.  I was thinking you could avoid needing the 'StructurePrinterFactory' by passing it from the caller, but the changes needed looks to be exploding:
https://github.com/brianzinn/ts-morph/commit/33e97693bf0e1808aa5da5e4b636685beb0bcecb
ps: I tried already passing a new type WriterContext { factory: StructurePrinterFactory }, but then saw that does not fit how writer/factory are designed...

**Comment by dsherret** [comment]
Yeah sorry, I was away in Montreal for a few days. I just merged this and kept it as a static class.

I will look into adding methods for manipulating type nodes in #546.

**Comment by vsviridov** [comment]
So, the `WriterFunctions` is not even available in the current version anymore...

**Comment by SeanSanker** [comment]
> So, the `WriterFunctions` is not even available in the current version anymore...

FYI: @vsviridov, this functionality is still available. It's just been renamed to `Writers`

https://github.com/dsherret/ts-morph/commit/be87373
https://github.com/dsherret/ts-morph/commit/79c6694

```ts
import { Writers } from 'ts-morph'

const { intersectionType, objectType } = Writers
// etc.
```
