### ISSUE TITLE
feature request: JSDocTypeExpression

### ISSUE THREAD

**Issue by Pineapples** [dsherret/ts-morph#530]
I'd like to request a wrapper for JSDocTypeExpression to read out the types of parameters in JSDoc tags.

**Comment by Pineapples** [comment]
I've added a pull request. Seems like your dev is behind on master. Cool project to work on. Let me know what you think.

**Comment by dsherret** [comment]
Thanks for the contributions @Pineapples! I just took a brief look and it looks good, but I have to go to work now. I'll merge this tonight after work.

By the way, I've updated the dev branch. Sorry about that, I just forgot to push it. Thanks for following the contributing instructions so well though :)

**Comment by dsherret** [comment]
This is released in v1.1.0. Thanks again, @Pineapples!
