### ISSUE TITLE
feature request: Expose typeExpression for JSDocTypeTag and JSDocReturnTag

### ISSUE THREAD

**Issue by Pineapples** [dsherret/ts-morph#535]
Sorry to bother you again with another feature request, but I would like to have the typeExpression property for JSDocTypeTag and JSDocReturnTag exposed.

I'll submit a pull request soon.

**Comment by dsherret** [comment]
For sure! I'll take a look at it after work. The jsdoc area hasn't been fully wrapped so I know it's missing stuff... sorry about that, but thanks for adding those methods. I appreciate it!

Maybe I will spend a bit of time this weekend wrapping more stuff in there.

Btw, take note that as a temporary workaround you can always fall back to the typescript compiler api node from any node by inspecting the `.compilerNode` property.
