### ISSUE TITLE
d.getArguments()[0].compilerNode.getText() return stings with comma 

### ISSUE THREAD

**Issue by yantrab** [dsherret/ts-morph#539]
Thank for the great jobs!

I glad if you take a look on my using your lib to compile [nest controller to client api](https://github.com/yantrab/nest-angular/blob/master/generator/index.ts).

to get the name of the method i did:

`d.getArguments()[0].compilerNode.getText()`
the result is like " 'getHello' ".

**Comment by dsherret** [comment]
Hey @yantrab, do you mean it returns the string with quotes? That node is probably a string literal. You can do the following:

```ts
import { StringLiteral } from "ts-morph";

// ...etc...

console.log((d.getArguments()[0] as StringLiteral).getLiteralValue());
```

Also you can check if the node is a string literal by using a type guard:

```ts
import { TypeGuards } from "ts-morph";

const arg = d.getArguments()[0];
if (TypeGuards.isStringLiteral(arg))
    console.log(arg.getLiteralValue());
```
