### ISSUE TITLE
A problem for export default  Variable

### ISSUE THREAD

**Issue by vibodev** [dsherret/ts-morph#552]
demo.ts
```ts
let isArray =  Array.isArray

export default isArray
```

test.js
```js
const project = new Project({})
project.addExistingSourceFiles(['.**/*.ts'])
let sourceFile = project.getSourceFileOrThrow(path.relative('.','demo.ts'))
let declarations = sourceFile.getExportedDeclarations()

for (const declaration of declarations) {
  console.log( declaration.isDefaultExport())
}
```
**Error:**
TypeError: declaration.isDefaultExport is not a function

HELP!~

**Comment by dsherret** [comment]
Right now `isDefaultExport()` only exists on `VariableStatement`. I've opened #553.

Current workaround is:

```ts
// untested...
import { Node, TypeGuards } from "ts-morph";

// ...etc...

for (const declaration of declarations) {
    let exportableNode = getExportableNode(declaration);
    if (exportableNode != null)
        console.log( declaration.isDefaultExport())
}

function getExportableNode(node: Node) {
    if (TypeGuards.isExportableNode(node))
        return node;
    if (TypeGuards.isVariableDeclaration(node))
        return node.getParent();
    return undefined;
}
```

Opened #554 as well.

**Comment by vibodev** [comment]
Thanks!!!

**Comment by vibodev** [comment]
> Right now `isDefaultExport()` only exists on `VariableStatement`. I've opened #553.
> 
> Current workaround is:
> 
> ```ts
> // untested...
> import { Node, TypeGuards } from "ts-morph";
> 
> // ...etc...
> 
> for (const declaration of declarations) {
>     let exportableNode = getExportableNode(declaration);
>     if (exportableNode != null)
>         console.log(declaration.isDefaultExport());
> }
> 
> function getExportableNode(node: Node) {
>     if (TypeGuards.isExportableNode(node))
>         return node;
>     if (TypeGuards.isVariableDeclaration(node))
>         return node.getParent();
>     return undefined;
> }
> ```
> 
> Opened #554 as well.



> Right now `isDefaultExport()` only exists on `VariableStatement`. I've opened #553.
> 
> Current workaround is:
> 
> ```ts
> // untested...
> import { Node, TypeGuards } from "ts-morph";
> 
> // ...etc...
> 
> for (const declaration of declarations) {
>     let exportableNode = getExportableNode(declaration);
>     if (exportableNode != null)
>         console.log(declaration.isDefaultExport());
> }
> 
> function getExportableNode(node: Node) {
>     if (TypeGuards.isExportableNode(node))
>         return node;
>     if (TypeGuards.isVariableDeclaration(node))
>         return node.getParent();
>     return undefined;
> }
> ```
> 
> Opened #554 as well.

Thanks!!
