### ISSUE TITLE
Emit diagnostics do not include semantic diagnostics

### ISSUE THREAD

**Issue by yantrab** [dsherret/ts-morph#555]
```
import {Project} from 'ts-morph'
const project = new Project();
project.createSourceFile("MyFile.ts", "const num:ddd = 1;");
const emitResult = project.emitToMemory();
for (const diagnostic of emitResult.getDiagnostics())
    console.log(diagnostic.getMessageText());
```
why diagnostic is empty in this case?

**Comment by dsherret** [comment]
What you probably want to do is check the pre-emit diagnostics:

```ts
const diagnostics = project.getPreEmitDiagnostics();
```

With that configuration it won't return the semantic diagnostics.

**Sidenote**

Right now the jsdoc on `getDiagnostics()` for `EmitResult` says:

> Contains declaration emit diagnostics.

However, I just looked at the compiler api source and it seems that an exception to this is that it will return more diagnostics if the `noEmitOnError` compiler option is true (see [here](https://github.com/Microsoft/TypeScript/blob/4db4c5892423562c9ea3938b9b2366de35dd0c5e/src/compiler/program.ts#L1526)). I've opened #556 for that, but it's not really related to this.
