### ISSUE TITLE
how can i check if prop type is enum? 

### ISSUE THREAD

**Issue by yantrab** [dsherret/ts-morph#560]
class{
f:someEnum
}

**Comment by dsherret** [comment]
`property.getType().isEnum()` should work.

**Comment by yantrab** [comment]
But is not work for me:

```
enum Color { Red, Green, Blue }
export class LoginRequest {
    color: Color;
}

prop.getType().getText() // Color
 prop.getType().isEnum() // false
```

**Comment by dsherret** [comment]
@yantrab thanks that was definitely a bug! This should be fixed in 1.3.0 (just released). Let me know if not.

**Comment by yantrab** [comment]
@dsherret    Thanks, it works. but how can i check is if array of enum?

**Comment by dsherret** [comment]
I'm not at my computer, but there should be an `isArrayType` and `getArrayType` method. Then check if that's an enum.
