### ISSUE TITLE
Using ts-morph in custom tslint rule fails to report in Visual Studio Code

### ISSUE THREAD

**Issue by vidal7** [dsherret/ts-morph#562]
I am using ts-morph in a custom tslint rule. The lint error is reporting fine when using tslint cli command but is not reporting in vscode. I don't know if it's a ts-morph, typescript-tslint-plugin, ms-vscode.vscode-typescript-tslint-plugin or vscode issue.

Version: 1.3.0

Rule is failing to report in vscode when using createWrappedNode or new Project(). To reproduce, simply remove comments on commented out lines. It doesn't matter which line you remove comments.

```ts
import Project, { CompilerNodeToWrappedType, createWrappedNode } from 'ts-morph';
import * as Lint from 'tslint';
import * as ts from 'typescript';

export class Rule extends Lint.Rules.AbstractRule {
    public static FAILURE_STRING: string = `Custom rule failed`;

    public apply(sourceFile: ts.SourceFile): Lint.RuleFailure[] {
        return this.applyWithFunction(sourceFile, walk);
    }
}

function walk(ctx: Lint.WalkContext<void>): void {
    ts.forEachChild(ctx.sourceFile, recur);

    function recur(node: ts.Node): void {
        if (isClass(node)) {
            // const wrappedNode: CompilerNodeToWrappedType<ts.ClassDeclaration> = createWrappedNode(node);
            // const project: Project = new Project();

            ctx.addFailureAtNode(node, Rule.FAILURE_STRING);
        }

        ts.forEachChild(node, recur);
    }
}

function isClass(node: ts.Node): node is ts.ClassDeclaration {
    return node.kind === ts.SyntaxKind.ClassDeclaration;
}

```

Removing comments on line should report custom tslint error in vscode.

**Comment by dsherret** [comment]
@vidal7 This seems like a problem elsewhere. Does the rule run at all? Does the file get executed? What about when you have a try, catch around the `createWrappedNode` statement? Does an exception occur then?

**Comment by vidal7** [comment]
Hi @dsherret, I gave another try. I found something interesting. In the tslint cli command, the rule is running perfectly with or without the `createWrappedNode` statement. But, in the context of vs code, the rule is not run at all so the try, catch strategy is useless. Here's is what is interresting.

Custom tslint rule are written in typescript and must be compiled down to javascript to be executed. So, I   modified the compiled down javascript file and requiring ts-morph seems to be the culprit.

Thus, adding `var ts_morph_1 = require("ts-morph");` in the javascript file seems to stop the rule to be executed. Does required is messing with something global that typescript-tslint-plugin, ms-vscode.vscode-typescript-tslint-plugin or vscode doesn't like? For now, I don't know. Maybe, this will give you clues about this issue.

**Comment by dsherret** [comment]
That's strange. Does it throw in the require statement? (What happens when you surround that require in a try/catch?)

ts-morph is released as ES5. I have a feeling that vscode can't find the package for some reason.

**Comment by vidal7** [comment]
Hi @dsherret, I dug down again the problem and the require statement is working perfectly and no throw occurs. I even commented out all lines in node_modules/ts-morph/dist/main.js and everything is working in vs code. So I tried to remove comments on random lines ans here he's the file that works for me.

```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var tslib_1 = require("tslib");
/// <reference path="typings/index.d.ts" />
tslib_1.__exportStar(require("./codeBlockWriter"), exports);
// tslib_1.__exportStar(require("./compiler"), exports);
tslib_1.__exportStar(require("./errors/classes"), exports);
// var fileSystem_1 = require("./fileSystem");
// exports.Directory = fileSystem_1.Directory;
// exports.DirectoryEmitResult = fileSystem_1.DirectoryEmitResult;
// tslib_1.__exportStar(require("./options"), exports);
// var Project_1 = require("./Project");
// exports.Project = Project_1.Project;
// var Project_2 = require("./Project");
// exports.default = Project_2.Project;
// var createWrappedNode_1 = require("./utils/compiler/createWrappedNode");
// exports.createWrappedNode = createWrappedNode_1.createWrappedNode;
var printNode_1 = require("./utils/compiler/printNode");
exports.printNode = printNode_1.printNode;
// var getCompilerOptionsFromTsConfig_1 = require("./utils/tsconfig/getCompilerOptionsFromTsConfig");
// exports.getCompilerOptionsFromTsConfig = getCompilerOptionsFromTsConfig_1.getCompilerOptionsFromTsConfig;
var TypeGuards_1 = require("./utils/TypeGuards");
exports.TypeGuards = TypeGuards_1.TypeGuards;
// var WriterFunctions_1 = require("./structurePrinters/WriterFunctions");
// exports.WriterFunctions = WriterFunctions_1.WriterFunctions;
tslib_1.__exportStar(require("./typescript/public"), exports);
```

Removing a single commented out line is falling my linting rule to report to VS Code

**Comment by dsherret** [comment]
@vidal7 that is very strange! Maybe it's a dependency like `fs-extra` or something. Ok, I'll take a look into this soon (do you have a repo I could reproduce this on quickly? Otherwise, I'll try to come up with my own reproduction). Thanks!

**Comment by vidal7** [comment]
Thank you @dsherret, I don't have a repo yet but I can set up one for you in the next following days. This will not be hard. Stay tuned.

**Comment by dsherret** [comment]
Closing this for now. Please reopen if you find out anything.
