### ISSUE TITLE
Error: Not implemented feature for syntax kind 'ArrayBindingPattern'.

### ISSUE THREAD

**Issue by WanderWang** [dsherret/ts-morph#563]
**Describe the bug**

I want to generate API docs from my .d.ts file . So I use ts-morph to convert .d.ts jsdocs to JSON but it emit a error

Version: 1.3.0

**To Reproduce**

**Expected behavior**

No Error

**Comment by WanderWang** [comment]
[mydts.zip](https://github.com/dsherret/ts-morph/files/2944601/mydts.zip)

here is the .d.ts file

**Comment by dsherret** [comment]
@WanderWang providing the stack trace would be useful.

**Comment by dsherret** [comment]
Nevermind, I remember what this is now. I'll implement this soon.

**Comment by dsherret** [comment]
This will possibly throw a more descriptive error message in 2.0.0. Most likely you will need to use `.getNameNode()` instead, but the return type for that will be fixed on `ParameterDeclaration` in 2.0.0.

**Comment by WanderWang** [comment]
Update : 

It works in 1.3.2 , thank u
