### ISSUE TITLE
Structures - Add new `statements` array to bodied/bodyable structures

### ISSUE THREAD

**Issue by dsherret** [dsherret/ts-morph#569]
There should be more alignment between the structures and the actual AST to support more scenarios. Right now the structures are restrictive because their design is not flexible.

This change would deprecate `bodyText` and any properties like `classes`, `namespaces`, etc. So instead of this:

```ts
const sourceFileStructure: SourceFileStructure = {
    classes: [{
        name: "MyClass"
    }],
    enums: [{
        name: "MyEnum",
        members: [{ name: "value" }]
    }]
};
```

It would look like this:

```ts
const sourceFileStructure: SourceFileStructure = {
    statements: [{
        kind: StructureKind.Class, // use this? Or a string: "class"?
        name: "MyClass"
    }, {
        kind: StructureKind.Enum,
        name: "MyEnum",
        members: [{ name: "value" }]
    }]
};
```

An additional huge advantage here is that `sourceFile.getStructure()` could return an array of statements and methods like `addStatements` could accept structures.

Note: `kind` would probably be a required property and then not required for methods like `.addClass(...)`.

Relies on #568.

**Comment by dsherret** [comment]
Implemented in 5f4943b.

**Comment by RWOverdijk** [comment]
@dsherret Hey! Finally made the step to update to the new module, but I'm hitting a wall here. bodyText is not longer allowed in `.addMethod()`. How can I set the body for a method now?

**Comment by dsherret** [comment]
@RWOverdijk I have `statements` accept a string in 3.0 (https://github.com/dsherret/ts-morph/blob/c9a1b84fb44d8c6fbc98669d61cec4a21225723f/lib/ts-morph.d.ts#L10970)

I really need to get that released soon... it's taken longer than I expected because I keep finding stuff to fix and I got distracted with another project. I'll try for this weekend.

**Comment by RWOverdijk** [comment]
@dsherret Hehe I know the struggle. But array is fine. Flexibility is one thing, it being functional another. I'd say forcing an array is _fine_ and I'm more than happy to use it that way. :)
