### ISSUE TITLE
Extending the library

### ISSUE THREAD

**Issue by cancerberoSgx** [dsherret/ts-morph#580]
This library is awesome, but unfortunately, when I tried to extending it to add extra APIs to current types, it was very hard or impossible. 

Imagine I want to add some extra API on top of ts-morph classes like Node, SourceFile, Project, without having to wrap objects, just plain old class/interface inheritance. 

Currently I'm encountering myself developing lots of small tools around it that certainly are useful for my needs but unlikely won't be merged or on the library. Probably too specialized, and also we dont want the library to get heavy. Also I'm noticing it's getting heavy (from the POV of the compiler, not runtime)

I tried to extend the global namespace, but since the library don't declare modules or namespaces is not possible. This how it's done in jest, the types need to be declared inside the library namespace and then you have a SomeClass.extend() method to add your implementation (example: https://github.com/cancerberoSgx/tsd-check-runtime/blob/84ed4b1b1729e9e8d9e4891afa528a28d8f3dca7/src/jestMatcher.ts)

```
declare global {
  namespace jest {
    interface Matchers<R> {
      toTrigger(options: void): R
    }
  }
}
SomeClass.extend({myMethods...})
```

It would be possible to contribute to ts-morph with such an extensibility API ? Do you prefer others / or see is not viable because of typings ? 

I tried more ordinary ways, like :
 * class / interface extends (some core classes like SourceFile cannot be extended cause have private constructor)
 * typescript mixin - gave me a lot of work and could not make it wok .. also very dirty to manipulate the prototype...

Do you envision some API for this or do you want to protect/private the library from this kind of use?

IMO, having a way for  custom "plugins" will encourage people to implement their own extensions outside ts-morph development workflow and enrich the echo system...  Consider that coding against an AST implies lots of repetitive code and in different scenarios. Having ways of authoring the semantics for custom needs would be awesome!

Things that IMO could be done as plugins progressively and by interested people,  could be:

 * structures
 * move
 * rename
 * refactors
 * query (like in tsquery)
 * high level type inference
 
Keep it up!
Thanks!

**Comment by dsherret** [comment]
Hmmm I don't believe the library is stable enough to offer that at the moment. I've found a wrapper pattern works well for me and helps simplify whatever I'm analyzing by creating simplified abstractions of the code being analyzed/manipulated. I don't have much time at the moment to explain it exactly, but I've been planning to write it down sometime in the future.

**Comment by cancerberoSgx** [comment]
I think we already discuss some of this in the past. And first let me say the discipline I see in this source code from several point of views is surprising for me being this mostly one-person project. (I'm talking from my point of view- that's is a sloppy developer that often do it for fun). 

Ans pardon the audacity, but if the motive is not willing / interested / have enough time to support issues / maintain an extension API which will have lots, there could be an intermediary solution. We could subclass  a couple of important classes internally (Project, SourceFile, Node) that allow normal class "extends" and explicitly document in these that are unstable / not supported / not safe.Then creating minimal interfaces with reduced methods to transverse the AST and basic project tools would be enough

I think something like that can be accomplished with minimal changes to current types and, it would imply no more than 5 new types  all encapsulated in a namespace so users realize they are accessing an "experimental"/unstable part of the library. Also , users will have the opportunity to "get out of these "extensibilty" types and access the "internal classes" at their own risk, but in other to do that they are forced to cast
 
If there are other "more stylistic" motives, then I stop here, will just say that IMO the project is loosing an opportunity. 

I'm not convinced wrapping would be a good approach for extending, maybe not in my world, I'm thinking extending without compiling, even extending at runtime, in a browser. 

I understand you have mechanized the process and that's awesome and elegant. But I don't think that's the correct pattern for extensions. as user I don't expect to clone / compile the core in order  in ioder to create a plugin for a simple use case

Don't take me wrong, I find very interesting how you distributed all the aspects across the types. The code I see is easy to read, and very descriptive, probably easy  to maintain and keep up TS. . 

I just want to know if there is a minimal chance to open a couple of well signaled doors so users can just import and extend a class or dynamically add new methods without having to, basically clone and recompile / redistribute the whole thing. If so I would be glad to make a minimal prototype, I would hate to clone the project just for this. 

thanks, and again, this comes from somebody that likes what he sees and is just pushing for something he thinks could improve the project a lot . Thanks for reading, we can close this OT issue... sorry for being a pain with this...

**Comment by dsherret** [comment]
Sorry, won't be doing this. I recommend writing reusable functions and then using them in your project:

```ts
export function doRefactor(sourceFile: SourceFile) {
    // ...etc...
}
```
