### ISSUE TITLE
feature: Node selectDescendants() and buildSelector() feature

### ISSUE THREAD

**Issue by cancerberoSgx** [dsherret/ts-morph#585]
I have a descent implementation for building a node's path from an ancestor and selecting a descendant using the selector. I wonder if you would accept a PR to include this functionality. 

Motivation: 

 * re-select a node quickly when (it or its ancestors) get forgotten. 
 * Have a simple selector query language supporting index, syntax kinds, children , descendants and siblings. Probably no more than just that. 
 * be able to verify that ancestors didn't changed (at some configurable degree) although they still are not forgotten

Implementation: 

 * optionally collects / validates extra information besides indexes in the path like syntax kind, sibling, children count. The idea is be able to validate that the AST didn't change too much while selecting. 
 * supports both ways of obtaining children index (getChildren and forEachChild)
 * the path object is very lightweight and "stringifiable". 

Or do you think this is out of topic and users should use tsquery library for this ?  Thanks

**Comment by dsherret** [comment]
Hey @cancerberoSgx is this another form of #351? I don't want to add/support any querying in this library at the moment. Someone can build that on top of this library if they'd like (similar to how tsquery is built on top of the typescript compiler api).

**Comment by cancerberoSgx** [comment]
Yes is more or less the same, sorry, The only difference is that I have it implemented now. it's been a while since I work with this library and I forgot about that issue. thanks.
