### ISSUE TITLE
Add Node.getEndLinePos()

### ISSUE THREAD

**Issue by cancerberoSgx** [dsherret/ts-morph#586]
Node has `getStartLinePos(includeJsDocComments?: boolean)`, `getStartLineNumber(includeJsDocComments?: boolean)` and `getEndLineNumber()` methods, but no `getEndLinePos()` . Can I add it ? Or is there an obvious  way of getting it that I'm not seeing? (currently using `ts.getLineAndCharacterOfPosition()`)

Thanks

**Comment by dsherret** [comment]
No, doesn't exist at the moment. What's the use case for this?

**Comment by cancerberoSgx** [comment]
I'm selecting the node's text in monaco-editor. I need lineNum and character both on start and end, that's the only one missing :(

**Comment by dsherret** [comment]
I recommend using `sourceFile.getLineNumberAtPos(node.getEnd())` and `sourceFile.getLengthFromLineStartAtPos(node.getEnd())` for now.

We should consider possibly a `sourceFile.getLineAndColumnAtPos(pos: number): { line: number; column: number; }` maybe and deprecate `SourceFile#getLineNumberAtPos(pos: number)`.

The problem I see with `getEndLinePos` is that it's ambiguous as to whether a method with this name would return the start position of the line or the end. `getStartLinePos` is useful for quickly telling if two nodes are on the same line (doesn't require getting the line number, which is slower).

**Comment by dsherret** [comment]
@cancerberoSgx if you'd like you can submit a PR for the `getLineAndColumnAtPos(pos: number): { line: number; column: number; }` method (and deprecate `getLineNumberAtPos`). Would that cover your use case?

**Comment by cancerberoSgx** [comment]
yes, will do, Do you want me to also  take care of the "deprecation" part? or should I leave that part to you? Thanks

**Comment by dsherret** [comment]
If you'd like. Up to you! This can go into 2.0 so it's ok to be a breaking change.

**Comment by dsherret** [comment]
Thanks! 😄

**Comment by cancerberoSgx** [comment]
OK, I just want to make sure I'm correct assuming It's OK that I just remove the method, right ? I'm asking because some people first tag the method with @deprecated but leave it a couple of releases before actually breaking. I'm 99% sure this is not the case, but would like to verify, thanks!

**Comment by dsherret** [comment]
I usually just add `@deprecated` when I don't want to cause a major release, but I'm doing a major release anyway so we might as well remove it at this time.

**Comment by dsherret** [comment]
Closing in favour of #587.
