### ISSUE TITLE
Remove unused and other TS built-in refactors and code fixes

### ISSUE THREAD

**Issue by cancerberoSgx** [dsherret/ts-morph#589]
Hi, I have working implementations of several TypeScript built-in code fixes and refactors that I could integrate in this library. Particularly remove-unused which removes all unused variables, imports, parameters, type parameters, etc in a source file could be nice to have. 

The implementation is quite simple, I just use LanguageService getSuggestionDiagnostics and getCodeFixesAtPosition and then SourceFile.applyTextChanges to apply the changes the Language Service provides, so indeed I'm not implementing any kind of logic besides passing the correct code fixes code to LanguageService.getCodeFixesAtPosition for each case. 

The code fixes will make all source file nodes to be forgotten, just like it currently happens with organizeImports()

Do you think I can create a PR for "removeUnused" since is the most general and useful, and then discuss if this is viable to introduce in the library ? And then from there we can discuss other refactors (not so general or useful) ?

Some refactors I have working and tested right know are

 * removeUnused
 * inferTypesFromUsage (will add types too all nodes without type declaration inferring from usage)
 * convertNamespaceImportToNamedImports / convertNamedImportsToNamespaceImport
 * remove/add BracesToArrowFunction
 * convert to Es6 module

Note: I have also other refactors but made by myself (not part of  language service built-ins) like extractInterface that given a class will create an interface with all class members and make the class implement it. I would also like what's you oopinion about including this kind of things in the library, or if it's too specialized / OOT for the library. 

And BTW, If I had the means, I would add all of this as a library extension and don't bother you here asking... ;)

**Comment by dsherret** [comment]
Hey @cancerberoSgx, yeah a lot of these would be useful, but if we are to add them could you open one issue per item, use the feature issue template, outline the changes to the public api that would happen as well as how it would work, and then we can discuss them individually? For some of them, it would be better if we implement it ourselves rather than using the language service so that the nodes won't be forgotten.

Also, [`extractInterface`](https://dsherret.github.io/ts-morph/details/classes#extracting-an-interface) already exists :)

**Comment by dsherret** [comment]
I'm going to close this issue as it's very broad. Please open individual ones as mentioned in the last comment.

**Comment by cancerberoSgx** [comment]
> Also, [`extractInterface`](https://dsherret.github.io/ts-morph/details/classes#extracting-an-interface) already exists :) Edit: Oh sorry, I misread your statement, but yeah just open one issue per request. Thanks

Ohhh !! didn't knew that. Perhaps could be nice to have a section in the docs that collects any "refactor-like" method such as orgenizeImports, formatText, extractInterface, rename(), move(), remove(), etc ?

BTW I opened https://github.com/dsherret/ts-morph/issues/590 so we can start discussing it. If you feel is viable I could start prototyping something, from scratch so nodes are not forgotten so I kind of have an idea if there is big difficulty in implement this from scratch
