### ISSUE TITLE
Remove Unused

### ISSUE THREAD

**Issue by cancerberoSgx** [dsherret/ts-morph#590]
Similar to methods `organizeImports()` , `formatText()`, `fixMissingImports()` I would like to have a method `removeUnused()` that removes any variable, parameter, named import, type parameter, method, etc. that is not used. 

```ts
    /**
     *  Removes used declarations like variables, parameters, members, etc. from this node descendants.
     *
     * @param formatSettings - Format code settings.
     * @param userPreferences - User preferences for refactoring.
     */
    removeUnused(formatSettings: FormatCodeSettings = {}, userPreferences: UserPreferences = {}) {}
```

**Alternatives**
The method could accept some options to control which kind of nodes should be removed or not. Also if we decide to put the method in SourceFile instead of Node, it could accept a targetnode option:

```ts
type RemoveUnusedExclude = 'variable'|'parameter'|'typeParameter'|'import'|'function'|'class'|'type'|'method'|'property'|'constructor'|'etc'
interface RemoveUnusedOptions{
    exclude?: RemoveUnusedExclude[]
    targetNode?: Node
}
removeUnused(options?: RemoveUnusedOptions):void
```

**Doubts** 

 * Similarly to formatText() this applies to any node, this method could be declared in `Node` although users will usually call it in `SourceFile`. So I'm not sure where would be the best location..

 * Should we use TS built in code fixes that already implements this? or should we implement it from scratch so Nodes are not forgotten ?

In some cases it could be tricky to define if something is used or not, like type parameters, exports, etc, and the implementation must be 100% safe, but I could try implementing something like that and see...

**Comment by dsherret** [comment]
Would this also include removing functions/classes/interfaces/etc? I think though that for performance reasons we should do it at a project level with the ability to optionally provide a source file or sourcefiles to limit the refactor to. That would allow us to do all the analysis first across the entire project for what to remove and then afterwards do the manipulation. If it's analysis, manipulation, analysis, manipulation, etc. it will be very slow because the compiler will need to build up the symbols each time. (We should also put this in a new `src/compiler/tools/refactors` folder)

Probably it should exist on `LanguageService` and `SourceFile` since that's where the other code fixes are. What about `LanguageService#removeUnusedIdentifiersAndDeclarations(containers?: Node | Node[]): this;`? (it would search all the descendants of the node(s) passed in or all the source files in the project).

**Comment by dsherret** [comment]
Or actually maybe just`removeUnusedDeclarations`.

**Comment by cancerberoSgx** [comment]
> Would this also include removing functions/classes/interfaces/etc?

The current  solution I have, using TypeScript code fixes, removes any kind of unused declaration (if it's not exported and not locally referenced then it's removed)

> I think though that for performance reasons we should do it at a project level with the ability to optionally provide a source file or sourcefiles to limit the refactor to. That would allow us to do all the analysis first across the entire project for what to remove and then afterwards do the manipulation

+1 - I think being able to exclude files (using glob pattern or similar) is mandatory since there are valid cases where you don't want to remove unused stuff (tests)

**Comment by cancerberoSgx** [comment]
> What about `LanguageService#removeUnusedDeclarations(containers?: Node | Node[]): this;`? (it would search all the descendants of the node(s) passed in or all the source files in the project).

I think it's better to have `LanguageService#removeUnusedDeclarations(filePathOrSourceFile: SourceFile | string): this;` since in general that's the signature of LanguageService methods. Then we can have, as you suggested: 

`SourceFile#removeUnusedDeclarations(containers?: Node | Node[]):this`
`Project#removeUnusedDeclarations(containers?: Node | Node[]):this`

Maybe in the case of Project `Project#removeUnusedDeclarations(excludeFiles?: SourceFile | string):this` is better.

The problem I'm currently having implementing `LanguageService#removeUnusedDeclarations(containers?: Node | Node[]): this;` is that, in case containers is undefined, I'm not sure how to obtain all project's source files (in general I don't know how to get the project from LanguageService and I doubt that is even possible . 

If you want to go this way, then I would need some help/tips with this. I can implement it copy/paste from `Project#getSourceFiles` but I would prefer you give me some hints first, or if it's possible to access a `Project`  from `LanguageService` method scope. Thanks

**Comment by dsherret** [comment]
After thinking this through, I think what you did in #595 is sufficient. This is normally a refactor that people do at the end and so keeping track of the nodes is not very necessary.

By the way, here's an example of calling this until there's no more changes:

```ts
let lastWidth: number = 0;
while (lastWidth !== sourceFile.getFullWidth()) {
    lastWidth = sourceFile.getFullWidth();
    sourceFile.fixUnusedIdentifiers();
}
```
