### ISSUE TITLE
How to construct object literals

### ISSUE THREAD

**Issue by ChuckJonas** [dsherret/ts-morph#622]
So I know that I can create a property like this:

classDeclaration.addProperty({
            name: 'foo',
            scope: Scope.Private,
            type: 'number',
            initializer: '4'         
});

but how would on build a more complex object:

For example, how would I construct `bar` in the class below?

``` typescript
class Foo {
    public bar = {
         x: 123,
         y: 'abc',
         z: { one: '1' }
    }
}
```

I know I could just string build it and set `initializer`, but I'm wondering if there is a better way?

**Comment by dsherret** [comment]
This is similar to [#320](https://github.com/dsherret/ts-morph/issues/320#issuecomment-429574081). Basically use the `WriterFunctions` (kind of experimental, but they'll probably stick around):

```ts
import { WriterFunctions } from "ts-morph";

classDeclaration.addProperty({
    name: 'foo',
    scope: Scope.Private,
    type: 'number',
    initializer: WriterFunctions.object({
        x: 123,
        y: `'abc'`,
        z: WriterFunctions.object({
            one: `'1'`
        })
    })
});
```

You can also create your own writer functions in case you want more control. You'd just have to write something similar to what's done in that `WriterFunctions` utility class methods. See the definition [here](https://github.com/dsherret/ts-morph/blob/0976e63495ae02a75a7754d9928639353248ba7b/src/structurePrinters/WriterFunctions.ts#L26). Basically, it does something like this internally:

```ts
classDeclaration.addProperty({
    name: 'foo',
    scope: Scope.Private,
    type: 'number',
    initializer: writer => {
        writer.write('{');
        writer.indentBlock(() => {
            writer.writeLine(`x: '123',`);
            writer.writeLine(`y: 'abc'`);
        });
        writer.write('}');
    }
```

**Comment by dsherret** [comment]
Updated my response to use `.quote("text")`. That's a bit better because then it uses the quote character specified in the [manipulation settings](https://dsherret.github.io/ts-morph/manipulation/settings).

**Comment by ChuckJonas** [comment]
beautiful! thanks!

**Comment by ChuckJonas** [comment]
@dsherret sorry to keep bugging you, but how would I add the `as const` keyword when using `WriterFunctions.object(`

``` ts
public bar = {
         x: 123,
         y: 'abc',
         z: { one: '1' }
    } as const 
```

**Comment by dsherret** [comment]
That's no problem!

Hmmm never thought about that. You could do this:

```ts
initializer: writer => {
    WriterFunctions.object({
        x: 123,
        y: writer => writer.quote('abc'),
        z: WriterFunctions.object({
            one: writer => writer.quote('1')
        })
    })(writer);
    writer.write(" as const");
}
```

But it would perhaps be better if I added an `WriterFunctions.assertion` (or `assert`?) function or if you implemented one yourself. So something like this:

```ts
initializer: WriterFunctions.assertion(WriterFunctions.object({
    x: 123,
    y: writer => writer.quote('abc'),
    z: WriterFunctions.object({
        one: writer => writer.quote('1')
    })
}), "const");
```

Opened #623.

**Comment by ChuckJonas** [comment]
nvm, figured it out

```
writer => {
                WriterFunctions.object(myObj)(writer);
                writer.write(' as const');
};
```

**Comment by quadband** [comment]
Just in case anyone stumbles across this in the future, WriterFunctions has been deprecated. Use Writers, instead. :)
