### ISSUE TITLE
Custom compiler host

### ISSUE THREAD

**Issue by DanTsk** [dsherret/ts-morph#626]
Can I pass my own compiler host implementation for ts.Program ? 
For example - custom module resolution like in this [example](https://github.com/Microsoft/TypeScript/wiki/Using-the-Compiler-API#customizing-module-resolution)

**Comment by dsherret** [comment]
Hey @DanTsk. No, most of the functionality that a custom compiler host would offer is already configurable in other ways (ex. by providing a custom file system host).

What you're suggesting by custom module resolution would be a good idea though! I can add a way to configure that. Opened #627.

Is there anything else you'd like that a custom compiler host would provide?

**Comment by DanTsk** [comment]
Hi @dsherret . I am currently working on the TypeScript runtime environment, with custom module resolution for node packages (without node_modules folders in each project folder) and Go-like imports: file URLs, GitHub project and etc.  And I am using **ts-morph** for types analysis and project compilation, so I really need those features to continue my work.

It would be great to have all next overrides configurable:
```
resolveModuleNames?(moduleNames: string[], containingFile: string, reusedNames?: string[], redirectedReference?: ResolvedProjectReference): (ResolvedModule | undefined)[];
getResolvedModuleWithFailedLookupLocationsFromCache?(modulename: string, containingFile: string): ResolvedModuleWithFailedLookupLocations | undefined;
resolveTypeReferenceDirectives?(typeDirectiveNames: string[], containingFile: string, redirectedReference?: ResolvedProjectReference): (ResolvedTypeReferenceDirective | undefined)[];
```

Thanks

**Comment by DanTsk** [comment]
But also, some additional information is needed during the building overrides. For example, for successful `resolveTypeReferenceDirectives` implementation, `ts.LanguageServiceHost` is required.

**Comment by dsherret** [comment]
Yeah, I think those being on `ProjectOptions` would work and then they could be passed down to the compiler host and language service host. A PR would be great if you're up for it! Otherwise, I can take a look at this sometime soon. Thanks!

**Comment by DanTsk** [comment]
I've opened pull request - [628](https://github.com/dsherret/ts-morph/pull/628)

**Comment by dsherret** [comment]
Closing this. As discussed a custom compiler host isn't going to be allowed, but specific options for custom module resolution and resolving type reference directives will.
