### ISSUE TITLE
ReturnStatementStructure?

### ISSUE THREAD

**Issue by marikaner** [dsherret/ts-morph#634]
This is more a question than an actual feature request, but I have been looking for this at multiple occasions already.

I am currently improving the readability and performance of our project, that uses ts-morph and I am wondering what is the best way to achieve the following:

```ts
someFunction() {
  return {
    a: 1,
    b: 2
  };
}
```
I am creating a function that returns an object literal. Currently I am creating a `FunctionDeclarationStructure` doing the following:

```ts
return {
  ...
  statements: writer => {
    const wfn = WriterFunctions.object({
      a: 1,
      b: 2
    });
    writer.write('return').space();
    wfn(writer);
    writer.write(';');
  }
}
```

But I am wondering whether this can be improved by using some other structure or statment? Of course this is just a minimal example the real deal is a lot more complex.

**Comment by dsherret** [comment]
Hey @marikaner, no, right now for most statements and expressions there's no helper functions or structures for doing this. I'm thinking to continue with the `WriterFunctions` pattern, though I wish that had a better/shorter name (I can't think of one... any ideas?).

So similar to [`WriterFunctions.assertion`](https://github.com/dsherret/ts-morph/blob/2145e89b33290516febec6dc3c67853a36df41cf/src/structurePrinters/WriterFunctions.ts#L80), which will be in v3.0, a similar `WriterFunctions.returnStatement` could be created:

```ts
// this could be made an array of these writer functions or strings (one per statement)
statements: WriterFunctions.returnStatement(
    WriterFunctions.object({
        a: 1,
        b: 2
    })
)
```

Does that sound good? In a way, this is kind of like AST factory functions, but exclusively for printing.

If you want a temporary workaround before this is implemented, take a look at that [WriterFunctions](https://github.com/dsherret/ts-morph/blob/2145e89b33290516febec6dc3c67853a36df41cf/src/structurePrinters/WriterFunctions.ts) class and create something similar in your own project.

**Comment by marikaner** [comment]
Yes, that sounds legit. I just had a look at the implementation and it looks like this should be very easy to do. If I have some time left I might just make a PR, if you're interested.
Also, I don't have a better name, but `Writers` might be shorter and good enough? (Why is this a class at all...?)

**Comment by dsherret** [comment]
@marikaner I like `Writers`! Thanks! I'll probably change (or at least alias) it to that next release.

It could just be an object with method declarations, but I'm just too used to static classes because of my mainly c# background :)
