### ISSUE TITLE
Performance issue with getExportedDeclarations()

### ISSUE THREAD

**Issue by nchanged** [dsherret/ts-morph#644]
Found another show stopper.
Here is a full snippet:

```ts
import { Project } from 'ts-morph';

const project = new Project();
const testFile = project.createSourceFile(
  'src/MyClass.ts',
  `
  export { Button } from './Button';
  export { Header } from './Header';
  export { default as Layout } from './Layout/Layout';
  export function bar(){}
  export function oi(){}
  export function hello(){}
  export function world(){}
`,
);
const start = new Date().getTime();
testFile.getExportedDeclarations();
testFile.getExportAssignments();
testFile.getImportDeclarations();
console.log(`took: ${new Date().getTime() - start}`);
```

It will take approx 1 second to complete, however, commenting out `testFile.getExportedDeclarations();` makes it 1ms. There must be something wrong with it. I've been happily traversing imports and exports until I stumbled upon that.

Running on NodeJs `v11.13.0`
Similar issues #432

A workaround for now:

```ts
const decls = testFile.getDescendantsOfKind(ts.SyntaxKind.ExportKeyword);
decls.forEach(exportsKeyWord => {
  const parent = exportsKeyWord.getParent();
  if (parent) {
    switch (parent.getKind()) {
      case ts.SyntaxKind.FunctionDeclaration:
      case ts.SyntaxKind.ClassDeclaration:
      case ts.SyntaxKind.VariableDeclaration:
        console.log(parent.compilerNode['name'].getText());
        break;

      default:
        break;
    }
  }
});
```

**Comment by dsherret** [comment]
@nchanged see the jsdoc and return type of that method: https://github.com/dsherret/ts-morph/blob/9e4f07ddef7def316ed9601b3c78a1409c7aed01/lib/ts-morph.d.ts#L2714

The method you are looking for is `#getExportDeclarations()`

**Comment by dsherret** [comment]
@nchanged Sorry, I previously jumped the gun by thinking you wanted export declarations.

The `#getExportedDeclarations()` uses symbols so it will be slow because it requires binding. It's pretty useful because it will transitively finds exported declarations (ex. `export { SomeDeclaration } from "./otherFile";`).

I think `#getExportedDeclarations()` is probably what you want because it will be most correct, however, if you just want a solution that traverses the AST then you could do something like:

```ts
import { TypeGuards } from "ts-morph";

const exportedStatements = file.getStatements().filter(s => TypeGuards.isExportableNode(s) && s.isExported());
```

**Comment by nchanged** [comment]
@dsherret thanks as always ;-)
But I still don't get it. The project has only 1 source file, the file consists of literally 7 lines of code, why does it make it 1000x slower? for 0ms to 1100s that's a huge leap, I don't think that the compiler is even that slow. 

I am building a tree shaking algorithm, so an average project consist of ~1500 files (including node modules), now imagine if a 7 line file takes more than a second, what would happen with 1500 files. It would run out of memory. Typescript compiler won't

I think I will go for `testFile.getDescendantsOfKind(ts.SyntaxKind.ExportKeyword)` since I can capture multiple scenarios and handle them accordingly. References are hard for the tree shaking, I need to check all of them anyway using `findReferencesAsNodes()`

```
export function foo(){}

export function bar(){
  foo() 
}
```
Imagine if `foo` has zero references but located inside bar(), if we are to remove foo() (the perfect candidate) we still need to check if it's inside other exports that are used/not used/going to be removed. Anyway, that's just a bit complex, I need some custom handling there.

**Comment by dsherret** [comment]
@nchanged once you use binding it will have to set up the program and type checker. That has a startup cost (ex. loading lib files).

I ran a profile just now, and most of the time is spent hitting the file system (resolving modules... ex. resolving those module specifiers to see what files they could be pointing at) and then binding. I don't have the other files the module specifiers are pointing at, so there could be more costs associated with those files existing.

> I am building a tree shaking algorithm, so an average project consist of ~1500 files (including node modules), now imagine if a 7 line file takes more than a second to be analysed, what would happen with 1500 files. It would run out of memory. Typescript compiler won't

How do you know the TypeScript compiler won't? Have you analyzed this?

**Comment by nchanged** [comment]
@dsherret well not that particular case, I just know that it wouldn't take that much time ;-)
besides,  in my caseI have my own custom modules resolution and I deal with rather files in-memory as opposed to the filesystem (all my modules are resolved long before the tree shaking occurs) and I just need a super fast analysis limited to one file.

**Comment by dsherret** [comment]
@nchanged so then using the custom module resolution here and dealing with files in memory should help a bit with performance. The rest of the time will be spent binding and that's unavoidable unless you use a method that does use symbols (as `#getExportedDeclarations()` does behind the scenes).

I highly recommend not traversing all the descendants unless you need to though as that will be slow. I think you can just get away with calling `#getStatements()` on the source file (returns the child statements of the source file).

**Comment by nchanged** [comment]
@dsherret thanks for the hint! I can get them all - imports and exports now ;-) Thanks
