### ISSUE TITLE
How to detect type alias correctly

### ISSUE THREAD

**Issue by claudv** [dsherret/ts-morph#653]
I would appreciate a few pointers to understand what I am doing wrong in my attempt to detect the name of a type alias.

To give a bit of context, I am building a tool for auto generating C++ types that match TS interfaces or classes and I use ts-morph as the TS parsing engine.

I need somewhat fine-grained control on the mapping from TS `number` to different C++ numeric types (`int`, `float`, `double`, etc...). As a possible approach I can define `type int = number`, and map the `int` alias to the corresponding C++ type.

I have set up the following example, where I try to obtain `int` as a type name in different ways, none of which seems to work for me (missing some compiler option?)

**interfaces.ts**
```
export type int = number;

export interface Sandwich {
    numLayers: int;
}
```

**index.ts**
```
import { Project, ts, TypeGuards } from "ts-morph";

const project = new Project({
    compilerOptions: {
        strictNullChecks: true
    }
});

console.log("TS version: " + ts.version);

project.addExistingSourceFiles("interfaces.ts");

const sourceFile = project.getSourceFileOrThrow("interfaces.ts");
const interfaces = sourceFile.getInterfaces();

interfaces.forEach(itf => {
    console.log(itf.getName());

    itf.getProperties().forEach(p => {
        const typeNode = p.getTypeNode()!;
        const type = typeNode.getType();
        console.log(
            "Name: " + p.getName() + "\n" +
            "Text: " + type.getText() + "\n" +
            "Symbol Name: " + (type.getSymbol() ? type.getSymbol()!.getName() : "") + "\n" +
            "Alias Symbol Name: " + (type.getAliasSymbol() ? type.getAliasSymbol()!.getName() : "") + "\n" +
            "\n"
        );
    });
});
```

Output:
```
TS version: 3.5.2
Sandwich
Name: numLayers
Text: number
Symbol Name: 
Alias Symbol Name:     <-- should this return `int`? 
```

Any help is appreciated.

**Comment by dsherret** [comment]
Hey @claudv, see this issue on TypeScript's main repo: https://github.com/microsoft/TypeScript/issues/28197

Wes' response:

> For performance reasons, we intern types where possible (this way we avoid duplicating work for equivalent types). We do not currently intern anonymous object types, though we've experimented with it before. Unfortunately, interning object types has the side effect of breaking go to definition on the interned types; so we didn't pull it in. The specific types we intern today are indexed accesses, unions, and intersections (also reverse mapped types, but only inference can produce those). This is a tradeoff - origin information is lost on interned types; but we do avoid quite a bit of work most of the time.

Luckily, I think this hack fixes the problem (use a [brand](https://basarat.gitbooks.io/typescript/docs/tips/nominalTyping.html)). Does this work? Seems like arithmetic operations still work (ex. `obj.numLayers++`). Let me know!

```ts
export type int = number & { __intBrand?: undefined };

export interface Sandwich {
    numLayers: int;
}
```

**Comment by claudv** [comment]
Hey @dsherret, thanks for your help!

The brand trick seems to work indeed, and no unpleasant side effect showing up so far.
Will let you know if I run into any gotcha's that invalidate the approach.

**Comment by millsp** [comment]
> Luckily, I think this hack fixes the problem

Thanks for sharing, that helped a lot. I also found that just a simple intersection works :man_shrugging:
