### ISSUE TITLE
addPropertyAssignment remove existing properties

### ISSUE THREAD

**Issue by budiadiono** [dsherret/ts-morph#654]
**Describe the bug**

Version: 2.3.0

Adding new property using `addPropertyAssignment` or `addPropertyAssignments` on existing object literal when containing **comment** in the code it will remove existing properties.

**To Reproduce**

Let say you have this object located on `src/fixtures/object-literal.ts`:

```ts
const ObjectLiteralConst = {
  foo: 'foo',
  // comment
  meh: 'meh',
  bar: 'bar'
}
```

Now try add new propery on it:

```ts
import { Project, SyntaxKind } from 'ts-morph'

export function addPropAssigment() {
  const project = new Project()
  const sourceFile = project.addExistingSourceFile(
    'src/fixtures/object-literal.ts'
  )
  const obj = sourceFile.getFirstDescendantByKind(
    SyntaxKind.ObjectLiteralExpression
  )

  obj.addPropertyAssignment({
    name: 'yum',
    initializer: `'yummy'`
  })

  console.log(obj.getText())
}
```

console.log returns:
```bash
{
  yum: 'yummy'
}
```

It will returns correct object when you remove the `// comment` line from `src/fixtures/object-literal.ts`.

I created this [repo](https://github.com/budiadiono/ts-morph-dojo) to reproduce this issue.

**Expected behavior**

console.log should returns:
```bash
{
  foo: 'foo',
  // comment
  meh: 'meh',
  bar: 'bar',
  yum: 'yummy'
}
```

**Comment by dsherret** [comment]
@budiadiono thanks! I was working on this bug last weekend. Will be released and fixed in 3.0 probably on Monday.

**Comment by budiadiono** [comment]
Awesome! Thanks you @dsherret

**Comment by dsherret** [comment]
@budiadiono this is released now. Please review [breaking-changes.md](https://github.com/dsherret/ts-morph/blob/master/breaking-changes.md) when upgrading.

**Comment by budiadiono** [comment]
Cool! Thank you so much @dsherret!

**Comment by dsherret** [comment]
Let me know if you run into any weird behaviour. That area should be better than before... it’s gotten smarter about dealing with commas and comments. (Uses the scanner to find the right place to insert commas)

**Comment by budiadiono** [comment]
Sure
