### ISSUE TITLE
Bundle scripts

### ISSUE THREAD

**Issue by dsherret** [dsherret/ts-morph#661]
It really helps with start up time if all the scripts are bundled into a single js file.

**Comment by lazarljubenovic** [comment]
Is this about bundling the distributed code of the library itself through npm? Does in-library `require` call really make much of a difference?

**Comment by dsherret** [comment]
@lazarljubenovic Yeah, I found with another library that when I packaged everything into a single file the startup time was faster (maybe that was coincidence though... and I was using a spinning disk drive...). It would at least be good to test this out and it's pretty easy to try this out with rollup.

**Comment by dsherret** [comment]
Well, if anything this has reduced the package size from of the scripts from 3MB to 900KB.
