### ISSUE TITLE
[Question/Help] Is there any way to find out if the type is global, local or imported?

### ISSUE THREAD

**Issue by DanTsk** [dsherret/ts-morph#662]
`Date` or `Promise` types are global. Also, I can import an interface from an external module (like `express`). And my local type that was declared in the project sources.

For example, I called `getReturnType()` on `FunctionDeclaration` and get type instance. Is there any way to find out if the type is global, local or imported?

Can't find anything about it in the docs.
Thanks!

**Comment by dsherret** [comment]
@DanTsk I'm not sure if there's a way to tell if a type is imported, but you can tell if it's global by looking at the source file location of its symbol's declarations (`type.getSymbolOrThrow().getDeclarations().map(d => d.getSourceFile.getFilePath())`).

There's probably a way to get the local symbol of the type and follow that to the import declaration, but I'm not sure and haven't figured it out. My knowledge of symbols is still not great. Sorry!

**Comment by dsherret** [comment]
Closing this for now. Please reopen if necessary.
