### ISSUE TITLE
add second parameter to getParentWhile condition

### ISSUE THREAD

**Issue by Validark** [dsherret/ts-morph#669]
Builds off: https://github.com/dsherret/ts-morph/issues/107

Being able to call `node.getParentWhile(p => ts.TypeGuards.etc(p) || etc)` is very nice. However, I would like to be able to easily check whether the node under it has the proper relationship to the current parent. For example, let's say I want to figure out whether something is in the conditional of an if statement:

```ts
node.getParentWhile((p, n) => ts.TypeGuards.isIfStatement(p) && p.getExpression() === n)
```

Where:
-  `n` is the current node which starts as `node` in the above example
-  `p` is the current parent which starts as `node.getParent()` in the above example

**Comment by dsherret** [comment]
@Validark that sounds like a good idea. Would you like to implement it? If not, I'll get to it sometime soon.
