### ISSUE TITLE
Get overwritten native type

### ISSUE THREAD

**Issue by brapifra** [dsherret/ts-morph#671]
Hey, first of all, congrats for this awesome lib!
I'm trying to get the type of `T` in this file but I can't make it work:

```typescript
type Date = string;
type T = Date;
```

As far as I know I should be able to get the string type by doing something like:
```typescript
const tType = sourceFile.getDescendantsOfKind(
      ts.SyntaxKind.TypeReference
)[0];
console.log(tType.getType().getText()); // Prints Date when I need string; 
```

I've also checked its definitions, and none of them are actually the `type Date = string;` that I added at the beginning.

**Comment by dsherret** [comment]
Hey @brapifra, thanks!

So, I tried out the code you posted and for me it outputs `string` as you say is expected.

Did you mean that you expected it to print `Date` and not `string`? If so, see my comment here: https://github.com/dsherret/ts-morph/issues/653#issuecomment-506003489

**Comment by brapifra** [comment]
Wait what? It outputs `Date` for me :thinking:

All I'm doing is this:

```typescript
 const project = new Project();
 project.addExistingSourceFiles(filePath);
 
const sourceFile = project.getSourceFiles()[0];

const tType = sourceFile.getDescendantsOfKind(
  ts.SyntaxKind.TypeReference
)[0];

console.log(tType.getType().getText());
```

**Comment by dsherret** [comment]
@brapifra I added a test here that shows the behaviour I'm seeing:

https://github.com/dsherret/ts-morph/commit/05455c2fa286c9ef02dad7d6c7834fb4956a4684

**Comment by brapifra** [comment]
Hmm... interesting. I've tried your test and it works as expected. But it doesn't when I change it to use an existing source file (That's basically my case):

```typescript
it('should return string when getting the type of T', () => {
    const project = new Project();
    const file = project.addExistingSourceFile(
      join(__dirname, '../src/test.ts')
    );
    const tType = file.getFirstDescendantByKindOrThrow(
      SyntaxKind.TypeReference
    );

    expect(tType.getText()).toEqual('Date');
    expect(tType.getType().getText()).toEqual('string');
  });
```

Result:
![imagen](https://user-images.githubusercontent.com/17855450/62497871-29e06680-b7d5-11e9-8794-2db46e74e5e5.png)

**Comment by dsherret** [comment]
@brapifra strange. Is the source file text of "test.ts" exactly what you posted above? It shouldn't matter if it's an existing source file or one loaded in via text—they both are treated the same way.

**Comment by brapifra** [comment]
Yup, it has exactly the same content :confused:

**Comment by dsherret** [comment]
@brapifra oh, I know what it is. It's because the `Date` type exists in the global scope and when using a virtual file system it doesn't load in the lib files. I'm able to reproduce this now.

Basically, try pasting this into an empty .ts file:

```ts
type Date = string;
type T = Date;
```

Then inspect `Date` on `T`. You'll see it's pointing to the global `Date` object. This does not occur when using modules though:

```ts
export type Date = string;
export type T = Date;
```

I'm not sure exactly what you want to do here, but one option is to disable the lib files by using the `noLib` compiler option (probably not what you want to do though).

```ts
const project = new Project({ compilerOptions: { noLib: true } });
```

**Comment by brapifra** [comment]
Oh, true! I've just checked it and VScode already throws an error when trying to overwrite the Date type:

![imagen](https://user-images.githubusercontent.com/17855450/62498483-47aecb00-b7d7-11e9-8584-ec8a3f07858d.png)

I probably should have printed the pre-emit diagnostics as they were quite insightful:
![imagen](https://user-images.githubusercontent.com/17855450/62498531-775dd300-b7d7-11e9-85ea-58f151b2ae6a.png)

Thanks :+1:

**Comment by dsherret** [comment]
No problem! Yup, doing...

```ts
const diagnostics = project.getPreEmitDiagnostics();
console.log(project.formatDiagnosticsWithColorAndContext(diagnostics));
```

...can be very helpful for catching this stuff. I forget to do it all the time myself though :(
