### ISSUE TITLE
[Question] How to traverse a TS node?

### ISSUE THREAD

**Issue by HamedFathi** [dsherret/ts-morph#675]
Hi,

I want to know how to traverse a AST tree? 
I want to visit any node and find each `comment`. 
Something like [walk-parse5](https://github.com/stevenvachon/walk-parse5/blob/master/README.md)

```js

walk(documentOrNode, node => {
    if (node['type'] && node['type'] === 'comment') {
        var data = <string>node['data'];
    }
});
```

**Comment by dsherret** [comment]
Hey @HamedFathi,

See this page: https://dsherret.github.io/ts-morph/navigation/

I think you're probably look for either the `forEachChild` or `forEachDescendant` method.
