### ISSUE TITLE
How to find out a property in class is static?

### ISSUE THREAD

**Issue by HamedFathi** [dsherret/ts-morph#677]
I want to find out a property (PropertyDeclaration) in class is static or not?

```js
export class MyClass {

  static inject = ['A', 'B', 'C'];

}
```

Is it possible? I did not see any `isStatic()` .

**Comment by dsherret** [comment]
That's strange. The method is [`isStatic()`](https://github.com/dsherret/ts-morph/blob/1f19e2e14544cfe328458c429fcf913b3e17c32f/lib/ts-morph.d.ts#L3047) and `PropertyDeclaration` nodes implement `StaticableNode` (see [here](https://github.com/dsherret/ts-morph/blob/1f19e2e14544cfe328458c429fcf913b3e17c32f/lib/ts-morph.d.ts#L4150)).
