### ISSUE TITLE
How to use ts-morph to make Typescript dependency graph?

### ISSUE THREAD

**Issue by HamedFathi** [dsherret/ts-morph#679]
Hi,

Is it possible to define a directory and an entry point to create a Typescript file dependency graph?

![q](https://user-images.githubusercontent.com/8418700/62821058-cdd66300-bb83-11e9-9796-11670e61b7b7.png)

Any idea?

**Comment by dsherret** [comment]
There is currently a `sourceFile.getReferencingSourceFiles()` that returns all the source files that reference the current source file (assuming modules are used). I'm surprised I haven't exposed the opposite of that, so I opened #680.

**Comment by HamedFathi** [comment]
@dsherret 

Thank you so much for your help. :)

For my scenario, As you mentioned above, I need the opposite of `sourceFile.getReferencingSourceFiles()`;

`getReferencingSourceFiles` return the parent file but I need all `referenced files`.

**Comment by dsherret** [comment]
Closing. Resolution will come in #680.
