### ISSUE TITLE
Add SourceFile#getReferencedSourceFiles() and similar methods

### ISSUE THREAD

**Issue by dsherret** [dsherret/ts-morph#680]
From #679.

There currently exists the following methods:

* `getReferencingSourceFiles()` - Gets any source files that reference this source file.
* `getReferencingNodesInOtherSourceFiles()`
* `getReferencingLiteralsInOtherSourceFiles()`

...but the opposite of this doesn't exist (ex. `getReferencedSourceFiles()`). This is just hidden internally and could be easily exposed.

While doing this, `#getReferencedFiles` should probably be renamed to `getFileReference()` to prevent confusion (even though the compiler node has a `referencedFiles` property... not worth keeping the name because it's probably a rarely used method that would be easy to find on the new method name).

**Comment by HamedFathi** [comment]
@dsherret 

Any progress on this?
Any timeline?

**Comment by dsherret** [comment]
@HamedFathi I've been super busy over the past few weeks with some personal stuff. I'm going to get back at this very soon (probably today or tomorrow I will finish this one and try to do a 4.0 release very soon to fix some issues with TS 3.6)

**Comment by HamedFathi** [comment]
@dsherret 

I just say you are amazing man. thank you so much.
I did something with ts-morph. [Madeline](https://madeline.netlify.com/)

**Comment by dsherret** [comment]
This is implemented and will be in v4.0. The corresponding methods are:

* `#getReferencingSourceFiles()`
* `#getReferencedSourceFiles()`

* `#getReferencingNodesInOtherSourceFiles()`
* `#getNodesReferencingOtherSourceFiles()`

* `#getReferencingLiteralsInOtherSourceFiles()`
* `#getLiteralsReferencingOtherSourceFiles()`

@HamedFathi that's cool! The coverage feature is neat.

**Comment by dsherret** [comment]
Ok, this is released now in 4.0.
