### ISSUE TITLE
Parse all types of Imports and require

### ISSUE THREAD

**Issue by HamedFathi** [dsherret/ts-morph#682]
I need to get all parts of an `import` statement.
```
1. name
2. alias
3. module
4. resolved path
```

```js
import defaultExport from "module-name"; // (1)
import * as name from "module-name";
import { export1 } from "module-name";
import { export1 as alias1 } from "module-name";
import { export1 , export2 } from "module-name";
import defaultExport, * as name from "module-name";
import "module-name";
var promise = import("module-name");
const promise = require("module-name"); // *** require ***
```

For number (1), I did this like the following
![qqq](https://user-images.githubusercontent.com/8418700/62837040-e2982100-bc7f-11e9-99d7-d8fb086a8cf6.png)

Can you help me with others? Does exist any general way to support all of those? (even for `require`)

**Comment by dsherret** [comment]
Hey @HamedFathi, I recommend reading the docs on imports: https://dsherret.github.io/ts-morph/details/imports (let me know if anything is missing from there)

For `require` and `import` I don't think I'll be adding helper functions for those methods, but you can always get the information yourself from the compiler api using the library.

Here's an example:

```ts
const file = project.createSourceFile("test.ts", `const result = import("typescript");`);
const varDec = file.getVariableDeclarationOrThrow("result");
const callExpr = varDec.getInitializerIfKindOrThrow(SyntaxKind.CallExpression);
const moduleSymbol = callExpr.getArguments()[0].getSymbolOrThrow();
const valueDeclaration = moduleSymbol.getValueDeclarationOrThrow();

console.log(moduleSymbol.getName());
console.log(valueDeclaration.getSourceFile().getFilePath());

const type = moduleSymbol.getTypeAtLocation(valueDeclaration);
for (const prop of type.getProperties()) {
    console.log(prop.getName());
}
```

**Comment by HamedFathi** [comment]
@dsherret 
OK, thanks, so I should try line by line.
