### ISSUE TITLE
[Question] Easiest way to pick a free-to-use variable name?

### ISSUE THREAD

**Issue by lazarljubenovic** [dsherret/ts-morph#684]
This might seem like a trivial task, but I'm not sure on what's the sanest way to accomplish this. I want to transform code, and introduce some intermediate variables. I don't really care for their names, but they must not clash with anything else in the scope. Sure, I'm going to pick `__INTERMEDIATE_VALUE_${i}__`, maybe even add some weird emoji character in there, so it's never going to clash in practice, but what would be the "correct" theoretical way to accomplish choosing a free variable name?

I understand that this is more of a conundrum than an actual problem/question, but it might be a fun task (or there might be an existing method for this that I'm unaware of?). Feel free to close, of course!

**Comment by dsherret** [comment]
Hmmm, yeah interesting question. What I usually do is basically the same as you—name the variable after the package name doing the change, add a globally incrementing value, and then also do the double underscore thing (`__myPackage${++id}__`).

A better way would be to maybe use the result of a guid in the name along with a prefix of something.

---

I think probably the theoretically correct way you're wondering about would be to (haven't thought about this too much though):

1. Start with name.
2. Check the scope of where the name is going to be used by using `node.getSymbolsInScope()` (I think)
3. If a clash is found then go back to step 1 with a new name.
4. If no clash is found, then declare the name.
5. Start using the name, but check `node.getSymbolsInScope()` for clashes along the way.
6. If a clash is found, then pick a new name, check all the previous uses for clashes... if no clashes, then rename the name to the new name and continue on. Repeat step 6 until no clashes.

Alternatively, every scope could be checked before hand and then a name picked based on that.

The problem with these solutions, is that it is very expensive and slow. It's best and fastest to just pick something globally unique and not worry about it :)

**Comment by lazarljubenovic** [comment]
Indeed, I gasped when you said "check for clashes along the way" in step 5. No way! :scream: 

I guess it's perefctly fine for any codegen/codemod library to just assume that crazy things aren't used in code. The library name tip is a great idea, in case several code manipulation libs (especally of the same author) are chained together.

Thanks for sharing your thoughts.
