### ISSUE TITLE
How to get 'questionToken' from getValueDeclarationOrThrow()?

### ISSUE THREAD

**Issue by HamedFathi** [dsherret/ts-morph#688]
I wrote the following code:

```js
public getTypeDetail(node : Type)
{
    let callSignatures = node.getCallSignatures(); // 'node' is Type, 'getCallSignatures()' returns Signature[]
    let params = signature.getParameters().map(x => {
        return {
            isOptional : x.getValueDeclarationOrThrow().getQuestionTokenNode() !== undefined // getQuestionTokenNode does not exist.
        }
    }
}
```

How to get `QuestionToken` information for each parameter of `getCallSignatures()` ?

I can find it in the final result but no method found!

![Screenshot_2](https://user-images.githubusercontent.com/8418700/63225350-335dcb80-c1e4-11e9-9701-8edad0cad7c7.png)

**Comment by dsherret** [comment]
The `getValueDeclarationOrThrow()` returns a `Node` type. In this case you should be able to just assert it as a `ParameterDeclaration`.

Also, there are more ways for a parameter declaration to be optional, so you'll probably want to use the `isOptional()` helper method, which will handle all the scenarios for you (ex. it could be a rest parameter or have an initializer):

```ts
(x.getValueDeclarationOrThrow() as ParameterDeclaration).isOptional()
```

**Comment by HamedFathi** [comment]
@dsherret 

Is `isOptional()` helper method available for `PropertyDecleration` and `PropertySignature` ?

![image](https://user-images.githubusercontent.com/8418700/63408880-35eb3b80-c405-11e9-8716-ff261733234d.png)

![image](https://user-images.githubusercontent.com/8418700/63409019-8ebad400-c405-11e9-8349-c51d979eb440.png)

**Comment by dsherret** [comment]
@HamedFathi no, there's only one way for a property to be optional. There only exists a `#hasQuestionToken()` method. If an `#isOptional()` method existed it would just do `return this.hasQuestionToken()`.
