### ISSUE TITLE
Export declaration using a const

### ISSUE THREAD

**Issue by shakilsiraj** [dsherret/ts-morph#695]
How do I create an export declaration using const? 

Here is what I wanted to create:
`export const taskActions = importedTasksActions;`

I tried this:
`
sourceFile.addExportAssignment({
    isExportEquals: true,
    expression: 'importedTasksActions'
  });
`

Which produces:
`export = importedTasksActions;`
 
How do i add a name to the export? 

Thanks in advance. Awesome library by the way!

**Comment by dsherret** [comment]
Hey @shakilsiraj, thanks!

That's a variable statement. See [here](https://ts-ast-viewer.com/#code/KYDwDg9gTgLgBAYwgOwM7xgQ1QawIIIwCWKqcAvHEQLaSzAAmAKtjqgcaQNxA).

![image](https://user-images.githubusercontent.com/1609021/64128493-d2f29080-cd84-11e9-838a-e990622aa110.png)

You can use `add/insertVariableStatement(s)`. For example:

```ts
sourceFile.addVariableStatement({
    isExported: true,
    declarationKind: VariableDeclarationKind.Const,
    declarations: [{
        name: "importedTasksActions",
        initializer: "importedTasksActions"
    }]
});
```

**Comment by shakilsiraj** [comment]
Worked like a charm. Thanks very much :).
