### ISSUE TITLE
Question: Getting the text of direct child intersection types

### ISSUE THREAD

**Issue by jxom** [dsherret/ts-morph#697]
Hey! 

I'm quite new to parsing ASTs, and I would very much appreciate some help! Anyway, I have a bunch of types that look like so:

```
export type D = {
    test: string
}
export type C = D & {
    baz: string
}
export type B = C & {
    bar: string
}
export type E = {
    foo: string
};
export type A = B & E;
```
or [see in the AST viewer](https://ts-ast-viewer.com/#code/KYDwDg9gTgLgBDAnmYcAicC8cDeAoOQhYAZxgC44yoBLAOwHM8BfPUSWBZVAYS3TgAyXASIAjAIYAvStXpNW7aPCQo4AIX59h+InElRZMWoxZtwyrmoCi-XUQBmECEZMKA3OY4rucAIL8msLW7kA)

Basically, I want to get the text of the intersection types of `A`. In this case it would be `"B"` & `"E"`.

At the moment, I am trying to get the intersection types like so:

```
node.getType().getIntersectionTypes()
```

However, this method seems to get all the *deep* intersection types (so [`B`, `C`, `D`, `E`]). Is there a way to just get the direct child types of `A` (`B` and `E`)?

Thanks!

**Comment by dsherret** [comment]
Hey @jxom,

The `#getType()` method uses the type checker to get the type and the type checker does some inlining. I don't believe there's any way to undo what it does... this is somewhat related to 653#issuecomment-506003489

On ts-ast-viewer.com on the right side under `Type`, it shows the compiler api result of `#getType()`. If you want the AST node, then use `#getTypeNode()`:

```ts
const typeNode = node.getTypeNode();

if (TypeGuards.isIntersectionTypeNode(typeNode)) {
    console.log(typeNode.getTypeNodes().map(t => t.getText())); // ["B", "E"]
}
```

**Comment by jxom** [comment]
It works! Thanks so much 🙏
