### ISSUE TITLE
MethodParameters - not easy to import EnumDeclaration

### ISSUE THREAD

**Issue by brianzinn** [dsherret/ts-morph#704]
**Is your feature request related to a problem? Please describe.**
I cannot import classes and enums using the same or easily discoverable way.

**Describe the solution you'd like**
I would like to import enums and classes using the same code transparently.

**Describe alternatives you've considered**
I did find a workaround.  I will describe the original problem a workable solution and what I would have preferred.
```ts
const method: MethodDeclaration = getMethodDeclaration();
method.getParameters().forEach((createMethodParameter: ParameterDeclaration) => {
   const paramText = createMethodParameter.getType().getText();
   // a class imported will be
   assertEquals("import("/Users/.../node_modules/npm_name/namespace").ClassName", paramText)

  // an enum will be missing import("...")
  assertEquals('EnumName', paramText)
  
  // What I did find with looking through TypeScript docs and Node debugging was:
  methodParameter.getType().getSymbol().getFullyQualifiedName();
});
```

So, I can work around it using `.getSymbol().getFullQualifiedName()`.  This doesn't feel natural - Would be nice to have getText() work the same or have maybe getFullyQualifiedName() as a convenience method included to discover without breaking Law of Demeter!  There is nothing in your docs about getQualifiedName().  **Feel free to close if you don't think any changes are needed** or I can do a PR if you think adding a method makes sense. Mostly wanted to share what took some time to figure out.  Great project - really enjoy it.

**Comment by dsherret** [comment]
Hey @brianzinn, I'm glad you enjoy the library! 🙂

The `#getText()` method just calls `TypeChecker#typeToString` in the compiler api.

Does the enum happen to be in the same file? If so, it won't have the import type. I believe it should if it's in a different file than the method parameter.

Maybe related: https://github.com/dsherret/ts-morph/issues/453#issuecomment-427405736

**Comment by brianzinn** [comment]
That makes sense and then everything is working as expected.  I am using a combination of looping through namespaces, getFullyQualifiedName() and a hacky regex `/import\(\"([^\"]+)\"\)\.([^<>,;\|) ]+)/` to accomplish everything.  What I am doing is generating a project from another library typings, so this project has made that much easier.  Thanks again!
