### ISSUE TITLE
How to get the exact file location from import("...").TYPE?

### ISSUE THREAD

**Issue by HamedFathi** [dsherret/ts-morph#705]
Hi,

For a type, I used `type.getText()` and Typescript get the following result:

```
"import(\"C:/.../packages/testing/node_modules/@aurelia/kernel/dist/di\").InterfaceSymbol<import(\"C:/.../packages/testing/node_modules/@aurelia/runtime/dist/observation/observer-locator\").IObserverLocator>"
```

I want to access the exact location of `InterfaceSymbol` and `IObserverLocator` types.
What files have the definition of these types?

Or

```
import(\"C:/.../node_modules/@types/webpack/index\").loader.LoaderContext
```

Which file in `webpack` package has the definition of `LoaderContext`?

Is it possible to find the exact file location of a type definition? like VSCode `Ctrl + Click` on a type

I want to make an API documentation generator so I need to click on each type and go to the definition in other site location before this I need to know the relation between types and where they are from.

**Comment by dsherret** [comment]
> Is it possible to find the exact file location of a type definition? like VSCode Ctrl + Click on a type

This is Ctrl + Clicking on a node—not a type. It's possible to do on an identifier node and that functionality is exposed with these two methods:

```ts
const definitions = identifier.getDefinitions();
// or
const nodes = identifier.getDefinitionNodes();
```

If you just have the type then you should be able to get it via the type's symbol:

```ts
const project = new Project();

const sourceFile = project.createSourceFile("test.ts", `class Test { prop: string; }
const myVar = new Test();`);

const myVarDec = sourceFile.getVariableDeclarationOrThrow("myVar");
const myVarDecType = myVarDec.getType();

// use getSymbol() to handle when the symbol doesn't exist
console.log(myVarDecType.getSymbolOrThrow().getDeclarations().map(d => d.getSourceFile().getFilePath()));
```

Outputs:

```
["/dir/test.ts"]
```

To be honest though, I'm not sure if my answer is entirely correct.

**Comment by HamedFathi** [comment]
@dsherret 

You help was so good thanks :)
