### ISSUE TITLE
Support trailing comma

### ISSUE THREAD

**Issue by kazelone** [dsherret/ts-morph#707]
**Is your feature request related to a problem? Please describe.**

A common use case for ts-morph is to add some element to an array, for example adding a new module to a `@ngModule` decorator. However, There doesn't seems to be an option to force a trailing comma.

It is a common practice to force trailing comma to minimize meaningless diff when adding new element; for example, it is the default in the recommended linting for typescript (https://github.com/palantir/tslint/blob/master/src/configs/recommended.ts)

**Describe the solution you'd like**

It would be nice to have this as an option in `manipulationSettings`, just like for `quoteKind`.

**Describe alternatives you've considered**

You can still do it by manually outputting the statement but it would be cleaner to use such an option and keep using `addElement()` or `addMember()`.

**Comment by dsherret** [comment]
This will be implemented in 4.2 (releasing very soon).

It will just have basic support for trailing commas, so for anything more advanced I would recommend not bothering with this and just use a code formatting library (such as the one I am currently working on: https://github.com/dsherret/dprint -- that formatter will give you very fine control over trailing commas per ast node)
