### ISSUE TITLE
getParentIf and getParentIfOrThrow

### ISSUE THREAD

**Issue by HoldYourWaffle** [dsherret/ts-morph#712]
**Is your feature request related to a problem? Please describe.**
There's already a `getParentIfKind` and `getParentIfKindOrThrow`, it would be nice if we could extend this convenience beyond kind comparisons, just like with `getParentWhile`.

**Describe the solution you'd like**
Two additional convenience methods: `getParentIf` and `getParentIfOrThrow`. They'd behave in the same way as their 'kind'-counterparts, except taking a predicate instead of a `SyntaxKind` to compare to.

**Describe alternatives you've considered**
It's entirely possible to do this manually, this is just a cleaner & more readable solution.

**Comment by dsherret** [comment]
Implemented by @HoldYourWaffle in #714.
