### ISSUE TITLE
Providing custom messages to OrThrow methods

### ISSUE THREAD

**Issue by HoldYourWaffle** [dsherret/ts-morph#715]
**Is your feature request related to a problem? Please describe.**
It's currently not possible to provide specific error messages to the `XXXOrThrow` methods. This limits these "AST assertions" to generic error message that most likely won't help a user of your library.

To put it another way: the current error messages can only tell you *what* was expected, not *why* it was expected.

**Describe the solution you'd like**
I'd love to add an optional `message` parameter to all the `OrThrow` methods. If this parameter isn't specified the current 'generic' messages should be used.

**Describe alternatives you've considered**
You could try-catch the assertions and throw your own error but this is clunky and doesn't really work for multiple assertions.

**Comment by dsherret** [comment]
Yeah, this is a really good idea. It should be possible to add this feature to the library using a programmatic refactor (so please if someone goes to implement this don't do it manually)

**Comment by jantimon** [comment]
@dsherret @HoldYourWaffle I believe this idea could improve ts-morph based scripts a lot!

I prepared https://github.com/dsherret/ts-morph/pull/1327 to add the feature but I would need help (and feedback) to finalize it.

![Preview](https://user-images.githubusercontent.com/4113649/189446754-6659934a-879b-4ebe-9537-22eba6200024.png)

As you can see it would also show the end-user of the file and the location to understand which part of the AST triggered the exception.
