### ISSUE TITLE
How to get all exported blocks of code (nodes)?

### ISSUE THREAD

**Issue by HamedFathi** [dsherret/ts-morph#716]
Is it possible to get all `exported` blocks of code (nodes)?

From the `export clause`, `export modifier`, `named export` and etc with any depth. 
For example:
```ts
const theAnswer = 42;
export { theAnswer };

export class A {}

export interface IB {}
export { IB as X};

export * from './src';

import { foo } from './foo';
export { foo };

export {
  relativeToFile,
  join,
  buildQueryString,
  parseQueryString,
  IQueryParams
} from './path';
```

I want to access all nodes that are exported. `theAnswer` has no export modifier but it is exported so it is a public API. Is it possible to fetch all exported nodes from a package with any nested/recursive dependency? (nothing else)

Actually I read [exports section](https://ts-morph.com/details/exports) but I am not sure **Is it support above scenarios**? Should I do extra work?

**Comment by dsherret** [comment]
@HamedFathi is `sourceFile.getExportedDeclarations()` what you're looking for or is there something else more specific?

https://ts-morph.com/details/exports#getting-exported-declarations

**Comment by HamedFathi** [comment]
@dsherret

I think `sourceFile.getExportedDeclarations()` is enough but
1. Does it resolve any kind of export? (Above samples)
2. It returns duplicate nodes however this is not wrong but I need just non duplicate nodes.

sample.ts
```
export class X {}
```

index.ts
```
export { X } from './sample';
```

It returns 2 records for `X` first from `sample.ts` and second `index.ts`.

I solved this problem with a hash code as an `id`.
```ts
getSha256(node.getFullText() +node.sourceFilePath())
```

Any better solution?
