### ISSUE TITLE
[Req] Add Typescript Type Guards documentation

### ISSUE THREAD

**Issue by HamedFathi** [dsherret/ts-morph#729]
Do you support [User Defined Type Guards](https://basarat.gitbooks.io/typescript/docs/types/typeGuard.html#user-defined-type-guards)?

May I ask you to add documentation about this?

```ts
/**
 * Just some interfaces
 */
interface Foo {
    foo: number;
    common: string;
}

interface Bar {
    bar: number;
    common: string;
}

/**
 * User Defined Type Guard!
 */
function isFoo(arg: any): arg is Foo {
    return arg.foo !== undefined;
}
```

How to get `arg is Foo`? What is the relation to this block and `arg` as a parameter? How to get type of `Foo`.

It would be great if add this to your documentation.

**Comment by dsherret** [comment]
See here:

https://ts-ast-viewer.com/#code/GYVwdgxgLglg9mABDAzgMTnAFAQwE4DmAXIjmAJ4CUJ+ByKiGciA3gLABQi3ieAplBB4ktAHTBMiAIQBeGYnAATPsBhg+igNycAvkA

It's a `TypePredicate`. I just wrapped that node in 4.2.0 (see #722).

I don't know if I'm going to add documentation for it though beyond what's in the JS docs (I need to revamp the documentation).

**Comment by HamedFathi** [comment]
@dsherret 

I can not find any `getTypePredicate()` or something like this.

![image](https://user-images.githubusercontent.com/8418700/66259617-d6cc6500-e7bf-11e9-9f3d-fbf31de17562.png)

May I ask you to share an example?

**Comment by dsherret** [comment]
Use `getReturnTypeNode()` then check if that is a type predicate using `TypeGuards.isTypePredicateNode`.
