### ISSUE TITLE
getConstraintOrThrow() does not return the type text with import("").

### ISSUE THREAD

**Issue by HamedFathi** [dsherret/ts-morph#736]
Hi
Please see the following example:
```ts
const src = `
export interface Length {
    length: number;
}

export class Test
{
   length: Length;
}

export function identity<T extends Length>(arg: T): T {
   return arg;
}
`;
const project = new Project({
    compilerOptions: {
        target: ScriptTarget.ES5
    }
});
const file = project.createSourceFile("test.ts", src);
file.forEachDescendant(x => {
    switch (x.getKind()) {
        case SyntaxKind.PropertyDeclaration:
            let prop = x as PropertyDeclaration;
            // import('...').Length
            let propTypeText = prop.getType().getText();
        break;
        case SyntaxKind.FunctionDeclaration:
            let func = x as FunctionDeclaration;
            // Length
            let funcTypeText1 = func.getTypeParameters().map(x=>x.getConstraintOrThrow().getText())
            // Length
            let funcTypeText2 = func.getTypeParameters().map(x=>(x.getConstraintOrThrow() as unknown as Type).getText());
        break;
    }
});
```

`propTypeText ` contains `import("...").Length` so I find out where is `Length`.
but when I use it as constraint `funcTypeText2 ` just returns the name.

How can I get `getConstraintOrThrow()` type result just like `.getType().getText();`? 

![image](https://user-images.githubusercontent.com/8418700/66901811-4d613200-f00c-11e9-9bb6-926a68f8ee56.png)

![image](https://user-images.githubusercontent.com/8418700/66901839-59e58a80-f00c-11e9-99fd-7488774d3f0f.png)

![image](https://user-images.githubusercontent.com/8418700/66901865-64078900-f00c-11e9-9859-0de21a37423d.png)

**Comment by dsherret** [comment]
@HamedFathi the return type of `#getConstraintOrThrow()` is a `TypeNode`, so that's a node in the AST. It's not a type (the `(x.getConstraintOrThrow() as unknown as Type).getText()` doesn't make sense and only works because `TypeNode` and `Type` happen to both have `getText()` methods that return a string).

Also, it's probably not ideal to rely on using the import type text to find out where a type is. You should be able to do something like `type.getSymbol()?.getValueDeclaration()?.getSourceFile()`

**Comment by dsherret** [comment]
> How can I get getConstraintOrThrow() type result just like .getType().getText();?

Use:

```ts
x.getConstraint()?.getType()?.getText();
```

**Comment by HamedFathi** [comment]
> Also, it's probably not ideal to rely on using the import type text to find out where a type is. You should be able to do something like type.getSymbol()?.getValueDeclaration()?.getSourceFile()

@dsherret, Your help is great just like always, but I need more. please consider the following example

```ts
export interface ITest1 {
    a1: number;
}
export interface ITest2 {
    a2: number;
}

export interface IGTest<T,U>
{
    t: T;
    u: U;
}

export function test() : IGTest<ITest1,ITest2>
{
    return ...
}
```

`.getReturnType().getText()` returns

**import("D:/...generator/test2").IGTest<import("D:/...generator/test2").ITest1, import("D:/...generator/test2").ITest2>**

As you can see `getText()` returns 3 imported paths. this is necessary for me. Now, I know 3 types involved in this type of node. unfortunately `type.getSymbol()?.getValueDeclaration()?.getSourceFile()` does not work for this scenario.It only seems to work for simple types. I need `sourceFilePath` for all of the involved types (IGTest, ITest1, ITest2). If you run this code on VSCode you can click on IGTest, ITest1 or ITest2 to find the definition location.

Is it possible to use your great guidance based on each import block (each type that is recognized)?

Unfortunately, for now, I use a regex to split imports and a TypePathMapper (string to string mapper) to file all types of definition paths.

Is it possible to find `getSourceFile` for IGTest,ITest1,ITest2?

**Comment by HamedFathi** [comment]
@dsherret Any idea?!

**Comment by dsherret** [comment]
There isn't a general solution as what some people want could be different from others. I'm AFK at the moment, but you should be able to get everything you need by navigating between symbols and types. You'll have to figure it out on your own though as I'm not so familiar with that part of the compiler.

In case something is missing, it might not be exposed in ts-morph so check`TypeChecker#compilerObject` for any useful missing methods or look in the Typescript compiler source code to see if it's not exposed there.

Additionally, ensure `project.getPreEmitDiagnostics()` has no results. Compile errors can sometimes prevent types from being resolved.

**Comment by HamedFathi** [comment]
@dsherret 

I am not sure what is the best way but I wrote the following code not bad to share here.

```ts
function getUsedTypes(node: Node): Type[] {
    const result: Type[] = [];
    const types = new Set<Type>();
    node.forEachDescendant(descendant => {
        if (TypeGuards.isTypedNode(descendant) || TypeGuards.isIdentifier(descendant)) types.add(descendant.getType());
        else if (TypeGuards.isReturnTypedNode(descendant)) types.add(descendant.getReturnType());
    });
    types.forEach(type => {
        if (!type.isAny() && !type.isUnknown() && !type.isNull() && !type.isNullable()) {
            result.push(type);
        }
    });
    return result;
}

function extractFromNode(node: Node, type: Type): TypeInfo {
        let typeImports: NewTypeImport[] = [];
        let types = getUsedTypes(node);
        let typeText = type.getText();
        let importedTypes: string[] = [];
        const importRegex = new RegExp(/import\((.+?)\)\.([^;>,\[\]\)\(<{}&!\s]+)/gm);
        const allImports = typeText.match(importRegex);
        if (allImports) {
            for (const imported of allImports) {
                let name = removeTypesImports(imported);
                importedTypes.push(name);
            }
            for (const t of types.valueOr([])) {
                let symbol = t.getSymbol();
                if (symbol) {
                    let declarations = symbol.getDeclarations();
                    for (const d of declarations) {
                        let path = d.getSourceFile().getFilePath();
                        let kind = d.getKind();
                        let kindName = d.getKindName();
                        let name = '';
                        let sym = d.getSymbol();
                        if (sym) {
                            name = sym.getName();
                            if (importedTypes.includes(name)) {
                                typeImports.push({
                                    kind: kind,
                                    kindName: kindName,
                                    path: path,
                                    name: name,
                                })
                            }
                        }
                    }
                }
            }
            return {
                text: typeText,
                value: removeTypesImports(typeText),
                imports: typeImports
            }
        }
        return {
            text: typeText,
            value: removeTypesImports(typeText),
            imports: undefined
        };
    }
```

Thanks.
