### ISSUE TITLE
Decorator: Get true function name or import module / path.

### ISSUE THREAD

**Issue by j** [dsherret/ts-morph#740]
I want to filter files that are decorated by a real decorator from a specific imported module.

I.E.

```typescript
import { Decorator as D } from 'something';

@D()
class Foo {
}
```

I know I can find this class by searching for D, but I want to find it by the true decorator name as well as the decorated import class.

I want to make sure the class is decorated with `Decorator` from `something` module.

Is this possible?

**Comment by dsherret** [comment]
Try doing this (but use and handle `getSymbol()` instead of `getSymbolOrThrow()`):

```ts
// untested
for (const dec of classDec.getDecorators()) {
    // check this returned array to find the function you're looking for
    const declarations = dec.getType().getSymbolOrThrow().getDeclarations();
    // or try this (I'm still not sure about what the difference between these two is... I should ask the compiler team)
    const declaration = dec.getType().getSymbolOrThrow().getValueDeclaration();
}
```

If that doesn't work, then try this (but it relies on the language service so will probably be slower):

```ts
for (const dec of classDec.getDecorators()) {
    // check this returned array to find the function you're looking for
    dec.getNameNode().getDefinitionNodes(); 
}
```
