### ISSUE TITLE
[Question] How to get nested modules/namespaces?

### ISSUE THREAD

**Issue by HamedFathi** [dsherret/ts-morph#744]
How to get information about nested modules/namespaces?

```ts
module M1 {
    export namespace NS1 {
        module M2 {
            var x = 1;
            namespace NS2 {
                class Greeter {
                    greeting: string;
                    constructor(message: string) {
                        this.greeting = message;
                    }
                }
            }
        }
    }
}
```

**Comment by lazarljubenovic** [comment]
What kind of information? They are just nested nodes in the AST tree, like many other nested nodes. You can query them based on what you need to extract from the source code.

**Comment by dsherret** [comment]
@HamedFathi do you mean like calling `getNamespaces()` on the `NamespaceDeclaration`? To go up the tree there is a helper `getParentNamespace()` method on some of the nodes.
