### ISSUE TITLE
VariableStatement in ExportedDeclarations

### ISSUE THREAD

**Issue by HamedFathi** [dsherret/ts-morph#746]
Why don't you allow `VariableStatement` in the `ExportedDeclarations` type?

```ts
export declare type ExportedDeclarations = 
ClassDeclaration
| InterfaceDeclaration 
| EnumDeclaration 
| FunctionDeclaration 
| VariableDeclaration 
| TypeAliasDeclaration 
| NamespaceDeclaration 
| Expression;
```

I think a `VariableStatement` is exportable not each inside declarations, Yes?

![image](https://user-images.githubusercontent.com/8418700/67222821-f52a9580-f43a-11e9-8726-8de534b35875.png)

Is it possible for you to add `VariableStatement` to `ExportedDeclarations`  type?

**Comment by dsherret** [comment]
That's not done because it's possible for not all the declarations to be exported in a variable statement. For example:

```ts
const a, b, c;

export { a };
```

Have you found a `VariableStatement` type being returned in `getExportedDeclarations()`? If so, let me know as that would be a bug.

**Comment by HamedFathi** [comment]
> Have you found a VariableStatement type being returned in getExportedDeclarations()
No, based on your description it is correct. No bug.

Thanks.
