### ISSUE TITLE
Custom module resolution (question)

### ISSUE THREAD

**Issue by donovanhiland** [dsherret/ts-morph#748]
I'm trying to migrate an existing codebase to typescript. The project was using webpack's module resolution where we resolve components in any `shared` folder in the app like we would resolve modules in `node_modules`. It will recursively look up the tree until it finds a match.

So if a file lives in `src/app/screens/shared/components/Button` and I try to import `components/Button` from within the `screens` directory it will resolve.

I feel like there's a way I could make this transformation with `ts-morph` but can't quite put the dots together. Any ideas?

Ideally I would be able to transform:
```
import Button from 'components/Button'
```
to
```
impot Button from 'src/app/screens/shared/components/Button'
```

**Comment by lazarljubenovic** [comment]
If you quickly need this once (you don't expect to run the same script over and over, or as a part of deployment process), it seems like using ts-morph might be an overkill. You could easily search and replace for `from 'components/`, and just quickly scan the git diff to see if something else accidentally got caught. It seems faster to me.

Of course, it's possible with ts-morph. Just suggesting to look at the bigger picture.

**Comment by donovanhiland** [comment]
The problem is that it’s not a direct 1 to 1 relationship. There could be any number of shared folders and it would be impossible to find and replace as the paths would be different based on where it’s being imported from and where the nearest matching shared folder module is location in relation

**Comment by dsherret** [comment]
Hey @donovanhiland, I believe you should be able to get this to work by providing a custom module resolution host: https://ts-morph.com/setup/#custom-module-resolution

Once that's setup, you could use `importDec.getModuleResolutionSourceFile()` to resolve the source file then use `importDec.setModuleSpecifier("new-value-goes-here");` to update the values. There is also a `sourceFile.getRelativePathAsModuleSpecifierTo(otherSourceFile)` that might be useful, but I'm not sure.
