### ISSUE TITLE
Integrating with monaco-editor

### ISSUE THREAD

**Issue by rizkyramadhan** [dsherret/ts-morph#749]
I am trying to make ts-morph work as language server for [monaco-editor](https://microsoft.github.io/monaco-editor/). Is there a tutorial or a guide to do this the right way ?

**Comment by dsherret** [comment]
No, I don't recommend using ts-morph for editor plugins as it's not really designed for that and you will use a lot of memory. (mostly only for doing large refactors or code generation)
