### ISSUE TITLE
How to get type of a tag in JSDoc?

### ISSUE THREAD

**Issue by HamedFathi** [dsherret/ts-morph#752]
```ts
/**
 * Check whether milk is solid at room temperature.
 * @return {boolean} Always returns false.
 */
function test() {
    return false;
};

/**
 * Represents a book.
 * @constructor
 * @param {string|boolean|number} p- The title of the book.
 */
function Book(p) {
}
```

How to get `boolean` for `@return` tag in JSDoc?
How to get `string|boolean|number` for `@param` tag in JSDoc?

`JSDocTag.getType().getText()` returns `any`.

**Comment by dsherret** [comment]
@HamedFathi I'm not sure why the compiler returns `any` in that scenario. It seems on the `JSDocReturnTag` you will need to do `getTypeExpression().getTypeNode().getType()`

**Comment by HamedFathi** [comment]
@dsherret 

How to find out which one of JSDoc tags have `getTypeExpression()`?

**Comment by dsherret** [comment]
@HamedFathi that won't be reliable because there are a lot of methods missing on JS Docs. Someone will need to go implement this feature if they want it. See #753.

For now, it's possible to fall back to using the compiler api and check for `typeExpression` on `tagName.compilerNode`.

**Comment by HamedFathi** [comment]
@dsherret 

May I ask you to share a snippet code for getting the types `(string|number)` for the following example with me?

```ts
/**
* @param {string|number} somebody
*/
function sayHello(somebody) {
   alert('Hello ' + somebody);
}
```

**Comment by dsherret** [comment]
@HamedFathi 

1. Go here: https://ts-ast-viewer.com/#code/PQKhFgCgQAgAQA4EMBOSC2MDeBnALigJYB2A5gD7ECu6ARgKYrkCCKaAngL4w4D269WrwAm7KCGBQAZlWIBjPIV7EeSdgAl6AGy28AFHwFDRASmxQYlpFsZ49Ack07eMezADUPfoJHsTAbihOIA
2. Then go to options and select "Tree Mode" to be "getChildren()".
3. Then in the middle area, it will now show what the tree looks like there

**Comment by HamedFathi** [comment]
@dsherret 
Thanks

**Comment by IvanFarkas** [comment]
Here is the code to get all JSDoc metadata. See [AST](https://ts-ast-viewer.com/#code/PQKhCgAIUgVBTAzgFwErwGaQMYBsCGiikAtHEspOhlDAAJ6GK2QMFEAmS25K1O7Yl0TYATgEsADsnEB7AHYA6FnUkBXAEa5x2Wisn5R+ALaQA3vLXGN8UQF9Il67YAKo2ZNKOrN0ZDceXhjupoxE+oYm5igS8gDmDjEBnmQx4vH+7imQwbKhghFGpmYasrK48PjyDqXlyV61FVWZgWS5+UyFUWYAIvjI8A4c-fD1ZH0DLdntAp3QwODwAB6SsqKUYcQIfJjm4ACQoBD70KzYCjFq2MhrB9B39AZF5k6+Dq+uWV4ffmM5ITgLshRFcbqIHqwnt00vFEsC-jC4lMggDzvJLtdbidHpFio1KtVII0-vjmn8ZmiMWCIapceYJoNIMMBn8Gci2qigSDMeDsQt9pTgaC1gAKACUe32h2AcAAnpIkAAuSAAbQABrAAMpyhVqyAAYi1kB6mHwalwyH1rCNAElEAA5c0ELTwOiQAB6AHkAII6+DuyAAPx9kAAYmtjP1AwBdLwAC2QyEkiEVwGAongcWWAEYAAzZxTnYwHaV+zViKSUCb4P3EMgJpMptMAd1bimQ8u4EmkBHiijWcWAHFk2EQwDjVQ4tQA1sANIQdCQOwrEIoE8ZcCW05BPQr5N6XDbjf0a7BO3XIA3k6ngIhm-g4lnRIo5EOR2PEArsOIMDp+nJ5CHE8SGMWQuFwMdmXwJdzxLZA43EVcfnqABebxcFwABuSBtzPFdlXVH49X1XMrToIVXQ9H4A0DGNSDghDVySL40MsDDsNw88CLVRFiIAcnteBm0gAA1fBcDUeA+LIii3XdREaLokgGMQxRiRY9CsJwmU8KVVU1VJeRiIomSQUo91DMU2NlKleDVOZUYNLYrTOPw-SGWI+QhOPAZxTIuSFKDBylIOOxwAOG5NWBdI4nFSV9gzZA1FEeRIAAKU1T17UUREf1lEU7MQMVMNC8AwqAA)

```TypeScript
const sourceFile = tsMorphProject.createSourceFile(
  "index.js",
  [
    "/**",
    " * TestRef class - Test Ref",
    " * @class",
    " * @classdesc TestRef class description.",
    " * @public",
    " *",
    " * @param {number} numberProp - number Prop - from class",
    " * @param {string} strProp - string Prop - from class",
    " * @param {boolean} boolProp - boolean Prop - from class",
    " * @param {Date} dateProp - Date Prop - from class",
    " */",
    "export class TestRef {",
    "	/**",
    "	 * @constructor",
    "	 *",
    "	 * @param {number} numberProp - number Prop - from constructor",
    "	 * @param {string} strProp - string Prop - from constructor",
    "	 * @param {boolean} boolProp - boolean Prop - from constructor",
    "	 * @param {Date} dateProp - Date Prop - from constructor",
    "	 */",
    "	constructor() {",
    "		// Types: [`TS Type` #TS Default# @TS IsNullable@ ^OA Type^ ~OA Format~] - https://regex101.com",
    "		// TypeScript Data Types - https://www.typescriptlang.org/docs/handbook/basic-types.html",
    "		// OpenAPI Data Types - https://swagger.io/docs/specification/data-models/data-types",
    "		this.numberProp = null; // Types: [`number` #0# @true@ ^number^ ~~] -",
    "		this.strProp = null; // Types: [`string` #'New Value'# @true@ ^string^ ~~] -",
    "		this.boolProp = null; // Types: [`boolean` #true# @true@ ^boolean^ ~~] -",
    "		this.dateProp = null; // Types: [`Date` #new Date()# @@ ^string^ ~date~] -",
    "	}",
    "",
    "	toString() {",
    "		return JSON.stringify(this);",
    "	}",
    "}",
  ].join("\n")
);
const classDecl = sourceFile.getClass("TestRef");
const constrDecl = classDecl?.getConstructors()[0];

for (let i = 0; i <= 1; i++) {
  let jsdocs: JSDoc[] | undefined;
  if (i === 0) {
    jsdocs = classDecl?.getJsDocs();
    console.log("");
    console.log("Class");
  }
  if (i === 1) {
    console.log("");
    console.log("Constructor");
    jsdocs = constrDecl?.getJsDocs();
  }
  jsdocs?.forEach((jsDoc: JSDoc) => {
    const description = jsDoc.getDescription();
    const comment = jsDoc.getCommentText();
    const tags = jsDoc.getTags();

    tags?.forEach((tag: JSDocTag<ts.JSDocTag>) => {
      const tagName = tag.getTagName();
      const tagcomment = tag.getCommentText();
      const tagText = tag.getText();
      let paramName: string = "";
      let paramType: string | undefined = "";

      if (tag instanceof JSDocParameterTag) {
        const paramTag = tag as JSDocParameterTag;
        paramName = paramTag.getName();
        paramType = paramTag.getTypeExpression()?.getTypeNode()?.getText();
      }
      console.log(`tagName:${tagName} paramName:${paramName} paramType:${paramType} tagcomment:${tagcomment}`);
    });
  });
}

```
