### ISSUE TITLE
Issues with changes not detected immediately after ts-morph exits

### ISSUE THREAD

**Issue by Roaders** [dsherret/ts-morph#755]
**Describe the bug**
It seems that writing of source files happens after ts-morph has exited (and after subsequent tasks run).

Version: 5.0.0

A migration script that runs `ts-morph` to replace imports then immediately runs `tslint --fix` to reorder imports does not successfully reorder the imports. If I run the script a second time the out of place imports are correctly picked up by tslint and are fixed.
I am wondering if the actual writing of the source files is happening after ts-morph exits.

I am kind of expecting the response to be no you're crazy this can't happen but at the moment I can't see anything else that explains what I am seeing...

If I add a 2 second delay between ts-morph finishing and lint starting it DOES work correctly.

**Comment by dsherret** [comment]
This is probably my fault. I’ve been meaning to update the docs. Are you awaiting the result of calling `.save()`?

Side note: probably don’t use `.saveSync()` on a project because it will be super slow in comparison.

**Comment by Roaders** [comment]
yes, that sounds like that's the problem. Is there a callback I can use to be informed when it's finished?

**Comment by dsherret** [comment]
@Roaders it returns a promise so you should be able to do `project.save().then(() => console.log("Done."))` or use the `await` keyword in certain contexts.

**Comment by Roaders** [comment]
ok, thanks. I'll give that a try.

**Comment by dsherret** [comment]
@Roaders please reopen this if it's still an issue.
