### ISSUE TITLE
How to get the full inferred type from a mapped type?

### ISSUE THREAD

**Issue by InExtremaRes** [dsherret/ts-morph#758]
First of all congratulation for this project!

Recently I open [a question](https://stackoverflow.com/questions/58699171/emit-an-inferred-mapped-type-to-a-d-ts) on StackOverflow but it haven't got enough traction.

I'm using this project now and everything is much more clean; still I couldn't get this working properly. My lack of understanding the compiler API is probably the biggest issue (and that I'm not a native english speaker).

A summary of the problem: My project has some _services_ classes and there is a mapped type that "creates" a type with the arguments and result of every service, which is inferred from the classes. The type inference works just fine, but now I want to emit a single .d.ts file with the _full inferred type_, without referencing any named type of the project.

The mapped type looks like this:

```ts
import { CArgs, CRes } from '../utils';

type S = import('src/applications').Services;
export type Commands = {
    -readonly [P in keyof S]: {
        args: CArgs<S[P]>;
        res: CRes<S[P]>;
    };
};
```

And my expected result is like this:

```ts
type Commands = {
    Com1: {
        args: number;
        res: void;
    };
    Com2: {
        args: {foo: string};
        res: string[];
    };
    // ... etc ...
};
```

I'm getting now some vaguely similar using a code like this:

```ts
import { Project, ts } from 'ts-morph';

// Project with the sources, uses baseUrl and paths
const projectSrc = new Project({
    tsConfigFilePath: 'tsconfig.prot.json',
});
const projectDest = new Project();

const protocolSrc = projectSrc.getSourceFileOrThrow('protocolo.ts');
const commandsNode = protocolSrc.getTypeAliasOrThrow('Commands');

const protocolDts = projectDest.createSourceFile('protocol.d.ts', protocolSrc.getStructure());
protocolDts.getImportDeclarations().forEach(x => x.remove());
protocolDts.getTypeAliasOrThrow('Commands').remove();

protocolDts.addTypeAlias({
    name: 'Commands',
    isExported: true,

    type: commandsNode
        .getType()
        .getText(
            commandsNode,
            ts.TypeFormatFlags.InTypeAlias | ts.TypeFormatFlags.NoTruncation
        ),
});

console.log(protocolDts.getFullText());
```

The output is not pretty (the type is a little big and is not formatted) but mostly works. The problem is that I am getting some references to named types (some even with the `import(...).Type` syntax) instead of just a full, plain type.

So:

Is that possible?

Is this a good approach for this or there is a better way?

Thank you very much in advance!

**Comment by dsherret** [comment]
@InExtremaRes this should be possible to do and it is useful to do what you're doing. The problem is I think a general solution would be a lot of work to implement. For example, look at the function `typeToTypeNodeHelper` in [checker.ts](https://raw.githubusercontent.com/microsoft/TypeScript/master/src/compiler/checker.ts)... I believe most of that functionality would need to be re-implemented.

In this situation, you could try walking the type using `getExports()` on the result of `commandsNode.getType()` to try to build up the text yourself. It might be a lot of playing around to get it right though.

Btw, I think you can remove these two lines?

```ts
protocolDts.getImportDeclarations().forEach(x => x.remove());
protocolDts.getTypeAliasOrThrow('Commands').remove();
```

Also, sorry that I am not too much help on this ☹

**Comment by InExtremaRes** [comment]
Hi @dsherret and thank you very much for your answer. I've been out for a while but I'll continue this exploration a soon as possible, I will examine your suggestions in depth.

> Btw, I think you can remove these two lines?
> 
> ```ts
> protocolDts.getImportDeclarations().forEach(x => x.remove());
> protocolDts.getTypeAliasOrThrow('Commands').remove();
> ```

Their purpose was to delete those statements since the destination starts as a copy of the source file and none of them will be necessary if the type is written as I wish. Maybe there is a better way?

> Also, sorry that I am not too much help on this ☹

Don't worry, and thank you again for answering. Happy holidays!
