### ISSUE TITLE
Ignore `decorators` in @example of JSDoc

### ISSUE THREAD

**Issue by HamedFathi** [dsherret/ts-morph#762]
```ts
/**
 * Component that creates log event objects based on raw inputs sent to `ILogger`.
 *
 * To customize what data is sent to the sinks, replace the implementation for this interface with your own.
 *
 * @example
 *
 * ```ts
 * @singleton
 * export class MyLogEventFactory {
 *   public createLogEvent(logger: ILogger, logLevel: LogLevel, message: string, optionalParams: unknown[]): ILogEvent {
 *     return {
 *       logLevel,
 *       optionalParams,
 *       toString() {
 *         return `[${logger.scope.join('.')}] ${message} ${optionalParams.join(', ')}`;
 *       }
 *     };
 *   }
 * }
 *
 * container.register(Registration.singleton(ILogEventFactory, MyLogEventFactory));
 * ```
 */
export interface ILogEventFactory {
}

```

Is it possible to ignore decorators (`@singleton`) inside of an `@example` jsDoc tag?

Unfortunately, TS compiler detects `@singleton` as a new tag, 

![image](https://user-images.githubusercontent.com/8418700/69477454-c9b11700-0dfb-11ea-81ec-a058a079a0b5.png)

**Comment by dsherret** [comment]
I was just going to recommend opening an issue on the TypeScript rep, but looks like you already have! https://github.com/microsoft/TypeScript/issues/35310

I'm not sure it matters with or without the code block in the example.

**Comment by dsherret** [comment]
As noted [here](https://github.com/microsoft/TypeScript/issues/35310#issuecomment-558300254), it seems you will need to do `&#64;singleton`
