### ISSUE TITLE
install 6.0.2 error

### ISSUE THREAD

**Issue by xiaohulu** [dsherret/ts-morph#770]
**Describe the bug**

Version: 6.0.2

**To Reproduce**

I upgrage `ts-morph` to 6.0.2 in package.json, then run `npm i`, throw below errors:

```sh
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @ts-morph/common@~0.2.2.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'ts-morph'
npm ERR! notarget
```

**Expected behavior**

Should install success.

**Comment by dsherret** [comment]
My bad! I’ll fix it when I get home. Thanks for reporting!

**Comment by dsherret** [comment]
Ok, the 0.2.2 package is published now. That was my bad. My processes for doing releases is not great at the moment, but I'll fix it up eventually.

@xiaohulu once again, thank you very much for reporting!

**Comment by xiaohulu** [comment]
@dsherret Thanks, It works now!
