### ISSUE TITLE
findReferencesAsNodes return empty for  {id, name}: { id: number, name:string }

### ISSUE THREAD

**Issue by yantrab** [dsherret/ts-morph#772]
Hi, thank for your great job.

I trying to remove unused parameters :

```
for (const parameter of file.getDescendantsOfKind(SyntaxKind.Parameter)) {
            if (parameter.findReferencesAsNodes().length === 0) {
                parameter.remove();
            }
        }
```
But it is remove {id, name} parameters  from this:

```
    getParams({id, name}: { id: number, name:string }): { id: number; name: string; } {
        return new Promise((resolve) => {
            this.api.get('some/get/' + id + '/more/' + name + '').subscribe((data: any) => resolve(data));
        });
    }
```
should i need to use another check for this case?

**Comment by dsherret** [comment]
Yes, you'll need to check the individual elements' names in the object binding pattern.

So basically:

1. Check if the parameter name is an `ObjectBindingPattern` (`Node.isObjectBindingPattern`)...
2. If so then get the elements, then call `findReferencesAsNodes` on the name node of those elements.

Unfortunately there are no methods for manipulating an `ObjectBindingPattern` at the moment, but you should at least be able to check if all the elements are used. I just opened #775.
