### ISSUE TITLE
[Feature Request]: Add ImportDeclaration.removeNamedImport() method

### ISSUE THREAD

**Issue by gregjacobs** [dsherret/ts-morph#776]
Hey @dsherret, long time! Happy holidays!

I'm implementing a script where I'd like to "move" named imports from one `ImportDeclaration` to another in a source file, and I realized that it would be useful to have an `ImportDeclaration.removeNamedImport(name)` method.

Seems the only way to remove a particular named import at this time is to use `removeNamedImports()` in conjunction with `addImports()` to remove all and then re-add the ones that should remain.

Thoughts?

Best,
Greg

**Comment by gregjacobs** [comment]
Hmm, was just thinking through this a bit more. One weird scenario to consider:

- A named import which is repeated but has two different aliases: `import { A as A1, A as A2 }`

**Comment by dsherret** [comment]
Hey @gregjacobs! Thanks. Happy holidays to you too! 😊

One of the problems with this library is there are so many methods. For removing a named import, this functionality actually already exists. Just call: `namedImport.remove()` ([see here](https://github.com/dsherret/ts-morph/blob/6b6973d07e0455e4e8e7b4587ee90ea6c88ac684/packages/ts-morph/lib/ts-morph.d.ts#L6771)).

I actually don't know why I added a `removeNamedImports()` method, but perhaps it was for consistency with `removeDefaultImport()` because there doesn't exist a `remove()` method on identifiers.

**Comment by dsherret** [comment]
To make this less confusing, I could update the docs for `removeNamedImports()` to suggest using `remove()` on the import specifier.

**Comment by gregjacobs** [comment]
Ah I totally missed that `namedImport.remove()`! 

I feel like I've missed that in the past too, but it's been a while since I got to play with ts-morph so I forgot about it again, lol.

I guess from an API perspective, my thinking was that if I'm able to add new named imports via the parent node, it would seem to me that I could also remove named imports via the parent node. I didn't look any further than that :/ Does make sense though - one needs to target the particular named import they're looking for to be able to remove it. 

Just wanted to thank you again though for your excellent library! It's so useful to have these abstractions above the compiler API, while also being able to edit original source files in a way that maintains the original formatting/comments/etc. I've used ts-morph (and previously ts-simple-ast 😄) on 3 separate projects now and it's always come through!

**Comment by gregjacobs** [comment]
I think we can close this guy for now - pebkac :)

**Comment by dsherret** [comment]
Thanks @gregjacobs! I'm glad that it's continued to be useful for you :)

Also, sorry for my delay in replying. I've had my head down working on a new project. I finally got around to opening #780

**Comment by gregjacobs** [comment]
All good man, thanks so much! Good luck with the new project!
