### ISSUE TITLE
addConstructor throw error when class have an JSDOC at the end

### ISSUE THREAD

**Issue by paranoidjk** [dsherret/ts-morph#778]
**Describe the bug**

Version: latest

**To Reproduce**

```ts
const { Project, StructureKind } = require("ts-morph");

const project = new Project({});

const classFile = project.createSourceFile("src/MyClass.ts", `
class Foo {
/**
 * 
 */
}
`);
const classNode = classFile.getClasses()[0];
classNode.addConstructor({
  statements: "console.log('i am constructor');",
});
```
![image](https://user-images.githubusercontent.com/7971415/72313794-7b1b4d00-36c7-11ea-8792-6c0c54692f3e.png)

**Expected behavior**

no error

**Comment by dsherret** [comment]
Interesting. So what's happening here is that the code changes to something like this:

```ts
class Foo {
  /**
   * 
   */
  constructor() {
  }
}
```

...which means that the constructor takes ownership of the jsdoc. So previously the class had 1 jsdoc and now it also has 1 (the constructor).

Thanks for reporting and providing an easy reproduction! I'll add some special case handling for this scenario.

**Comment by dsherret** [comment]
For now, a workaround should be to just insert before the jsdoc using `classNode.insertConstructor`.

**Comment by lazarljubenovic** [comment]
I've gotta hijack this to tell you that I love how you explain the bug when you understand it, @dsherret! Keep up the great work maintaining the lib :)

**Comment by dsherret** [comment]
Thanks @lazarljubenovic! I have been taking a bit of a break from working on ts-morph, but I will get back to it very soon. I'll probably do a quick release to fix this bug over the weekend though.

**Comment by paranoidjk** [comment]
@dsherret Thanks for your work ❤️.  I want to know when there will be a new version released,  since i noticed that you fixed this bug in master,  but the default branch is latest.

**Comment by dsherret** [comment]
@paranoidjk sorry, I was waiting for the TS 3.8 release. I'll do a release this weekend 🙂
