### ISSUE TITLE
How to get type information of CallExpressions?

### ISSUE THREAD

**Issue by chaosite** [dsherret/ts-morph#78]
Let's say I have a bit of code like:

```typescript
import {MongoClient} from "mongodb";

var http = require('http');
var MongoClient : MongoClient = require('mongodb').MongoClient;
var url = "mongodb://localhost:27017/mydb";

MongoClient.connect(url, function(err, db) {
  if (err) throw err;
  var query = { address: "Park Lane 38" };
  db.collection("customers").find(query).toArray(function(err, result) {
    if (err) throw err;
    console.log(result);
    db.close();
  });
});
```

This isn't perfect TypeScript, but it's good enough for the compiler. I want to get the types of the various CallExpressions, so `db.collection("customers")`, `db.collection("customers").find(query)`, and so on. Also interesting are the types of the identifiers, like `db`.

How can I do this?

**Comment by dsherret** [comment]
Hi @chaosite, sorry for the long reply.

I've made this slightly easier to do in 0.65.0, but overall doing what you want is still a bit of a challenge. Overall, this part of the library hasn't been thought out as much and is more complicated to use.

First, I recommend using some TypeScript AST viewer (there's one in atom-typescript and another visual studio extension. I'll add more on this in #79.

From there, you probably will want to get all the call expression descendants:

```typescript
import * as ts from "typescript";
import Ast from "ts-simple-ast";

const ast = ...;
const sourceFile = ast.getSourceFile(...);
// generally, I want this library to be easy enough to use without having to use the type checker,
// but this scenario hasn't really been implemented yet
const typeChecker = ast.getTypeChecker();

// call expressions
for (const callExpression of sourceFile.getDescendantsOfKind(ts.SyntaxKind.CallExpression)) {
    // here's the part I'm unsure of... I haven't tested this code

    // try this
    const type = typeChecker.getTypeOfNode(callExpression);
    // or this
    const type = typeChecker.getTypeOfNode(callExpression.getExpression());
}

// identifiers
for (const identifier of sourceFile.getDescendantsOfKind(ts.SyntaxKind.Identifier)) {
    // i'm pretty sure this will work. I should add an identifier.getType() method.
    const type = typeChecker.getTypeOfNode(identifier);
}
```

Anyway, sorry it's not so great at the moment. Let me know how it goes and if this works or not. Thanks!

**Comment by dsherret** [comment]
I have made this easier in 0.66.0. You can use code similar to the following:

```typescript
import * as ts from "typescript";
import Ast from "ts-simple-ast";

const ast = ...;
const sourceFile = ast.getSourceFile(...);

// call expressions
for (const callExpression of sourceFile.getDescendantsOfKind(ts.SyntaxKind.CallExpression)) {
    const type = callExpression.getReturnType();
}

// identifiers
for (const identifier of sourceFile.getDescendantsOfKind(ts.SyntaxKind.Identifier)) {
    const type = identifier.getType();
}
```

View documentation on call expressions [here](https://dsherret.github.io/ts-simple-ast/details/expressions) and on identifiers [here](https://dsherret.github.io/ts-simple-ast/details/identifiers).

I'm going to close this issue, but please reopen it if this doesn't solve your problem.
