### ISSUE TITLE
Need more api to create a `ts.server.PluginCreateInfo`

### ISSUE THREAD

**Issue by heroboy** [dsherret/ts-morph#781]
```typescript
//this defined in  tsserverlibrary.d.ts
interface PluginCreateInfo {
        project: Project;
        languageService: LanguageService;
        languageServiceHost: LanguageServiceHost;
        serverHost: ServerHost;
        config: any;
}
```

**Is your feature request related to a problem? Please describe.**
I need a way to load my language service plugin.

**Describe the solution you'd like**
Provide apis to get all these `PluginCreateInfo` members.
Or I can custom load a plugin from a required module.

**Describe alternatives you've considered**
Maybe `project` and `serverHost` not exist. But at least `languageServiceHost` exists.

**Comment by dsherret** [comment]
Follow updates in #326. Basically, ts-morph is not designed to work with ts server and I'm not sure that it would ever be possible to get it to work. You can use the `createWrappedNode` api, but it is limiting: https://ts-morph.com/navigation/compiler-nodes#navigating-existing-compiler-nodes

**Comment by heroboy** [comment]
hi @dsherret , I agree with you. But as what I said above, at least expose the `languageServiceHost` is possible. I see the source code you create `serverHost` as a local variable. What about storing as a member, and providing a getter?

**Comment by dsherret** [comment]
I don't want to expose any of the hosts at this time. I wouldn't recommend using a ts-morph `Project` in a language service plugin.

**Comment by heroboy** [comment]
eh..... I'm not using this in plugin. But make an environment to load and create my plugin, and test it.
