### ISSUE TITLE
[Feature Request]: Node.getProject() method

### ISSUE THREAD

**Issue by gregjacobs** [dsherret/ts-morph#782]
Hey @dsherret. I've come across a couple of scenarios where it would be convenient to be able to retrieve the `Project` instance from a `SourceFile` (such as to grab other source files in the project based on the given `SourceFile`'s source).

I've been passing in both the `Project` and the `SourceFile` instances to functions that I write which need this ability, but figuring that having a `SourceFile.getProject()` method would be convenient (especially when one function calls another, and it ends up being a lot of functions that need both arguments). 

Since this feature could be handy on any `Node`, was thinking to put this new method on that class. The method could just return `this._context.project`?

Thoughts?

Best,
Greg

**Comment by dsherret** [comment]
Sure. Do you want to do a PR and add it to Node? It would be very easy to do as you pointed out. I think this method should throw if the node was created with the `createWrappedNode` function though. Otherwise I would get to it soon.

**Comment by gregjacobs** [comment]
Hey man, many apologies! I just realized that you commented on this issue way-back-when and I somehow missed it :X  I totally would have raised that PR! 

Thanks for adding the method though - will def help, and much appreciated!

**Comment by dsherret** [comment]
@gregjacobs that's no problem as it was simple to add! I'll release this over the weekend now that TS 3.8 is out.

**Comment by gregjacobs** [comment]
Sounds good :) Thanks!
