### ISSUE TITLE
Change Log?

### ISSUE THREAD

**Issue by angusmunro** [dsherret/ts-morph#783]
We are currently running version 3.1.3 and looking to evaluate an upgrade to 6.0.2.

Is there a changelog anywhere I can review of what has changed? 

https://github.com/dsherret/ts-morph/blob/HEAD/breaking-changes.md seems to return a 404 from the npm package page.

As does: https://github.com/dsherret/ts-morph/blob/HEAD/CHANGELOG.md

Thanks!

**Comment by dsherret** [comment]
Thanks for reporting! I will look into those dead links. Here are the correct ones:

* https://github.com/dsherret/ts-morph/blob/latest/packages/ts-morph/breaking-changes.md
* https://github.com/dsherret/ts-morph/blob/latest/packages/ts-morph/CHANGELOG.md

**Comment by angusmunro** [comment]
Thanks! It looks like upgrading will be a very good idea for us, given the bundle scripts improvements in V4
