### ISSUE TITLE
add function implementations for NewExpression nodes.

### ISSUE THREAD

**Issue by MaxKless** [dsherret/ts-morph#784]
Handling constructor calls is complicated right now. Implementations for e.g.` .remove()` or `.getArguments() ` would be tremendously helpful.

**Comment by dsherret** [comment]
@MaxKless could you show an example of what you mean and show an example? Right now for new expressions such as this...

```ts
new MyClass(arg1, arg2)
```

...it implements `ArgumentedNode` which has a `#getArguments()` method.

**Comment by MaxKless** [comment]
Hi @dsherret , thanks for the quick response. It seems like there were some problems with type inference on my part so I couldn't find the `ArgumentedNode` methods. Thanks for pointing that out. 
As for removing new expressions, I take it it's best practice to just replace the parent?

**Comment by dsherret** [comment]
@MaxKless I've also occassionally had that problem with the language service not showing those methods. It seems like it's gotten way better over the years though.

It depends on the context. For example, for a new expression like this...

```ts
new SomeClass();
```

...the parent expression statement could have `remove()` called on it. Let me know if you think of a scenario where the API could be better.

**Comment by MaxKless** [comment]
Thanks again for the help, I managed to get the types and relevant methods to show up.
