### ISSUE TITLE
Wrong NPM Package is currently published

### ISSUE THREAD

**Issue by quadband** [dsherret/ts-morph#786]
npm install ts-morph currently installs 1.3.5 which shows as published 17 hours ago. It's missing a lot of stuff. I lost part of my sanity this morning trying to figure out what was going on in my code.

**Comment by dsherret** [comment]
Jeez. I would have thought it would keep whatever is the highest published version number as the latest.

Sorry about that and thanks for letting me know! Will fix this right away.

**Comment by dsherret** [comment]
Fixed. Thanks so much once again for reporting!
