### ISSUE TITLE
The sourceFile getters are not retreiving all targeted objects from their sourceFile

### ISSUE THREAD

**Issue by pierregallard** [dsherret/ts-morph#788]
The sourceFile getters are not retrieving all targeted objects from their sourceFile: 
 - sourceFile.getFunctions() only retrieves some functions of the given sourceFile
 - sourceFile.getVariableDeclarations() only retrieves some variable declarations of the given sourceFile

Here is my testing script ( tsm.ts ):
```
import * as ts from "typescript";
import * as fs from "fs";
import * as tsm from "ts-morph";

function generateDocumentation(fileNames: string[],options: ts.CompilerOptions): void {
	const project = new tsm.Project();
	const checker = project.getTypeChecker();
	for (const fileName of fileNames){
		const sourceFile = project.addSourceFileAtPath(fileName);
		console.log("printing all functions of the given sourceFile:");
		sourceFile.getFunctions().forEach((f) => console.log("name: " + f.getName() + " - type: "+ f.getType().getText()));
		console.log("\nPrinting all variables of the given sourceFile");
		sourceFile.getVariableDeclarations().forEach((v) => console.log("name: " + v.getName() + " - type: "+ v.getType().getText() ));
	}
}

generateDocumentation(process.argv.slice(2), {
	target: ts.ScriptTarget.ES5,
	module: ts.ModuleKind.CommonJS
});

```

Here is the source code I use for my tests: test.ts

```
//Sourcecode test
// WS for Workspace
var WS = (function ($) {
    "use strict";
	/**
     * This is just a test-function
     * @param {boolean} bool
     * @return {string}
     */
	function functionTest(bool) {
		return "abc";
	}
	
    /* Variables */
    var var0 = [];
    var var1 = {},
        var2 = 0,
        var3 = '',
        var4 = null,
        var5;

	/**
     * This is just an anonymous test-function
     * @return {int}
     */
    var anonFunc0 = function () {
        return 42;
    }

    /** Retrieve UserGroups from the server, store them in the variable Grouptest.
	 * This is just an anonymous test-function with an AJAX style promise
     **/
    var anonFunc1 = function () {
        return new Promise(function (resolve, reject) {
            let DataObject = {
                "RequestType": "request",
                "Session_ID": SessionID
            };

            let successAjax = function (data) {
                data = data.d;             
                resolve(data);
            }

            ajax({
                url: "WebServices/Workspace_Ajax.asmx/WebMethodSimple",
                data: JSON.stringify(DataObject),
                origin: "anonFunc1"
            }).then(successAjax, reject);
        });
    };
	return {// This dictionnary contains is what is inside the WS object, so it contains references to public methods
		anonFunc0 : anonFunc0,
		anonFunc1 : anonFunc1,
	}
})(jQuery);
$(document).on("click", '#Button1', WS.anonFunc1);

const dateToString = d => `${d.getFullYear()}-${('00' + (d.getMonth() + 1)).slice(-2)}-${('00' + d.getDate()).slice(-2)}`;
const MonthToString = d => `${d.getFullYear()}-${('00' + (d.getMonth() + 1)).slice(-2)}`;

/**
 * This is just a test-function outide WS
 * @param {boolean} bool
 * @return {boolean}
 */
function func0(bool){
	console.log("DoSomething");
	return bool;
}

/**
 * This is just a test-function outide WS returning a promise
 */
function func1() {
    return new Promise(function (resolve) {
            console.log("DoSomething");
            resolve(true);
    });
}
```

To launch the script in cmd (windows 10), I use this command: 
```tsc tsm.ts --m commonjs && node tsm.js test.ts```

**Current output**
printing all functions of the given sourceFile:
name: func0 - type: typeof func0
name: func1 - type: typeof func1

Printing all variables of the given sourceFile
name: WS - type: ($: any) => void
name: dateToString - type: (d: any) => string
name: MonthToString - type: (d: any) => string

**Expected output**
Printing all functions of the given sourceFile:
[Every functions printed: at least functionTest, func0, func1 and maybe the anonymous function (I don't know about the anonymous functions, I didn't find anything about them in the documentation)]

Printing all variables of the given sourceFile
[Every variables printed : at least var0, var1, var2, var3, var4, var5 and maybe the anonymous function]

**Comment by dsherret** [comment]
I did not look at the output in detail, but it seems correct. Those methods will only get the child variable declarations and child source files (see the JSDoc comments for those methods).

If you want to get all the descendant function declarations then you could use a method like `#getDescendantsOfKind(SyntaxKind.FunctionDeclaration)`.

**Comment by dsherret** [comment]
Also, note that "anonymous functions" are actually function expressions and not function declarations. https://ts-ast-viewer.com/#code/G4QwTgBCB2D20DECu0DGBGCBeCAzFqALgJbwQAUAlBAN4BQAvgNxA

**Comment by pierregallard** [comment]
Thank you for the quick answer. 

I am actually making an automated-documentation tool for a big project I am working on. I had previously made a script in pure Typescript in order to recover every function and class declaration, but I decided to try out ts-morph for its `findReferences()` functionality (as this seems hard to implement without a specialized library). Is findReferences also limited to a particular context (only getting its results in the child source files)?

Also I want to parse JSDoc parameters whenever possible, if I understand [this](https://github.com/dsherret/ts-morph/issues/734#issuecomment-542377434) correctly, I will have to use  `getChildren` instead of `getDescendantsOfKind`, right ?

**Comment by pierregallard** [comment]
Also, what is the point of `getFunctions` and `getVariableDeclarations` being Source Files methods? Wouldn't it make more sense to have themas node methods, in order to not be restricted to the AST root ?

**Comment by dsherret** [comment]
> I am actually making an automated-documentation tool for a big project I am working on. I had previously made a script in pure Typescript in order to recover every function and class declaration, but I decided to try out ts-morph for its findReferences() functionality (as this seems hard to implement without a specialized library). Is findReferences also limited to a particular context (only getting its results in the child source files)?

`findReferences()` and `findReferencesAsNodes()` is just a wrapper around the LanguageService's `findReferences()` method. It will find all references within the "program" (so it should return all references and not be limited).

> Also I want to parse JSDoc parameters whenever possible, if I understand this correctly, I will have to use getChildren instead of getDescendantsOfKind, right ?

I think `getDescendantsOfKind` can be used to get JSDoc parameters. Open an issue if not as it would be good to change it to do that. Generally though you can get jsdoc information by having a node (say a `FunctionDeclaration`) then calling `#getJsDocs()` on it. From there, you can call `#getTags()` then filter by `Node.isJSDocParameterTag(tag)`.

> Also, what is the point of getFunctions and getVariableDeclarations being Source Files methods? Wouldn't it make more sense to have themas node methods, in order to not be restricted to the AST root ?

They're on any node that can have statements. So those methods also exist on `FunctionDeclaration`, `NamespaceDeclaration`, `MethodDeclaration`, etc. It's not on every node because not all nodes can have children that are functions, for example.

**Comment by pierregallard** [comment]
I've coded my script with `getChildren()` because I this part before you answered, but I will try to do it with getDescendantsOfKind in the future in order to test it out. Optimizations are not an important criteria in my project, but I will try to optimism it when it will be completed.

As you pointed out for the anonymous functions, I needed to look for FunctionExpression. But aiming directly for FunctionExpression gets yield much results: I only want to retrieve the function declarations for my documentation tool. Since I don't want to parse though every existing FunctionExpression, the trick I came up with is to only check for VariableDeclaration nodes and see if their **type.getText()** correspond to a function. Then I can recover their ExpressionNode child ofr the function signature: 

```
function visit(checker: tsm.TypeChecker, node: tsm.Node){
    
    (...)

    if (tsm.Node.isVariableDeclaration(node)) { //anonymous function are  function expressions found in variable declaration
        if (node.getType().getText()[0]=="("){ //the type of anonymous functions always starts with a parenthesis ex:"() => ..."
            console.log("Anonymous function name: " + node.getName() + "- type: "+ node.getType().getText());
            //searching for an eventual jsdoc style comment node:
	    let statement = node.getVariableStatementOrThrow();
	    if(statement.getJsDocs()[0]){
		console.log("JSDoc comment:" + statement.getJsDocs()[0].getDescription());
	    }
	    let functionExpressionNode = null;
	    node.getChildren().forEach((child) => {
	    if (tsm.Node.isFunctionExpression(child)){ //recovering the anonymous function node, there should always be only one
	        functionExpressionNode = child;
		let testsignature = checker.getSignatureFromNode(functionExpressionNode);

		(...)

	    }
	});
    }
}
```

However I realize that it might not be the best way to do it. Is there a property that may allow me to skip a handmade test on the type.getText() (`if (node.getType().getText()[0]=="(")`)?

Also, as I understand it, there is no special `getFunction()` that would look for FunctionExpression in VariableDeclaration nodes, right ? My simple child exploration loop does find the desired FunctionExpression from VariableDeclaration node so it's fine, but I was just wondering if I missed something.

**Comment by dsherret** [comment]
@pierregallard sorry for my delay. It will be slower to do that. You'll want to exclusively use the AST to be fast.

Something like:

```ts
if (Node.isVariableDeclaration(node)) {
    const initializer = node.getInitializer();
    if (initializer != null && (Node.isFunctionExpression(initializer) || Node.isArrowFunction(initializer))) {
        // use initializer here
    }
}
```

Also, see my answer here for another scenario: https://github.com/dsherret/ts-morph/issues/800#issuecomment-619630622
