### ISSUE TITLE
replaceWithText on node formats code

### ISSUE THREAD

**Issue by kukjevov** [dsherret/ts-morph#792]
**Describe the bug**

When i want to update text of node by replacing it using `replaceWithText` i expect it to do not automatically apply formatting. But now i cant apply custom format on node since it is changed right after calling `replaceWithText`.

Version: 7.0.0

**To Reproduce**

Argument of this block
```ts
@Component({
    selector: 'app',
    templateUrl: "app.component.html",
    styleUrls: ['app.component.scss'],
    changeDetection: ChangeDetectionStrategy.OnPush,
    animations: [routeAnimationTrigger]
})
```

is replaced by new text starting with new line.

```ts

{
    selector: 'app',
    templateUrl: "app.component.html",
    styleUrls: ['app.component.scss'],
    changeDetection: ChangeDetectionStrategy.OnPush,
    animations: [routeAnimationTrigger]
}
```

i expected

```ts
@Component(
{
    selector: 'app',
    templateUrl: "app.component.html",
    styleUrls: ['app.component.scss'],
    changeDetection: ChangeDetectionStrategy.OnPush,
    animations: [routeAnimationTrigger]
})
```

but i got

```ts
/**
 * Application entry component
 */
@Component(
    {
        selector: 'app',
        templateUrl: "app.component.html",
        styleUrls: ['app.component.scss'],
        changeDetection: ChangeDetectionStrategy.OnPush,
        animations: [routeAnimationTrigger]
    })
```

**Expected behavior**

**Comment by kukjevov** [comment]
Hmm after some more playing i have found out, that i have `CallExpression`, where i have `ObjectLiteralExpression` as first argument. Now when i log `getIndentationLevel` of this expression i got `1`. When i use `replaceWithText` with `CodeBlockWriter` and i log `getIndentationLevel` of this writer it is `0` even though it will perform indent. Why i cant change this indent of *parent* or how to do it.

**Comment by kukjevov** [comment]
As i see it, the problem is, that writer automatically gets default indent set to `0`, but in fact it is applied to as `1`, so it cant be changed to *real* `0` i tried to use `-1` value but that is not working.

**Comment by kukjevov** [comment]
It looks like it can be solved, but it needed little investigation

**Comment by BryceBarbara** [comment]
@kukjevov How did you fix it? I'm in the same situation.

![image](https://user-images.githubusercontent.com/24460210/123856632-2dec6480-d8d6-11eb-833d-ab207ce3c410.png)
