### ISSUE TITLE
Question: TypeArguments of baseTypes

### ISSUE THREAD

**Issue by khenidak** [dsherret/ts-morph#793]
First thank you for your awesome work!

I have a quick question. I would appreciate help
Let us say i have
``` typescript
interface i_base<t_base_1 extends int, t_base2 extends string>{}
interface i_sub<t_1 extends int, t_2 extends string, t_3 extends string>  
     extends i_base<t_1, t_2>{}
type concrete =  i_sub<0, 's1', 's2' >;
```
I would like to walk the inhiritance tree of `i_sub`, get `i_base` and get the value that was passed to it from `i_sub`

so far i have
```typescript
const ta = /* type alias*/.getTypeNode()
ta.getTypeName().getType().getBaseTypes();
```
I can walk the base types and i can find `i_base` however `getTypeArguments()` returns `t_base_1` and `t_base2` not `0` and `s1`.

is this possible? @dsherret

**Comment by dsherret** [comment]
@khenidak sorry for my extremely late reply. Yes, this is possible by looking at the type arguments on the type alias' type node's type:

```ts
import { Project } from "ts-morph";

const project = new Project({ useInMemoryFileSystem: true });
const sourceFile = project.createSourceFile("file.ts", `
interface i_base<t_base_1 extends int, t_base2 extends string>{}
interface i_sub<t_1 extends int, t_2 extends string, t_3 extends string>
     extends i_base<t_1, t_2>{}
type concrete =  i_sub<0, 's1', 's2' >;
`);

const concreteTypeAlias = sourceFile.getTypeAliasOrThrow("concrete");
const concreteTypeAliasTypeNode = concreteTypeAlias.getTypeNodeOrThrow();
const type = concreteTypeAliasTypeNode.getType();

// outputs
// 0
// "s1"
// "s2"
for (const typeArg of type.getTypeArguments())
  console.log(typeArg.getText(concreteTypeAliasTypeNode));
```

The base type will not have the type arguments provided to it.

Also, see here and click the type alias's type node and look at the "Type" area in the bottom corner: https://ts-ast-viewer.com/#code/JYOwLgpgTgZghgYwgAmAfQEZwM4QDxiY4RoCMyEAHpCACbargA0yhWuATBdRHQ9mCigA5gD4A3gF8AUKEixEKdNgCuGAmW416jMC0Jcq2-oJH60AZi28dAoSDHJk0p66M2G6dvkKlzHCRkwAE8ABxQEAHsQBCgISGQAXidlNTwABhYAcmxSLOzsDizkUQBuIA

**Comment by khenidak** [comment]
Thanks :-) and no need for apologies!
