### ISSUE TITLE
sourceFile.getFunctions should support commonjs style

### ISSUE THREAD

**Issue by atian25** [dsherret/ts-morph#800]
**Is your feature request related to a problem? Please describe.**

```js
// test.js
exports.sayHello = function(name) {};
```

```js
  const project = new Project();
  const [ sourceFile ] = project.addSourceFilesAtPaths(`test.js`);
  const functions = sourceFile.getFunctions();
  console.log(functions);
```

**Describe the solution you'd like**

current `getFunctions` only support ts export.

**Describe alternatives you've considered**

**Comment by dsherret** [comment]
Hey @atian25, right now `getFunctions()` only returns the function declarations. That is a function expression. See here: https://ts-ast-viewer.com/#code/KYDwDg9gTgLgzgOjgQwJ4AlgBssQAQC8eAZgK4B2AxjAJYTkAU5yAtsAJR4DeAvgNxA

You could get all the descendants that are function expressions by doing something like:

```ts
import { SyntaxKind } from "ts-morph";

const funcExpressions = sourceFile.getDescendantsOfKind(SyntaxKind.FunctionExpression);
```

But you will probably want to do something specific to the scenario (ex. looking at the binary expression, then seeing that the right hand side is a function expression).

**Comment by atian25** [comment]
yes, so I won't whether ts-morph will provide a sugar method to handler all the situation for users, so they don't need to write it each and each time.

**Comment by dsherret** [comment]
It's hard to know exactly what users might want per scenario. I'd recommend that users write their own helper in this scenario in order to get the function expressions they want.

Here's an example:

```ts
import { Node, StatementedNode, SyntaxKind } from "ts-morph";

// untested
function* getFunctionExpressionsInAssignments(node: StatementedNode) {
    for (const statement of node.getStatements()) {
        if (Node.isBinaryExpression(statement)) {
            const right = statement.getRight();
            if (statement.getOperatorToken().getKind() == SyntaxKind.EqualsToken && Node.isFunctionExpression(right))
                yield right;
        }
    }
}
```
