### ISSUE TITLE
How can I get node location(Line, column)?

### ISSUE THREAD

**Issue by susiwen8** [dsherret/ts-morph#801]
Hi , Great project you got here. I just want to know how can I get which line and column this node at original source file?

**Comment by dsherret** [comment]
Hey @susiwen8, it seems this currently only exists on the source file. On any node, do:

```ts
const lineAndColumn = node.getSourceFile().getLineAndColumnAtPos(node.getStart());
```

`getStart()` returns the first token pos within the node (excluding jsdocs... provide `getStart(true)` to get the start position with js docs)

**Comment by susiwen8** [comment]
@dsherret Thanks `getLineAndColumnAtPos` is exactly what I need.
