### ISSUE TITLE
fixUnusedIdentifiers() removes arrow function parameter

### ISSUE THREAD

**Issue by MaxKless** [dsherret/ts-morph#804]
**Description**

Version: 7.0.1

When I call fixUnusedIdentifiers() after making some changes to a file (that don't include the relevant arrow function), part of the arrow function argument is removed. 

**To Reproduce**

I wrote a short sample morph that demonstrates the buggy behaviour on the attached 'file.ts'

**morph**
```ts
import { Project, SyntaxKind, CallExpression, ts } from 'ts-morph';

console.log(ts.version); // 3.8.3

const project = new Project();
const sourcefile = project.getSourceFile('file.ts');
let logic = sourcefile
  .getClass('SampleEffects')
  .getProperty('brokenEffect$')
  .getInitializerIfKindOrThrow(SyntaxKind.CallExpression);
logic = updateOfType(logic);
sourcefile.fixUnusedIdentifiers();

project.save();

function updateOfType(pipe: CallExpression): CallExpression {
  pipe
    // get piped functions and their descendants
    .getDescendantsOfKind(SyntaxKind.CallExpression)
    .filter(exp => exp.getExpression().getText() === 'ofType')
    .forEach(exp => {
      exp.removeTypeArgument(exp.getFirstChildByKind(SyntaxKind.TypeReference));
    });
  return pipe;
}
```

**file.ts**
```ts
import { Actions, Effect, ofType } from '@ngrx/effects';
import { Store, Action } from '@ngrx/store';
import { toArray, withLatestFrom, map } from 'rxjs/operators';
import { of } from 'rxjs';

class Type implements Action {
  type: 'type';
}
export class SampleEffects {
  constructor(private actions$: Actions, private store: Store<{}>) {}

  @Effect()
  brokenEffect$ = this.actions$.pipe(
    ofType<Type>('type'),
    toArray(),
    withLatestFrom(of([{ num: 1 }])),
    map(([action, num]) =>
      action.reduce((acc, val) => {
        acc.push({ ...val, bug: num[0] });
        return acc;
      }, [])
    )
  );
}

```

**Expected behavior**

I expect the morph to only modify the ```ofType()``` function. Instead, the following code is generated:

```ts
import { Actions, Effect, ofType } from '@ngrx/effects';
import { toArray, withLatestFrom, map } from 'rxjs/operators';
import { of } from 'rxjs';

export class SampleEffects {
  constructor(private actions$: Actions) {}

  @Effect()
  brokenEffect$ = this.actions$.pipe(
    ofType('type'),
    toArray(),
    withLatestFrom(of([{ num: 1 }])),
    map(([action]) =>
      action.reduce((acc, val) => {
        acc.push({ ...val, bug: num[0] });
        return acc;
      }, [])
    )
  );
}

```

Note the missing ```num``` argument in the arrow function

**Comment by dsherret** [comment]
This uses the "unusedIdentifier_delete" quick fix in the compiler API. It seems this is failing because there are compile errors in that file after doing the `updateLogic`.

After doing the `updateLogic` method, try outputting the diagnostics:

```ts
console.log(project.formatDiagnosticsWithColorAndContext(project.getPreEmitDiagnostics()));
```

You'll see the following diagnostic:

```ts
src/test.ts:16:20 - error TS2698: Spread types may only be created from object types.

16         acc.push({ ...val, bug: num[0] });
```

So I think since that diagnostic is occurring on that line, TypeScript doesn't analyze the file properly and then thinks the `num` identifier is unused.

To get around this, just ensure there are no diagnostics in the source file before running `fixUnusedIdentifiers()`. It seems to work fine in that case.

I could report this as a bug in the TypeScript repo, but I'm pretty sure they will just tell me that all bets are off once there's a compile error in the file (as they have told me in the past).

**Comment by MaxKless** [comment]
Hi @dsherret, thanks for the super quick and thorough answer! It looks like the compile errors mess everything up. I'm going to try and ensure they're fixed before letting ```fixUnusedIdentifiers()``` run. The problem seems to be that the modified ```ofType()```  isn't typed correctly anymore and everything below relies on it for typing. 
Thanks again :)
