### ISSUE TITLE
[Question] What's the best way to sync with editor ?

### ISSUE THREAD

**Issue by GrandSchtroumpf** [dsherret/ts-morph#809]
Hello,
I'm building a vscode extension and I want to update the sourceFile object when user save its code.
Currently I do : 
```typescript
const path = sourceFile.getFilePath();
const text = fs.readFileSync(path).toString();
sourceFile.replaceWithText(text);
```
But it feels a little bit wrong to "just" to get the latest version of the code. I could find documentation about this.

**Comment by dsherret** [comment]
If you only want to refresh from the file system then there is a `sourceFile.refreshFromFileSystem()` method (and sync counterpart).

I’m not sure about vscode, but there’s probably a way to get the file text from the editor itself though. In that case you could just use the `replaceWithText` method once you have the text.

**Comment by GrandSchtroumpf** [comment]
Amazing, it works perfectly, thank you !

For future reader, in the end I used : 
```typescript
vscode.workspace.onDidSaveTextDocument(file => {
  sourceFile.replaceWithText(file.getText());
})
```
