### ISSUE TITLE
Non string Decorator Arguments 

### ISSUE THREAD

**Issue by GrandSchtroumpf** [dsherret/ts-morph#813]
**Is your feature request related to a problem? Please describe.**
I want to manipulate a decorator argument from Angular like that : 
```typescript
@Component({
  selector: 'my-app',
  templateUrl: 'path',
  styleUrl: 'path',
})
class MyClass {}
```
But once I do `getStructure()` on the ClassDeclaration I ends up with a string which cannot be parse : 
```
const [ config ] = structure.decorators[0].arguments; // "{\n selector: 'my-app',\n .... }"
JSON.parse(config); // error
```

**Describe the solution you'd like**
Instead of beeing a string, argument could be a structure or at least being easily parsed without string manipulations.

**Describe alternatives you've considered**
string manipulation with regex ... 😕

**Comment by dsherret** [comment]
I think this is #683. That said, do you need to use structures here? You can get everything you want from the AST rather than using the "structures":

```ts
const classDec = ...;
const args = classDec.getDecorators()[0].getArguments();
```

The structures are right now kind of "AST-lite", but will be improved more in #683 over time.

**Comment by GrandSchtroumpf** [comment]
Indeed this is a duplicate sorry.
Yes, I think I need to use structure here. I manipulate the structure on the frontend & send the result to the backend to do the transformation. A little bit like you suggest in the documentation about performance.

**Comment by dsherret** [comment]
@GrandSchtroumpf no trouble, it's good to know people need this and to know the use cases.

Ah, I see. Yeah, sorry nothing like that exists at the moment. #683 is a really big feature. I'm not sure if there's even a good way of doing this with the compiler api directly. You may just want to work with the wrapped AST in ts-morph at the moment on the front and backend if that's possible or perhaps build your own custom structure for that at the moment on top of ts-morph to help you do this. I'm not sure...

**Comment by GrandSchtroumpf** [comment]
Yes I guess I'll use the declaration to get the arguments and replace them in the structure before sending it to the frontend.
If you think of a solution that could be integrated in ts-morph let me know, I could try to make a PR.
