### ISSUE TITLE
[Question] How to modify a property of a type alias?

### ISSUE THREAD

**Issue by binoche9** [dsherret/ts-morph#815]
I would like to go through all types and interfaces and replace the property `member` if it exists. So I would like to change

    interface X {
        member: OldMember;
        otherStuff: ...
    }
    type Y = {
        member: OldMember;
        otherStuff: ...
    }

to

    interface X {
        member: NewMember;
        otherStuff: ...
    }
    type Y = {
        member: NewMember;
        otherStuff: ...
    }

For interfaces, I found I can do `i.getProperty('member').set({ type: "NewMember" })`, but I was struggling to find the equivalent functions for types. What am I missing?

**Comment by dsherret** [comment]
Running the code through ts-ast-viewer to see what the node kinds are may help: https://ts-ast-viewer.com/#code/JYOwLgpgTgZghgYwgAgBrIN4Chm+QWwnwCNoAuZAOQgHcBZI0qAbhzwHswALaAZTACuMGBQB04rAF8sYAJ4AHFAE1kAXkxtchEuSq0GOlpuSceUfkJHJxoqUA

```ts
import { Project, Node, TypeLiteralNode } from "ts-morph";

const project = new Project({ useInMemoryFileSystem: true });

const file = project.createSourceFile("file.ts", `interface X {
  member: OldMember;
  otherStuff: ...
}
type Y = {
  member: OldMember;
  otherStuff: ...
}`);

const interfaceDec = file.getInterfaceOrThrow("X");
const typeAlias = file.getTypeAliasOrThrow("Y");

interfaceDec.getProperty("member")?.setType("NewMember");
// I use an assertion here, but you may want to check Node.isTypeLiteralNode(typeNode)
(typeAlias.getTypeNodeOrThrow() as TypeLiteralNode).getProperty("member")?.setType("NewMember");

console.log(file.getFullText());
```

**Comment by binoche9** [comment]
I'm getting an error that `getProperty` doesn't exist on the type node - are you sure that the type casting is sound?

**Comment by dsherret** [comment]
@binoche9 yup. Type node or type **literal** node?

**Comment by binoche9** [comment]
file.getTypeAliases().forEach(t => {
        const node = t.getTypeNodeOrThrow() as TypeLiteralNode;
        console.log(node)
        const serviceMember = node.getProperty("services");
        if (serviceMember !== undefined) {
            serviceMember.setType(servicesSetName)
        }
    });

The error is telling me that `TypeError: node.getProperty is not a function`. 

When I print the `node` object it seems to tell me that it's a `TypeLiteralNode` so I'm a bit baffled.

**Comment by dsherret** [comment]
@binoche9 oh ok. So every result of `t.getTypeNodeOrThrow()` on a `TypeAliasDeclaration` will not necessarily be a `TypeLiteralNode`. For example:

```ts
type MyAlias = string; // this is a string keyword
type MyOtherAlias = /* this is a type literal node */ {
    test: number;
};
```

https://ts-ast-viewer.com/#code/C4TwDgpgBAsiCCAbAlgQwM5QLxXcATsgHYDmA3FAPSVTAAWymjUquBxJUA1hCAO4B7fABMAUKEiwQAeXoR8SNJhyUAVLQZNMrCdBTB5qRFCIDh0VTQDeoqHdoQ8ALhMBXALYAjeWVEBfMiA

What I posted only works if you know the type will be a type literal node.

You'll have to do something like this (what I mentioned with `Node.isTypeLiteralNode`:

```ts
import { Project, Node } from "ts-morph";

// ...etc...

file.getTypeAliases().forEach(t => {
    const typeNode = t.getTypeNodeOrThrow();
    if (Node.isTypeLiteralNode(typeNode)) {
        typeNode.getProperty("services")?.setType(servicesSetName);
    }
});
```

**Comment by binoche9** [comment]
Ah that did the trick. Thank you for walking me through it! Plus the amazing response time!

**Comment by dsherret** [comment]
No problem! Not much else to do right now haha 😄
