### ISSUE TITLE
.getReturnTypeNode() returns undefined

### ISSUE THREAD

**Issue by jorasso** [dsherret/ts-morph#821]
Hello, I think there is some kind of bug, or I use the API in the wrong way when I try to get a return type node of the method when its return type is not specified explicitly. 

Here is an example source code: 
```import { Project } from "ts-morph";

const project = new Project({ useInMemoryFileSystem: true });
const sourceFile = project.createSourceFile(
	"file.ts",
	`
	export class SomeObject {
		weight: number = 100;
	}
	export class Test {
		shouldReturnVoid(){}

		shouldReturnNumber () {
			return 10;
		}

		shouldReturnObjectOfClass () {
			return new SomeObject();
		}

                shouldReturnFunction () {
			return () => {
				new SomeObject();
			}
		}
	}`
);

console.log(
	sourceFile
		.getClass("Test")
		.getMethod("shouldReturnFunction")
		.getReturnTypeNode()
);
```

.getReturnTypeNode() returns undefined.

At the same time, I am able to get the type node in a similar situation using code like this with original compiler API:
```
var type = ts2csMain.typeChecker.getTypeAtLocation(declaration);
var typeNode = ts2csMain.typeChecker.typeToTypeNode(type);
```

Version: 7.1.0

**Comment by dsherret** [comment]
@jorasso I think what you're looking for is `getReturnType()`. That will return the type from the type checker. `getReturnTypeNode()` returns the node in the AST. In this case, there is no explicit `void` node so it returns undefined.

This is a point of confusion with the library and something I need to explain better when improving the docs.

**Comment by jorasso** [comment]
Thanks for such a quick reply! 

I updated the example a little bit. Do you think in such example typeChecker.typeToTypeNode(type) wouldn't be useful?

I have troubles to get all the information that I need just from getReturnType() (parameters the function take, and the return type of returned function).

**Comment by jorasso** [comment]
```var sf = project.createSourceFile(
	"temp_file" + uuid() + ".ts",
	"var tempVar: " + declaration.getType().getText() + ";"
);

var typeNode = sf.getVariableDeclaration("tempVar").getTypeNode();```

This is a workaround I used to get the info I need. Not beautiful for sure, but does the job for now.

BTW I noticed that after upgrading ts-morph it works a lot faster than before! Great work @dsherret !

**Comment by aleclarson** [comment]
`getReturnType` and `getParameters` should give you the information you need.

Type nodes only exist for explicit declarations, because the concept of a "node" is related to a text range in a source file.
