### ISSUE TITLE
Upgrade TypeScript version to 3.9.0

### ISSUE THREAD

**Issue by c3-kaviselvam** [dsherret/ts-morph#822]
**Is your feature request related to a problem? Please describe.**

Engineers at TypeScript (Microsoft) fixed this JS Doc [bug](https://github.com/microsoft/TypeScript/issues/36338) in their recent [version 3.9.0 release](https://github.com/microsoft/TypeScript/milestone/109). Would it be possible upgrade ts-morph's typescript dependency version to 3.9.0 ?

**Describe the solution you'd like**

Upgrade `typescript` version in package.json to 3.9.0

**Describe alternatives you've considered**

Our current alternative is to manually go through the .d.ts files that we're parsing and remove any problematic JS Doc syntax.

**Comment by dsherret** [comment]
It should be on 3.9.0 at the moment. See #816 and https://github.com/dsherret/ts-morph/blob/e769b7871982ca874684e20355d58f1153efdcda/packages/common/package.json#L25

Have you found it's not on that version?

**Comment by c3-kaviselvam** [comment]
I'm so sorry. It turns out that our team hadn't done an npm install recently to get the most recent version of ts-morph. After getting the latest version, I see ` "typescript": "~3.9.2" `. Again, I apologize for missing this detail (and the issue you mentioned) before opening this issue. I'll close it now. Thanks!

**Comment by dsherret** [comment]
@c3-kaviselvam no worries 🙂
