### ISSUE TITLE
[Question] Integration with `ts-patch`?

### ISSUE THREAD

**Issue by canonic-epicure** [dsherret/ts-morph#828]
Hello,

Am I correct, that currently `ts-morph` assumes a custom compilation process?

Is it possible to integrate `ts-morph` with `ts-patch` or `ttypescript`? The goal is a seamless enhancement of the TS compiler with the macros expansion abilities.

**Comment by dsherret** [comment]
No, it would be difficult to support the scenario as ts-morph does a lot of stuff internally around the compiler api. Probably using the `createWrappedNode` function is the closest to getting what you'd like: https://ts-morph.com/navigation/compiler-nodes#navigating-existing-compiler-nodes
