### ISSUE TITLE
Why aren't import references to a moved sourcefile not updated when they import the moved sourcefile absolutely?

### ISSUE THREAD

**Issue by the-leonat** [dsherret/ts-morph#829]
https://github.com/dsherret/ts-morph/blob/b8bbeb5410d0e7b7205fb4923d0e2f346147f368/packages/ts-morph/src/compiler/ast/module/SourceFile.ts#L984

in this line references are excluded from being updated which import the changed source file absolutely. im sure there is a reason to this. please let me know. 

my typescript project has module aliases set up and is using absolute imports intensively to improve code readability. i cant think of a problem which could arise when updating absolute imports.

**Comment by dsherret** [comment]
@the-leonat this may be a bug. I'll look into it soon. In the meantime, would you be able to provide input, expected output and actual output that demonstrates the incorrect behaviour?

**Comment by the-leonat** [comment]
thanks for your reply. i will try to provide some context:
my `ts.config` is setup using the paths parameter like e.g.
```
   "paths": {
      "@components/*": [
        "./components/*"
      ],
     ....
```
modules within the `./components` folder are then imported absolutely like `import ExampleComponent from "@components/ExampleComponent";`

i call `exampleFile.moveImmediatelySync(newFilePath);` and expect all modules which import something from `exampleFile` to update their imports respectively.

but only relative imports of `exampleFile` are updated. absolute imports are not touched at all.

it was at this point that I dove in the ts-morph code and discovered the above referenced line.
from that i realised that absolute imports are explicitly excluded. and i don't know why.

**Comment by the-leonat** [comment]
hej @dsherret . could you please provide some insight?

**Comment by dsherret** [comment]
Opened https://github.com/dsherret/ts-morph/issues/837
