### ISSUE TITLE
Json schema for Typescript AST?

### ISSUE THREAD

**Issue by TFTomSun** [dsherret/ts-morph#831]
Hello,
in the AST Viewer, I can see that the typescript syntax tree is shown as a data model. Is there a json schema available for that model? Can that data model based on a ts file be exported to json somehow?

**Comment by dsherret** [comment]
I don't know of any easy ways to do this. It might be useful for someone to create something that does this directly on the compiler API nodes.

It would probably have to use something similar to what I do on ts-ast-viewer.com and do some analysis to figure out what are the internal properties on nodes that should be ignored.
