### ISSUE TITLE
How to check fastly if a node is a function ?

### ISSUE THREAD

**Issue by geneseframework** [dsherret/ts-morph#833]
Hi,

I need to find all the AST nodes which have type "function" in a given project. For that, I check if the node is an Identifier and then I use 

```
node.getType().getApparentType().getText().match(/=>/);
```

The result is correct, but is incredibly slow to obtain. For a big project, I need more than 2 minutes to check all the AST nodes with this method.

I suppose that I can do that much more efficiently, but I don't know how.

Could you help me ?

Thanks

**Comment by geneseframework** [comment]
Hi !

Thanks for your answer. Unfortunately, when I try to use your code, I have an error : `Property getTyeNode does not exist on type 'Node'`, even if I know that this node is an Identifier.

For example, in the code `a.slice(1)`, I would like to return `function` for the AST node corresponding to the Identifier `slice`

**Comment by dsherret** [comment]
> For example, in the code a.slice(1), I would like to return function for the AST node corresponding to the Identifier slice

You'll need to use the type checker in that case. I don't think there's any way around it. You may want to use the regular TypeScript Compiler API for doing that to see if it's faster. Using `@ts-morph/bootstrap` might help with the setup: https://github.com/dsherret/ts-morph/tree/latest/packages/bootstrap

Side note: Using `Node.isTypeNode` checks for if a node has a `getTypeNode()` function.

**Comment by geneseframework** [comment]
Hi, and thanks again for your answer.
I found a little trick : the `Identifier` node corresponding to `slice` in `a.slice(1)` must have a grandparent which is a `CallExpression` and must be the second son of its parent. And that's all... No need to check its type.
This operation is really fast.
Thanks again for your help, and congratulations for your module : it is really excellent ! 👍
