### ISSUE TITLE
Interoperability with Typescript Compiler API

### ISSUE THREAD

**Issue by Christian24** [dsherret/ts-morph#834]
**Is your feature request related to a problem? Please describe.**

I am trying to write a plugin for dtsgenerator: https://github.com/horiuchi/dtsgenerator

It provides an API hook with a Typescript `SourceFile` parameter and you can return the Typescript's `SourceFile` after you mutated it to your liking. It would be cool to use ts-morph for the manipulation. It would be cool to add a `addSourceFileFromTSSourceFile` method to `Project` which takes Typescript's `SourceFile` type. Additionally, it would be great to have an `emitTS` on `Project` which would return an array of Typescript's `SourceFile`. I would guess as adoption of Typescript's compiler API grows, it would be cool to use `ts-morph` as a middleman to make more userfriendly.

**Describe the solution you'd like**

It would be cool to add a `addSourceFileFromTSSourceFile` method to `Project` which takes Typescript's `SourceFile` type. Additionally, it would be great to have an `emitTS` on `Project` which would return an array of Typescript's `SourceFile`.

**Describe alternatives you've considered**
An alternative would be to use https://ts-morph.com/setup/adding-source-files#by-string However, that would not work for emitting.

**Comment by dsherret** [comment]
I recommend using the TypeScript Compiler API directly if you're making a plugin for anything that uses the TypeScript Compiler API. ts-morph does too much under the hood and supporting these scenarios isn't viable for this project (this is mostly good for code generation and manipulating code using only ts-morph).
