### ISSUE TITLE
Add quotation marks around non-standard names for enums

### ISSUE THREAD

**Issue by jeswr** [dsherret/ts-morph#836]
**Is your feature request related to a problem? Please describe.**

I am using ts-morph to generate typescript code from files in anther domain. I am wanting to generate `enum`s for instances in the domain, however, some have names that cannot be used in `enum`s. This includes `this-type-of-name`, names that conflict with existing keywords such as `Function` and in some cases even the empty string ``.

**Describe the solution you'd like**

For `ts-morph` to add quotation marks around these values so that a valid typescript file is generated. For instance something like this would be generated:

```ts
enum example {
  okName = "value-related-to-okName",
  'name-like-this' = "value-related-to-name-like-this",
  'Function' = "value-related-to-Function'
}
```

**Describe alternatives you've considered**

Currently I am just adding quotation marks around all names that I am generating. It does mitigate this issue but is an inelegant solution and is something that I believe would be better handled within the `ts-morph` package.

**Comment by dsherret** [comment]
Seems reasonable.

Note for whoever implements this: https://stackoverflow.com/a/9337047/188246
