### ISSUE TITLE
Allow calling `Node.is***` functions undefined value

### ISSUE THREAD

**Issue by sisisin** [dsherret/ts-morph#842]
**Is your feature request related to a problem? Please describe.**

Sometime, TypeScript Compiler API returns `Node | undefined` value.
I want to check this Node kind with using `Node.is***` API, but I need to check undefined before call `Node.is***` function.

**Describe the solution you'd like**

Change [this function](https://github.com/dsherret/ts-morph/blob/latest/packages/ts-morph/src/compiler/ast/common/Node.ts#L2095-L2099) to following code

```diff
-    static is<TKind extends keyof KindToNodeMappings>(kind: TKind): (node: compiler.Node) => node is KindToNodeMappings[TKind] {
-        return (node: compiler.Node): node is KindToNodeMappings[TKind] => {
-            return node.getKind() == kind;
+    static is<TKind extends keyof KindToNodeMappings>(kind: TKind): (node: compiler.Node | undefined) => node is KindToNodeMappings[TKind] {
+        return (node: compiler.Node | undefined): node is KindToNodeMappings[TKind] => {
+            return node?.getKind() == kind;
        };
    }
```

**Comment by dsherret** [comment]
Thanks! This is a good idea.

If someone wants to work on this, the code for this is all code generated. The script that generates the code is found here: https://github.com/dsherret/ts-morph/blob/latest/packages/ts-morph/scripts/generation/createNodeTypeGuards.ts

After doing the change there, run `yarn code-generate`
