### ISSUE TITLE
Does ts-morph support modifying AST *before* type-checking?

### ISSUE THREAD

**Issue by m93a** [dsherret/ts-morph#843]
Hey!
I want to make a compiller that supports operator overloading in TypeScript – specifically I want to turn expressions `x + y` into `op_add(x, y)`. However, if I do it *after* type checking, TypeScript throws an error and fails to correctly infer the return type. I need to make this change right after the Parser and before the Binder. Does ts-morph support modifying the AST before the Binder runs? Thanks!

**Comment by dsherret** [comment]
@m93a yup, you can make changes to a bunch of files then do a full type checking pass by running `project.getPreEmitDiagnostics()`, then finally run `project.emit()`.

It won't be as fast as using the compiler api directly though.
