### ISSUE TITLE
Resolving to target type?

### ISSUE THREAD

**Issue by meandmax** [dsherret/ts-morph#846]
Is it possible to retrieve the target type of a type in ts-morph, that would be so amazing :)

```
interface B {
  b: string;
  c: string;
}

interface A {
  b: Omit<B, 'c'>;
}

wanted result:

interface A {
  b: { b: string };
}
```

**Comment by meandmax** [comment]
Which approach would you choose to resolve to the target object type if they are nested?

```
interface A {
    property: Pick<V, Omit<V, Pick<V, K>>>
}
```

**Comment by meandmax** [comment]
Any idea if tsc has functionality which I could use to resolve this to the result type?

**Comment by dsherret** [comment]
I believe the only way to do this is to get the type of `Pick<V, Omit<V, Pick<V, K>>>` (ex. `propertyDec.getType()`), then loop over all the properties using `getProperties()`.
