### ISSUE TITLE
Implement remaining js doc tags

### ISSUE THREAD

**Issue by dsherret** [dsherret/ts-morph#854]
* JSDocAuthorTag
* JSDocCallbackTag
* JSDocEnumTag
* JSDocImplementsTag

An example of how some of the other nodes were implemented is here: https://github.com/dsherret/ts-morph/pull/849/commits

This will close #854

**Comment by ilyaulyanov** [comment]
@dsherret  I've added the remaining tags following your example in my forked repo - will create a PR shortly.
