### ISSUE TITLE
When emitting js files, it should fail if there are compilation errors in the ts file.

### ISSUE THREAD

**Issue by jjtang1985** [dsherret/ts-morph#860]
**Describe the bug**

Version: 8.1.0

**To Reproduce**

```ts
import { Project, ts } from "ts-morph";

console.log(ts.version); // 4.0.2

  const p = new Project({ compilerOptions: { outDir: "dist", declaration: true } });
  p.createSourceFile("MyFile.ts", "consttt num = 1;");
  p.emit();
```

**Expected behavior**

Since there is a compilation issue of the `.ts` file (`consttt` should be `const`), I would expect an error message and/or some other mechanism so that I'm aware of the error.
However, current behaviour is that the `.js` files are still generated and I will never notice it until when I consume the generated files.

**Comment by dsherret** [comment]
Hey @jjtang1985, although that would be nice for some scenarios, checking the diagnostics takes time and some people might not want to do that when emitting.

Getting the diagnostics is a separate step in the compiler API and in ts-morph they can be checked for by using `p.getPreEmitDiagnostics()`. See [diagnostics](https://ts-morph.com/setup/diagnostics).
