### ISSUE TITLE
Question: Is it possible to manipulate block Node to add statements  ?

### ISSUE THREAD

**Issue by khunder** [dsherret/ts-morph#861]
I want to dynamically add statements inside an async arrow function inside a class;
I read the documentation and I didn't find anything that could help me, I was only able to get the block node where I want to insert my statements.
Is there any clean way to make it happen?

```typescript
  import {SyntaxKind, ArrowFunction, Block} from "ts-morph";
  //
  // .....
  // 
  let methodBody = `property = async(arg) => { }`;
  serviceClass.addMember(methodBody);
  let method = serviceClass.getMemberOrThrow(context.name);
  let arrowFunction =method.getDescendantsOfKind(SyntaxKind.ArrowFunction)[0];
  let block =arrowFunction.getDescendantsOfKind(SyntaxKind.Block)[0];
 ///
 /// block.addStatement('') ???
```

Thanks

**Comment by dsherret** [comment]
`arrowFunction.addStatements(...)` should work for arrow functions that have a block body. I've opened #862 as there is a bug here when it doesn't have a block.

By the way, a cleaner way to access the block node is:

```ts
const body = arrowFunction.getBody();
if (Node.isBlock(body)) {
    // use body here
}
```
