### ISSUE TITLE
KindToNodeMappings widens type to index signature and always has value type `Node`

### ISSUE THREAD

**Issue by gregjacobs** [dsherret/ts-morph#865]
Hey @dsherret,

I noticed this interface in ts-morph which prevents methods like `getParentIfKind()` and `getDescendantsOfKind()` from returning the correct node type:

```ts
export interface KindToNodeMappings extends ImplementedKindToNodeMappings {
    [kind: number]: compiler.Node;
}
```

This widens the entire `KindToNodeMappings` type to the index signature, and effectively invalidates all of the more-specific types in `ImplementedKindToNodeMappings` from which it inherits.

Was there a reason you did this? It makes it so that we always need to type assert which could be dangerous:

```ts
const importDecl = namedImport.getParentIfKind(SyntaxKind.ImportDeclaration);  
// importDecl is of type `Node` rather than `ImportDeclaration`

const importDecl = namedImport.getParentIfKind(SyntaxKind.ImportDeclaration) as ImportDeclaration;  
// importDecl type is now of type `ImportDeclaration` due to type assertion,
// but oops! It could also be `undefined`!
```

Version: 8.1.0

Thanks,
Greg

**Comment by dsherret** [comment]
Hey @gregjacobs, hope you're well! This works fine for me using TS 4.0.2 on the dev side and ts-morph 8.1.0:

![image](https://user-images.githubusercontent.com/1609021/93408812-782eb880-f863-11ea-9016-84cbf1e423eb.png)

Where are you getting `SyntaxKind` from? Is it from `import { SyntaxKind } from "ts-morph";` or via the `ts` export—`import { ts } from "ts-morph"; ts.SyntaxKind`? I am thinking perhaps its being imported some other way and the versions of TypeScript are no longer in sync.

**Comment by gregjacobs** [comment]
Hey @dsherret,

So this is super interesting! First of all, I corrected a misunderstanding of mine with index signatures in that I thought they widened the whole interface, but they actually only widen if the index access itself is dynamic:

```ts
interface MyStuff {
    couchColor?: 'red';
    [key: string]: string | undefined;
}
const myStuff: MyStuff = {};

myStuff['couchColor'] = 'blue';  // ERROR! Used the literal 'couchColor', and 'blue' not assignable to 'red' | undefined

let key: string = 'couchColor';
myStuff[key] = 'blue';  // okie dokie smokey! (sad face actually - totally dangerous)
```

Now, I tried to reproduce the issue I am having in my codebase and in a minimal example, I have no issues:

```ts
import { Project, SyntaxKind } from 'ts-morph';

const project = new Project();
const sourceFile = project.createSourceFile('tmp.ts', `
    const something = myFn();
`);

const callExprs = sourceFile.getDescendantsOfKind(SyntaxKind.CallExpression);
for (const callExpr of callExprs) {
    console.log(callExpr.getArguments());  // zero complaints - callExpr is in fact of type CallExpression
}
```

However, deep in my code, I have this snippet:

```ts
import { SyntaxKind } from 'ts-morph';

// ...

const jsxOpeningElParent = refNodeParent.getParentIfKindOrThrow(SyntaxKind.JsxElement);
jsxElements.push(jsxOpeningElParent);
```

but am ending up with this TypeScript error:

```
TSError: ⨯ Unable to compile TypeScript:
src/project/file.ts:220:38 - error TS2345: Argument of type 'Node<any>' is not assignable to parameter of type 'JsxElement | JsxSelfClosingElement'.
  Type 'Node<any>' is missing the following properties from type 'JsxSelfClosingElement': set, getStructure, getAttributes, getAttribute, and 7 more.

220                     jsxElements.push(jsxOpeningElParent);
                                         ~~~~~~~~~~~~~~~~~~

```

Most interestingly: vscode is reporting the type of `jsxOpeningElParent` as `JsxElement` on hover (would post a screenshot but my work computer won't let me 😭), but the CLI thinks it's of type `Node<any>`. I'm still not sure why exactly... 

Continuing to investigate! Thanks for the quick reply though!!

**Comment by gregjacobs** [comment]
Ok I have no idea why this might be, but the issue had something to do with `ts-node` (which we're using to run the script). I upgraded us from v8.5.4 to v9.0.0, and the error disappeared. Maybe it was as you said: an older version of TypeScript being executed somehow (although I would imagine it would have needed to be very old to not include JsxElement? Very weird!)

Thanks for your time as always though, and apologies on the non-issue!

**Comment by dsherret** [comment]
That’s no problem! Might be that ts-node was swapping out the typescript version used at runtime for some reason.
