### ISSUE TITLE
How to use this lib properly?

### ISSUE THREAD

**Issue by deepslam** [dsherret/ts-morph#866]
Hi guys!

At first, thank you for this amazing lib!
But I'm a bit misunderstood - how can I get classes from a source file?

I do the following:

```
      const project = await getProject();
      await project.addSourceFileAtPathIfExists(
        "./src/templates/NewFeature.ts"
      );
      project.getSourceFiles().forEach((sourceFile) => {
        const allChildren = sourceFile.getChildren();

        sourceFile.forEachChild((node) => {
          console.log("----");
          console.log(node.kind);
          console.log(node.getText());
        });
     });

```

The question is - how can I get the classes? (for example)
According to the doc, the should be a method getClasses but neither sourceFile not node don't include getClasses.
I suppose that I'm doing something wrongly.

Could you please help me?
Thank you!

--
Regards, Dmitry

**Comment by dsherret** [comment]
Hey @deepslam, there are two libraries here:

https://github.com/dsherret/ts-morph/tree/latest/packages/bootstrap
https://github.com/dsherret/ts-morph/tree/latest/packages/ts-morph

@ts-morph/bootstrap supports not blocking the event loop by using await, but that’s not in ts-morph yet. I think just remove await everywhere and it should work

**Comment by deepslam** [comment]
Hello!

Thank you for your reply.
I'm a bit confused cause I don't even find getClasses method (for example).
I've made grep in node_modules/ts-morph and node_modules/@ts-morph, and I have found no records with "getClasses".
But here https://ts-morph.com/navigation/ I can see that each node of forEachChild should have getClasses method.
What am I doing wrong?

**Comment by dsherret** [comment]
@deepslam strange. The `getClasses()` method should be in ts-morph.d.ts (see [here](https://github.com/dsherret/ts-morph/blob/9168b5320e1ede2d63c2d80e415553deba5d0785/packages/ts-morph/lib/ts-morph.d.ts#L7780)).

Copy and paste all this code into your editor and it should work:

```ts
import { Project } from "ts-morph";

const project = new Project();
const sourceFile = project.createSourceFile("test.ts", "class T {}");
const classes = sourceFile.getClasses();
console.log(classes.length);
```

1. Don't use `await` anywhere. That's [@ts-morph/bootstrap](https://github.com/dsherret/ts-morph/tree/latest/packages/bootstrap#example) and not [ts-morph](https://github.com/dsherret/ts-morph/tree/latest/packages/ts-morph#example).

**Comment by deepslam** [comment]
Ohh, shame on me, sorry.
I used createProject from @ts-morph/bootstrap and there I definitely don't see getClass.
Your code works.
Thanks, friend!

**Comment by dsherret** [comment]
@deepslam it's no problem! Sorry it's confusing. I need to think of a better way of managing this and it might be moving out the bootstrap project to a separate repo.
