### ISSUE TITLE
New expression without arguments parenthesis throws TypeError

### ISSUE THREAD

**Issue by ikeyan** [dsherret/ts-morph#867]
Calling `getArguments()` on an expression like `new Object` throws an exception.

Version: 8.1.0

**To Reproduce**

```ts
import { Project, ts } from "ts-morph";

console.log(ts.version); // 4.0.2

const project = new Project();
const sourceFile = project.createSourceFile("test.ts", `new Object;`);

// reproduce the problem here
// console.log(typeof sourceFile.getStatements()[0].getExpression().compilerNode.arguments); // undefined
sourceFile.getStatements()[0].getExpression().getArguments();
/*
Uncaught TypeError: Cannot read property 'map' of undefined
    at NewExpression.getArguments (node_modules/ts-morph/dist/ts-morph.js:2710:48)
*/
```

**Expected behavior**

`getArguments()` should return `undefined` as the underlying property does; or add `hasArguments()` to `NewExpression` and if it is true, `getArguments()` can throw an exception (with better error message).

**Comment by dsherret** [comment]
Thanks for reporting this @ikeyan! This is now fixed and published in 8.1.1

Honestly, I don't get why the TypeScript Compiler API doesn't just do an empty array here in its AST. Is there some differing behaviour between no parens and parens I don't know about?

Anyway, this didn't seem like something that people should have to worry about, so calling `getArguments()` will just return an empty array when there are no parens. Also, `insertArguments` and like methods will now not through. If someone wants to know if it has parens, they can expect the tokens or text of the node.
