### ISSUE TITLE
Manipulating decorators easily

### ISSUE THREAD

**Issue by GregOnNet** [dsherret/ts-morph#871]
## Thank you

Hi @dsherret, first I want to thank you for providing this library I have already used it before and it speeded up my work.

## Problem

Currently, I am facing the challenge that I want to read information out of a class and add this information to a decorator.

```ts
// Given ...
@Rule({
 // some settings
})
export class Entity {
  aString: string;
}

// What the manipulation should look like ...
@Rule({
  name: 'Entity',   // <- reading the class name and add it to the decorator
  types: {
    aString: String // <- reading public properties and add it to a dictionary inside the decorator
  }
})
export class Entity {
  aString: string;
}
```

The existing API for decorators seems not to be capable of updating decorator settings.
I was not able to add a property to the decorator where the value is an object.
Do I miss something here?

## Desired solution

Next to the operation `addArgument`, `removeArgument`, ... I would love to have a method `updateArgument`.

```ts
// class: ClassDeclaration
const decorator = clazz.getDecorator('Rule');
ruleSettings = decorator.getArguments()[0];
// ...convert argument values to an object, appending desired options
decorator.updateArgument(1, ruleSettings);
//                       ^--- first argument in decorator
```

## Alternatives

I read through the docs and did not find an alternative way to solve this problem.
If there is an existing way of manipulating decorators I would love to hear about it.

Cheers
Gregor

**Comment by ikeyan** [comment]
@GregOnNet You want to add `PropertyAssignment` into `ObjectLiteralExpression`.
You can see the actual tree here.
https://ts-ast-viewer.com/#code/AIJQrgNgpgFA3gKAAQDsCGBbKAuJAiAURQBcBLYgTzwQF8BKBKADwAcB7AJ2KQGMI0AzgKREylJIiRI0AZWIdSKAOa4B8xUoDctIA

Here's a working code to add `name` property assignment.
```typescript
import {ModuleKind, Node, Project, ScriptTarget, StructureKind, SyntaxKind} from "ts-morph";


const project = new Project({
    compilerOptions: {
        target: ScriptTarget.ES2019,
        module: ModuleKind.CommonJS,
        lib: ["ES2020", "DOM"],
        allowJs: true,
        alwaysStrict: true,
        experimentalDecorators: true,
    }
});
const rootFile = project.createSourceFile("./index.ts", `
@Rule()
export class Entity {
  aString: string;
}
`);
for (const classDeclaration of rootFile.getChildrenOfKind(SyntaxKind.ClassDeclaration)) {
    const decorator = classDeclaration.getDecorator("Rule");
    if (decorator) {
        // get the first argument or add one if absent
        const argument = decorator.getArguments()[0] ?? decorator.addArgument("{\n}");
        if (Node.isObjectLiteralExpression(argument)) {
            argument.addProperty({
                kind: StructureKind.PropertyAssignment,
                name: "name",
                initializer: JSON.stringify(classDeclaration.getName()),
            });
        }
    }
}
console.log(rootFile.getText());
```

**Comment by GregOnNet** [comment]
@ikeyan thank you very much for the quick response.
Thank you for providing the example as well. 🙏

I will try it out.
I also close the issue for now.
