### ISSUE TITLE
Best way to resolve a TypeReference

### ISSUE THREAD

**Issue by DerKorb** [dsherret/ts-morph#872]
lets say I have some code like this:
`
import {someType} from "someModule";
class A extends B<someType> {
    ...
}
`
Now I want to get the node for someType.
The best way I found so far is
- getClass("A")
- getDescendantsOfKind(SyntaxKind.TypeReference)
- get all imports from source file: ref.getSourceFile().getImportDeclarations()
- find the matching ImportDeclaration by comparing the named imports
- get the node from the matching import
Is there an easier way to get from the reference to the node?

**Comment by dsherret** [comment]
It depends what knowledge you already know about the file.

You could just do:

```ts
const someType = sourceFile.getFirstDescendantOrThrow(node => Node.isIdentifier(node)
    && node.getText() === "someType"));
```

There could be false matches for other type references that match and happen to use the same name though. There's also stuff like `const importDec = sourceFile.getImportDeclaration("someModule"); const someTypeNamedImport = importDec.getImports()[0];`.

**Comment by DerKorb** [comment]
I see, so no shortcuts. I wrote myself a helper now, that will resolve a TypeReference to a Node. Thanks for the answer.
