### ISSUE TITLE
getLeadingCommentRanges with class properties and decorators

### ISSUE THREAD

**Issue by MitchellMonaghan** [dsherret/ts-morph#873]
Given the class
```
export myClass {
  // myComment1
  // myComment2
  @Decorator1
  // myComment3
  @Decorator2
  // myComment4
  myProp: string;
}
```
Calling "getLeadingCommentRanges()" on the "myProp" node returns "myComment1" and "myComment2"
Calling "getLeadingCommentRanges()" on the "Decorator1" node returns "myComment1" and "myComment2"
Calling "getLeadingCommentRanges()" on the "Decorator2" node returns "myComment3"

"myComment4" seems to be inaccessible.

I might be wrong but isn't the intention to return the comments before each node? Calling "getLeadingCommentRanges()" on the "myProp" node should instead return the inaccessible "myComment4".

Thanks

I might be able to contribute on this issue.

**Comment by dsherret** [comment]
The leading comment ranges of the property declaration are what come before the decorators, so I believe this is correct behaviour. You should be able to get the leading property of the name node by calling `prop.getNameNode().getLeadingCommentRanges()`

**Comment by dsherret** [comment]
See here how the range of the property declaration includes the decorators:

![image](https://user-images.githubusercontent.com/1609021/94998360-53cf1d80-057f-11eb-966d-18728d35b331.png)

**Comment by MitchellMonaghan** [comment]
Yes your are correct thank you. Sorry new to using the typescript compiler and your npm package has been awsome.
Thanks for the help and very fast response.

**Comment by dsherret** [comment]
No problem and I'm glad the library has been useful! 🙂
