### ISSUE TITLE
[Question] using createSourceFile method 

### ISSUE THREAD

**Issue by panda0603** [dsherret/ts-morph#877]
Hello, I'm new to using typescript compiler api. 

What I basically want to do is get the types of the objects in MemberExpression and new expression. 

e.g., 

```
const a =[1,2,3];
a.includes(2); 
// for object instance a, I would want to get the type 'Array' when analyzing a.includes(2)
```

I've tried the following using the native typescript compiler api, like follows: 
```
let program = ts.createProgram(fileName, {});
let checker = program.getTypeChecker();

  for (const sourceFile of program.getSourceFiles()) {
    if (!sourceFile.isDeclarationFile) {
      ts.forEachChild(sourceFile, visit);
    }
  }

  function visit(node) {
    const nodeType = ts.SyntaxKind[node.kind];

    if (nodeType === 'PropertyAccessExpression') {
      let tsObject = checker.getTypeAtLocation(node.expression);
      const type = checker.typeToString(tsObject);
      console.log(type);
    }
 }
```
What would be the above equivalent using ts-morph?

From this, I have two questions. 

1. browsing the documentation for ts-morph, it does not seem to use createProgram, but createSourceFile. Can createSourceFile achieve the same functionality of getting the types as above or does ts-morph also support createProgram? I am not sure about the difference between the two. 

2. When using createSourceFile, the format is as below: 
```
project.createSourceFile(fileName, sourceCodeText); 
```
Do we always have to supply the path to the file AND the source code text of the file together? What is the one that actually gets analyzed? I am asking this because in createProgram, you can only put the path to the file which is convenient. What happens if the sourceCodeText parameter is different from the content of the file path provided? 

Thanks very much!

**Comment by dsherret** [comment]
@panda0603 there is a "Project" object that stores a collection of source files. This project object can be populated with source files using the methods outlined [here](https://ts-morph.com/setup/adding-source-files).

Similar code would be (though, using `forEachDescendant` instead of `forEachChild` because I believe the code above will not output anything since it will only go over the statements... I haven't testing anything though—just writing off the top of my head):

```ts
for (const sourceFile of project.getSourceFiles()) {
    if (sourceFile.isDeclarationFile()) continue;

    sourceFile.forEachDescendant(descendant => {
        if (Node.isPropertyAccessExpression(descendant)) {
            console.log(descendant.getType().getText()); // this uses the type checker internally
        }
    });
}
```

Note though, that you can also do stuff like:

```ts
import { Node, SyntaxKind } from "ts-morph";

for (const statement of sourceFile.getStatements()) {
    if (Node.isExpressionStatement(statement)) {
        // or use statement.getExpression() then check Node.isPropertyAccessExpression(expr)
        const expr = statement.getExpressionIfKind(SyntaxKind.PropertyAccessExpression);
        if (expr != null) {
            console.log(expr.getType().getText());
        }
    }
}
```
