### ISSUE TITLE
definition files not under rootDirs are excluded unexpectedly 

### ISSUE THREAD

**Issue by Zzzen** [dsherret/ts-morph#878]
**Describe the bug**

Version: 0.6.0

**To Reproduce**

1. `git clone https://github.com/Zzzen/morph-demo`
2. `node morph.js`

main files:

```ts
// tsconfig.json
{
  "compilerOptions": {
    /* Basic Options */
    "outDir": "build",
    "rootDirs": ["src"],                        /* List of root folders whose combined content represents the structure of the project at runtime. */
  },
  "include": ["types.d.ts", "src/*.ts"]
}


// types.d.ts
declare const SOME_GLOBAL_VAR: string;

// src/index.ts
const foo = SOME_GLOBAL_VAR;

// morph.js
const { createProject, ts } = require("@ts-morph/bootstrap");
main();
async function main() {
    const project = await createProject({ tsConfigFilePath: "tsconfig.json" });
    const diagnostics = ts.getPreEmitDiagnostics(project.createProgram());
    console.log(diagnostics);
}

```

**Expected behavior**

like how tsc compiles, there should be no diagnostics.

`typed.d.ts` is specified in `include` field of tsconfig. But it's discarded by [TsConfigResolver](https://github.com/dsherret/ts-morph/blob/b8bbeb5410d0e7b7205fb4923d0e2f346147f368/packages/common/src/tsconfig/TsConfigResolver.ts#L47) because it is not a child of any rootDirs.

**Comment by dsherret** [comment]
I think this just needs to take into account the files in "include" as well.
