### ISSUE TITLE
Create call expression

### ISSUE THREAD

**Issue by scherebedov** [dsherret/ts-morph#879]
Hello, I have created source file, how I can add to this source file call expression?
I want to get next file result:
```
exampleFunction('stingArgumentOne', function(){});
```
for example first argument is string, second is function;

Thanks!

**Comment by dsherret** [comment]
The expression level API is not so great at the moment. You can just do this though:

```ts
sourceFile.addStatements("exampleFunction('stingArgumentOne', function(){});");
```

Or using a writer in order to use the quote preferences:

```ts
sourceFile.addStatements(writer => {
    writer.write("exampleFunction(").quote("stringArgumentOne").write(", function(){});");
});
```
