### ISSUE TITLE
NameableNodeInternal#set({name}) does not rename refs

### ISSUE THREAD

**Issue by IKatsuba** [dsherret/ts-morph#882]
I see a test:
https://github.com/dsherret/ts-morph/blob/latest/packages/ts-morph/src/tests/compiler/ast/base/name/nameableNodeTests.ts#L177

So this is done on purpose.

But why? I expected different behavior

**Comment by dsherret** [comment]
Yeah, it's on purpose. The `set` methods don't ever use the language service.

Use `rename(newName)` to rename a node with the language service instead.
