### ISSUE TITLE
There is an option to get compiled class from class deceleration ?

### ISSUE THREAD

**Issue by yantrab** [dsherret/ts-morph#890]
Hi,
i combined real time code with ts-morth .

i need to get class prototype from class deceleration -

```
const project = new Project({ tsConfigFilePath: process.cwd() + "/tsconfig.json" });
const sourceFiles = project.getSourceFiles();
const allClasses: {[ name:string ]: ClassDeclaration}= {};

sourceFiles.forEach(s => {
  s.getClasses().forEach(c => {
    allClasses[c.getName() as string] = c;
  });
});

    if (nonNullableType.isClass()){
     //  here i want to get some real meta data of the class
      const classValidation = Reflect.getMetadata(symbols.validations, getClass(nonNullableType.getText()).prototype) || {};
      schema.properties = merge(schema.properties, classValidation);
    }
```

thanks a lot !

**Comment by dsherret** [comment]
@yantrab are you asking how to get the prototype type from the class type? I looked into it for 30 minutes and haven't figured it out yet, so I'm giving up for a little bit. Sorry! ☹ I'll take a look again soon.

**Comment by yantrab** [comment]
@dsherret  sorry for wasting your time, maybe it is not possible what i tried to do.

but i will glad if you take a look on what i did with your package , and what do you think about this.

https://github.com/yantrab/strongly

thanks !
