### ISSUE TITLE
Getting the type of a LiteralType property

### ISSUE THREAD

**Issue by CyriacBr** [dsherret/ts-morph#894]
Hi. I've been struggling with retrieving the types of a TypeLiteral properties.
Exemple with the following interface:
```ts
interface Test {
  foo: { a: number; b: string }
}

const _interface = file.getInterface('Test');
const prop = _interface.getProperties()[0];
const type = prop.getType(); 
type.isObject() // true;
const properties = type.getProperties();
const firstProp = properties[0].
firstProp.getName() //a;
// How to obtain the type here?
```

I tried `firstProp.getTypeAtLocation` and `firstProp.getDeclaredType` but they give `any`.
Any idea?

**Comment by dsherret** [comment]
Do you have any compile errors? What does `project.getPreEmitDiagnostics()` return?

You may just want to stay in the AST and then get the property type at the end. I think it would be something like (going from memory):

```ts
const propTypeNode = prop.getTypeNode() as TypeLiteral;
const firstProp = propTypeNode.getProperties()[0];
console.log(firstProp.getType().getText());
```

https://ts-ast-viewer.com/#code/JYOwLgpgTgZghgYwgAgCoQM5mQbwFDLIwD2xAXLsnBSAK4C2ARtANzKMVZSgDmyAvnn5A

**Comment by CyriacBr** [comment]
Hi, thanks for the reply. I did try `project.getPreEmitDiagnostics()` to see if there were any error and there were none.

About what you suggested, `getType`doesn't exist on `firstProp`, as it is a `Symbol`, not a `PropertySignature`. That seems to be the issue.
But that helped because I noticed thanks to the AST that I could actually access the `PropertySignature` from the Symbol's `valueDeclaration`.

So this works:
```ts
  const typeName = (firstProp.getValueDeclaration() as PropertySignature)
    .getType()
    .getText();
```

Thanks!
However, I wonder if it's intended that `getProperties()` from `TypeLiteral` returns `Symbol`s instead of `PropertySignature`s.

**Comment by dsherret** [comment]
It won't be a symbol if using `getTypeNode()` instead of `getType()` (see my previous code and how it's using `.getTypeNode()`).

`getType()` uses the type checker, but `getTypeNode()` gets the node in the AST. It probably makes sense in most scenarios to use `.getType()` though because it works even when something doesn't have an explicit type.

**Comment by CyriacBr** [comment]
Oh right, thanks for the clarification.
