### ISSUE TITLE
[Question] How to create a constant object literal expression?

### ISSUE THREAD

**Issue by ChristianIvicevic** [dsherret/ts-morph#895]
I came across the scenario where I wanted to dynamically create the following code:
```ts
export const Paths = {
  /* ... */
} as const;
```
Eventually I used the `Writers` functions which feel not idiomatic at all (refer to the line with the `initializer`):
```ts
outputSourceFile
    .addVariableStatement({
        declarationKind: VariableDeclarationKind.Const,
        isExported: true,
        declarations: [
            {
                name: 'Paths',
                initializer: Writers.assertion(Writers.object({}), 'const'),
            },
        ],
    })
```
Is there any better way to create an `ObjectLiteralExpression` combined with an `AsExpression` using `const`?

**Comment by dsherret** [comment]
Ah, yeah this is #683. No, right now the writers are the best solution.
