### ISSUE TITLE
[Question] How to create a type alias including typeof and keyof?

### ISSUE THREAD

**Issue by ChristianIvicevic** [dsherret/ts-morph#896]
Assume that there is an object as follows:
```ts
export const Paths = {
  PATH_1: 'path1',
  PATH_2: 'path2',
} as const;
```
Now I want to create the following type alias using ts-morph:
```ts
export type Paths = typeof Paths[keyof typeof Paths];
```
I did not find suitable code samples for such a complex case so I hardcoded it as follows:
```ts
outputSourceFile.addTypeAlias({
    name: 'Paths',
    isExported: true,
    type: `typeof Paths[keyof typeof Paths]`,
});
```
Is there any better approach for this complex type alias that doesn't need a hardcoded string?

**Comment by dsherret** [comment]
I think this would be #683.

A better approach may be to use a writer function if the scenario is very complicated, but in this scenario a hardcoded string is probably more appropriate.

```ts
outputSourceFile.addTypeAlias({
    name: 'Paths',
    isExported: true,
    type: writer => writer.write(`typeof Paths[keyof typeof Paths]`),
});
```
