### ISSUE TITLE
Issue getting comments from the top sourceFile

### ISSUE THREAD

**Issue by tinchoz49** [dsherret/ts-morph#898]
**Describe the bug**

Version: 9.1.0

Using `file.getStatementsWithComments` to read comments from the top sourceFile only works depending of the content.

If I have a single comment on top, it reads the statement ok, if a add a new function statement stop working.

**To Reproduce**

### Example 1 (working)

file: `test.js`
```js
/**
 * A module description
 * @author ...
 */
```

```js
import { Project, ts } from "ts-morph";

console.log(ts.version); // 4.1.2 <-- provide this

const project = new Project({
  compilerOptions: {
    noEmit: true,
    allowJs: true
  }
});

project.addSourceFilesAtPaths('**/*.js')
const file = project.getSourceFile('./test.js')

// reproduce the problem here
file.getStatementsWithComments()[0].getText() // "/**\n * A module description\n * @author ...\n */"
```

### Example 2 (failing)

file: `test.js`
```js
/**
 * A module description
 * @author ...
 */

function test () {}
```

```js
import { Project, ts } from "ts-morph";

console.log(ts.version); // 4.1.2 <-- provide this

const project = new Project({
  compilerOptions: {
    noEmit: true,
    allowJs: true
  }
});

project.addSourceFilesAtPaths('**/*.js')
const file = project.getSourceFile('./test.js')

// reproduce the problem here
file.getStatementsWithComments()[0].getText() // "function test () {}"
```

**Expected behavior**

It should work on both examples.

**Comment by dsherret** [comment]
This is expected. Once a comment becomes a js doc comment then it becomes owned by the node it describes and becomes a child of that node.

![image](https://user-images.githubusercontent.com/1609021/101705226-7d5f6600-3a54-11eb-915e-37ca245b412f.png)

**Comment by tinchoz49** [comment]
Ah thanks I didn't know that
