### ISSUE TITLE
Get all tagged template literals

### ISSUE THREAD

**Issue by lastmjs** [dsherret/ts-morph#899]
**Is your feature request related to a problem? Please describe.**

I'm new to the project, looking through the documentation, and I don't see any simple way to get all tagged template literals.

**Describe the solution you'd like**

For example, I'm trying to do some TypeScript type generation for GraphQL queries. The queries are scattered throughout the codebase, and look similar to this:

```typescript
const result = await graphql.query(gql`
  query {
    getUser(id: 1) {
      id
      name
    }
  }
`);
```
I want something like:

```typescript
sourceFile.getTaggedTemplateLiterals();
```

I could then loop through those, grab the ones named `gql`, grab the text, and then be off converting that text to a GraphQL AST to then create the TypeScript AST with the types for that specific query.

**Describe alternatives you've considered**

I might be able to get all template literals and go from there, but the documentation only describes `NoSubstitutionTemplateLiteral`...which might work because we generally do not interpolate our template literals, but it would be nice to have tool to just get the tagged template literals nonetheless.

**Comment by dsherret** [comment]
Hey @lastmjs, you should be able to use something like `sourceFile.getDescendantsOfKind(SyntaxKind.TaggedTemplateExpression)` or if you need more control use [`forEachDescendant`](https://ts-morph.com/navigation/#foreachdescendant) and check `if (Node.isTaggedTemplateExpression(node)) { .... }`.
