### ISSUE TITLE
make getTargetType return undefined if would return self

### ISSUE THREAD

**Issue by jasonkuhrt** [dsherret/ts-morph#904]
**Describe the bug**

Version: 9.1.0

**To Reproduce**

```ts
import dedent from 'dedent'
import * as tsm from 'ts-morph'
import { dumpType } from './utils'

const tsMorphProject = new tsm.Project({
  skipAddingFilesFromTsConfig: true,
  useInMemoryFileSystem: true,
})

tsMorphProject.createSourceFile(
  '/repro-example.ts',
  dedent`
    export interface Foo<T> {}
  `
)

tsMorphProject.addSourceFileAtPath('/repro-example.ts')

tsMorphProject.getSourceFiles().map((sf) => {
  sf.getExportedDeclarations().forEach((ex) => {
    const t = ex[0]!.getType()!
    dumpType(t)
  })
})
```

My log:

```
t.getText()                                          = import("/repro-example").Foo<T>
t.getSymbol()?.getName()                             = Foo
t.compilerType.getFlags()                            = 524288
(t.compilerType as tsm.ts.ObjectType)?.objectFlags   = 6
t.getAliasSymbol()?.getName()                        = undefined
t.getApparentType().getText()                        = import("/repro-example").Foo<T>
t.getSymbol()?.getDeclarations()?.[0]?.getKindName() = InterfaceDeclaration
t.getSymbol()?.getDeclarations()?.[0]?.getText()     = export interface Foo<T> {}

t.isAnonymous()                                      = false
t.isAny()                                            = false
t.isInterface()                                      = true
t.isObject()                                         = true
t.isArray()                                          = false
t.isBoolean()                                        = false
t.isBooleanLiteral()                                 = false
t.isClass()                                          = false
t.isClassOrInterface()                               = true
t.isEnum()                                           = false

t.getAliasTypeArguments().length}                    = 0
Boolean(t.getTargetType())                           = true
t.getTargetType() === t                              = true

t.getText(undefined, tsm.ts.TypeFormatFlags.InTypeAlias)                           = Foo<T>
t.getText(undefined, tsm.ts.TypeFormatFlags.UseAliasDefinedOutsideCurrentScope)    = Foo<T>
t.getText(undefined, tsm.ts.TypeFormatFlags.UseTypeOfFunction)                     = Foo<T>
t.getText(undefined, tsm.ts.TypeFormatFlags.UseFullyQualifiedType)                 = import("/repro-example").Foo<T>
t.getText(undefined, tsm.ts.TypeFormatFlags.NoTruncation)                          = Foo<T>
t.getText(undefined, tsm.ts.TypeFormatFlags.UseStructuralFallback)                 = Foo<T>

Target Type?
------------
N/A
```

Notice that I mark `Foo` has having no target type here (N/A) because the target type refers to self via reference equality.

 

**Expected behavior**

This looks like a bug to me. It seems that calling `getTargetType` in this case should return `undefined` (or maybe slightly better `null`). It seems to me that `getTargetType` should recursively return values until the terminal non-instantiated type-with-generics is reached.

**Comment by dsherret** [comment]
Hey @jasonkuhrt, I looked into this as it's been a while and it's expected behaviour. The compiler API seems to always reference itself on the `target` property for reference types:

![image](https://user-images.githubusercontent.com/1609021/102098195-e5b39c00-3df4-11eb-9b9f-5106191b0173.png)

https://ts-ast-viewer.com/#code/JYOwLgpgTgZghgYwgAgCoQM5gDyoHzIDeAUMmcgA5QD2FAXGgNzEC+xxANhGMmA+lmxYooAOZ5GQA

It will be `undefined` if it's not a reference type.

**Comment by jasonkuhrt** [comment]
Yeah figured. Calling this a bug is probably wrong. Rather a feature?

I'm thinking from TyDoc's use-case. It wants to traverse the target "chain" (can it be deeper than one level? Don't think so...). It feels like this would be the intent of most use-cases? Does it make sense to follow the tsc API here?

**Comment by dsherret** [comment]
At this point I'd rather just say aligned with the compiler API and don't want to do a breaking change for this. It's best if this works as similar to the compiler API as possible.

I don't think it can be deeper than one level either, so calling `getTargetType()` once should probably work out.

**Comment by jasonkuhrt** [comment]
Ok understood, maybe we can mention this on the docs or something. Would you be open for a PR for that?

**Comment by dsherret** [comment]
@jasonkuhrt sure! Yeah, on the JS doc just saying it will return itself if it's already the target type.
