### ISSUE TITLE
[Question]: How to create an arrow function and destructure arguments

### ISSUE THREAD

**Issue by yazfield** [dsherret/ts-morph#906]
Hi,

I'm writing a script to generate Typescript code using ts-morph, I was trying to generate an arrow function but couldn't find a way to do it. I checked the docs, issues and ts-morph code but didn't find something like `addFunction` for arrow functions.

I would appreciate if you could point me on how to achieve this 😅 

I was also trying to generate object destructuring  statement but had to partially do it with a string like this:
```javascript
// StatementStructures object
{
    kind: StructureKind.VariableStatement,
    declarationKind: VariableDeclarationKind.Const,
    declarations: [
      {
        kind: StructureKind.VariableDeclaration,
        initializer: (writer) => writer.write('fields'), // object to destructure
        name: '{ a, b }',
      },
    ],
  }
```

Is there a better way to achieve this? as you can see I'm doing it via the `name` property.

Thanks a lot. sorry for being greedy with the questions.

**Comment by dsherret** [comment]
@yazfield no problem asking questions and sorry for my delay!

I think using the name property here is best and I'm glad that works. Unfortunately there aren't any expression level structures at the moment (#683).
