### ISSUE TITLE
[Question]: How to get a function's type signature (and not "typeof myFunction")

### ISSUE THREAD

**Issue by stacey-gammon** [dsherret/ts-morph#907]
I'm using ts-morph to create API documentation, and I'm collecting type signatures. I have two functions defined like so:

```ts
export function aFunction(a: string): string {
  return 'hi';
}

export const bFun = (a: string) => { return 'hi'; }
```

I'm using `node.getType().getText()` to grab the signature. This works on the arrow function, but it doesn't on the FunctionDeclaration. Using the ast debugger I can see the information I want, but `node.getType().getText()` gives me `typeof aFunction`, which is not what I want.

<img width="903" alt="Screen Shot 2020-12-17 at 1 39 35 PM" src="https://user-images.githubusercontent.com/16563603/102529843-7943d180-406e-11eb-81c5-f8d2c0be02d5.png">

I'm assuming this information must be extractible somehow since you are displaying it in the ast viewer. 

Any ideas? :)

**Comment by misha** [comment]
I've been using this library for a project recently, and I was able to solve this issue.

`FunctionDeclaration` stores its parameters and return type separately. For example, the following code:

```ts
const source = project.createSourceFile('test.ts', `
  export function aFunction(a: string): string {
    return 'hi';
  }
`)

const aFunction = source.getFunctionOrThrow('aFunction')
console.log(aFunction.getParameters().map(parameter => parameter.getText()))
console.log(aFunction.getReturnType().getText())
```

Outputs:

```
[ 'a: string' ]
string
```

You can use these outputs to re-construct the functions type in any way you look, including an arrow function.

**Comment by dsherret** [comment]
Thanks @misha!

@stacey-gammon sorry for my delay! I think providing the context of `node` to `getText` will give the same type as is displayed on ts-ast-viewer—`node.getType().getText(node)`. That said, you might want to do something along the lines of what @misha recommended in order to get more fine grained information. What might be best is to use `functionDec.getSignature()` to get the signature from the type checker then call `getParameters()` and `getReturnType()` on that.

**Comment by stacey-gammon** [comment]
Great, thanks, passing node worked!

**Comment by stacey-gammon** [comment]
Actually, it didn't work. 🤦‍♀️  I was looking at the wrong test. `node.getType().getText(node)` still just returns `typeof TheFunction`.   However, I was able to make it look better using @misha's suggestion. Thanks!!
