### ISSUE TITLE
rename a class doesn't change in other files

### ISSUE THREAD

**Issue by jmls** [dsherret/ts-morph#908]
When renaming a class, I expected references to that class to be changed in the project

Version: 9.1.0

**To Reproduce**
/* foo.ts */
export class A {}
export class B {}

/* bar.ts */
import { A } from './foo';
import * as dto from './foo;

export class C {
   baz:A = {};
   zab:dto.B = {};
}

if I rename A and B to A1 and B1 then nothing gets changed in C

**Expected behavior**
I was expecting C to be changed. I'm sure that when I've renamed methods this has been changed throughout the project, so I don't know if I'm doing something wrong

**Comment by dsherret** [comment]
@jmls would you be able to show some example code that reproduces the problem? Are you using the `rename` method?

**Comment by jmls** [comment]
I found the problem ... whilst putting together a small example, a thought struct me - I was saving the modified file - but how do I save the other files that are automatically changed ? 

so I went on a little hunt, and found `project.save()` 

I'm really sorry for wasting your time - thanks for the great project.

**Comment by dsherret** [comment]
No problem! You didn't waste my time :)

Yeah, `project.save()` is what to use. Glad you found the issue!
