### ISSUE TITLE
[Question] How to get the default value from a jsdoc parameter tag?

### ISSUE THREAD

**Issue by tinchoz49** [dsherret/ts-morph#911]
Hi @dsherret,

Is there a way to get the default value from a jsdoc parameter tag?

```javascript
/**
 * @param {string} [p1="test"] - An optional param with a default value
 */
function stringsStringStrings(p1) {
  // TODO
}
```

**Comment by dsherret** [comment]
Unfortunately I don't think so. It seems like the compiler API doesn't show this information:

https://ts-ast-viewer.com/#code/PQKhCgAIUgBAHAhgJ0QW0gbwM4BdkCWAdgOYC+kA2vAIwC8ARLgKZ4MC6kAtJAIJGQA9vFwFBRRABtISVBgDuBXAAtIiSABNmAM0QBXSbkgA3KXuZQQwcNr1EAxqPGQ8hUtgDK+YiS9uS2AAUtACUWFCQwMCQACoA8gAiceBkQA

1. Click the link above.
2. Go to Options and check "Show internals"
3. Click on the `FunctionDeclaration` in the middle column.
4. Inspect the `jsDoc` property in the right column... I don't see anything there that would get this.
