### ISSUE TITLE
How to check if property is get accessor ?

### ISSUE THREAD

**Issue by yantrab** [dsherret/ts-morph#913]
```
type.getProperties().forEach(prop => {
      if (prop.isGetter) return;
}
```

thanks!

**Comment by dsherret** [comment]
I don't know if the type checker makes this distinction. I think you have to go back to the declaration and check if it's a get accessor:

```ts
// something along these lines... I didn't test this
Node.isGetAccessor(prop.getDeclarations()[0])
```

**Comment by Gerrit0** [comment]
You can get this from the `symbol.flags` property:

```ts
checker.getPropertiesOfType(type).map(s => [s.name, !!(s.flags & ts.SymbolFlags.Accessor)])
```

**Comment by dsherret** [comment]
oh yeah, I missed that! Thanks @Gerrit0!

![image](https://user-images.githubusercontent.com/1609021/103370338-8e6f2600-4a9a-11eb-9a33-e2eb9f8993cc.png)

**Comment by yantrab** [comment]
work like a charm! thanks .
