### ISSUE TITLE
How to get enum declaration from type

### ISSUE THREAD

**Issue by yantrab** [dsherret/ts-morph#914]
Hi, i see that i can get the enum members - 
`const members = enumDeclaration.getMembers();`

but i have the type, how can i get the type declaration to get the members?
```
export enum Role {
  admin = "admin",
  user = "user"
}

export class User  {
  role: Role;
}
```

i looping other user properties and build my ajv scheme -

```
export const getParamSchema = (type: Type) => {
  if (type.isEnumLiteral()) {
    schema.type = "string";
    schema.enum = [];// here i want to add the enum members..
  }
}
```

thanks.

**Comment by dsherret** [comment]
I didn't test it, but I think an enum type is a union, so you should be able to use `type.getUnionTypes()`. Let me know if that doesn't work!

**Comment by yantrab** [comment]
thanks but it is not work for me , return empty array .
i solved it by 
```
    schema.enum = (prop as any)
      .getValueDeclarationOrThrow()
      .getSourceFile()
      .getEnum(e => e.getName() === nonNullableType.getText())
      .getMembers()
      .map(m => m.getName());
    return schema;
```

**Comment by dsherret** [comment]
Hmmm weird. I just tried it and it works for me. There are some missing helper functions that should probably be added though and I've opened #916.

I think that solution there won't work when the declaration is not exported from the file. I think you should just be able to do `(enumType.getDeclarations()[0] as EnumDeclaration).getMembers()`

**Comment by yantrab** [comment]
yes, you are right , it is work only for exported enaum. so this is what i need to do to get enum values?:
```
  if (nonNullableType.isEnum()) {
    schema.type = "string";
    schema.enum = nonNullableType.getUnionTypes().map(t => last(t.getText().split(".")) as string);
    return schema;
  }
```

**Comment by dsherret** [comment]
@yantrab now that #916 is implemented you should be able to do:

```ts
nonNullableType.getUnionTypes().map(t => t.getLiteralValueOrThrow() as string)
```

**Comment by fasiha** [comment]
@dsherret forgive me for potentially hijacking this question, I feel like it's very similar to my question. Happy to open a new issue if that's better! 

My question: is there a way to *add* enum or union members? I have the following:
```ts
import { Project, Node as TypeGuards } from 'ts-morph';
var project = new Project();
var sourceFile = project.createSourceFile(
  'file.ts',
  `const c = 'ccc';
  export type Foo = 'a'|'b'|typeof c;
  `,
);
var al = sourceFile.getTypeAliasOrThrow('Foo');
var ty = al.getType();
console.log(ty.getUnionTypes().map(t=>t.getLiteralValueOrThrow()))
```
and I can see the literal values of my union type `Foo`. Great. Now, what's the way for me to add a new element to the union `'d'` say?

(I see that object expressions have `addPropertyAssignment` for example, and wondering if there's an equivalent for unions?)
