### ISSUE TITLE
add parameter to super

### ISSUE THREAD

**Issue by jmls** [dsherret/ts-morph#915]
how would one go about adding a parameter to the `super` statement in a class ?

I can get the super (SuperExpression) with 

```
const superStatement = constructorDef.getFirstDescendantByKind(
                        SyntaxKind.SuperKeyword
                    );
```
but now I'm kind of stuck what to do next .. 

I have a number of classes that I'd rather not have to modify manually (replacing debug with a logger) 
and I've managed to get the debug imports / statements removed and changed, added the import statements 
for the logger and added the logger to the constructor of all classes.

This super transformation is the very last step !

**Comment by dsherret** [comment]
A `super` keyword is found in a call expression.

![image](https://user-images.githubusercontent.com/1609021/103369732-e60c9200-4a98-11eb-958f-3b66b5228c98.png)

https://ts-ast-viewer.com/#code/MYGwhgzhAEBCkFNoG8BQ0PWAewHYQBcAnAV2AOyIApcSBbALmlroCMEiBKFAX1T9ShIMACoJC0BAA8CCXABMY8CEjSYseQqXKUq3NeswQSABw5UArJwDc6THx5A

You should be able to do:

```ts
const superKeyword = constructorDef.getFirstDescendantByKind(SyntaxKind.SuperKeyword);
const callExpr = superKeyword.getParentIfKindOrThrow(SyntaxKind.CallExpression);
callExpr.addArgument("test");
```

Though, that would throw an error for expressions like `super.test(5)`. You may want to instead go through `constructorDef.getStatements()` and find the call expression within an expression statement that has an expression that's a super keyword.

**Comment by jmls** [comment]
thanks. that works for me
