### ISSUE TITLE
make it available for Deno

### ISSUE THREAD

**Issue by hemedani** [dsherret/ts-morph#921]
**Describe the solution you'd like**
Just make work this awesome lib for Deno

**Comment by dsherret** [comment]
It would be great. ts-morph was actually previously used in Deno's build system when it was still on npm.

ts-morph doesn't have too many dependencies, so I don't believe this would be too hard. I think probably the easiest solution here would be to build [`code-block-writer`](https://github.com/dsherret/code-block-writer) for Deno (has no dependencies), then bundle `ts-morph` and `@ts-morph/common` into a single file, then implement https://github.com/dsherret/ts-morph/blob/latest/packages/common/src/fileSystem/RealFileSystemHost.ts for Deno.

**Comment by dsherret** [comment]
Opened https://github.com/dsherret/code-block-writer/issues/36

**Comment by dsherret** [comment]
One part about this was figuring out how to bundle the .d.ts files (aka lib files) for Deno. https://github.com/dsherret/ts-morph/pull/934 should solve this, but I think for Deno it will have to remove the "require" and always load the lib files module in `getLibFiles()` (https://github.com/dsherret/ts-morph/blob/3dd5c72a48a7a5852cf5f995126b8cc12567ee86/packages/common/src/getLibFiles.ts#L2).

**Comment by dsherret** [comment]
**ts-morph/common dependencies**
- [x] TypeScript - Now bundled in ts-morph/common
- [ ] is-negated-glob - Rewrite and include in ts-morph/common
- [ ] dsherret/to-absolute-glob - Need to rewrite and include in ts-morph/common
- [x] mkdirp - Deno has a `ensureDir` at https://deno.land/std@0.72.0/fs/README.md
- [x] fast-glob - See `expandGlob` https://deno.land/std@0.77.0/fs
- [x] multimatch - Available from Deno https://deno.land/std@0.79.0/path/glob.ts

**ts-morph dependencies**
- [x] code-block-writer - Available for Deno https://github.com/dsherret/code-block-writer

**Comment by dsherret** [comment]
@hemedani this is now available here: https://deno.land/x/ts_morph@10.0.1

Note that I haven't developed a way to run the tests for the Deno module yet, so it might be a little bit unstable. I started using it in some of my Deno code in a different repo and seems to work well so far...

**Comment by hemedani** [comment]
awesome
