### ISSUE TITLE
[Question] `node.getType().getText()` vs `node.getType().getText(node)`

### ISSUE THREAD

**Issue by stacey-gammon** [dsherret/ts-morph#923]
This is somewhat related to my question here: https://github.com/dsherret/ts-morph/issues/907

I'm relying on the import paths inside the returned string from `node.getType().getText()` to build reference links in an API doc system. `node.getType().getText(node)` always strips these import paths, but sometimes it returns better information than when not supplying the node.

Is there any way to get both the more complete information, but keep the import paths?  I made a table of these differences here:

<img width="1482" alt="Screen Shot 2021-01-27 at 1 09 03 PM" src="https://user-images.githubusercontent.com/16563603/106034659-2dd70700-60a1-11eb-9f2c-0b3fa81ae8e8.png">

There are some pretty interesting results. Notice how `KindOfADup` actually returns a reference to `Foo` because their types overlap, though they are defined separately.

Link to [codesandbox](https://codesandbox.io/s/still-resonance-9idq4?file=/src/App.tsx)

**Comment by dsherret** [comment]
Probably to get more complete information you could inspect the `Type` objects themselves then once having a type reference, maybe looking at `.getSymbol()` and then following the symbols to the declaration (using `Symbol#getAliasedSymbol()` might help you travel). It will be a bit of code to write though.

> Notice how KindOfADup actually returns a reference to Foo because their types overlap, though they are defined separately.

Yeah, it's annoying and unfortunate that the ts compiler does this ☹. See here: https://github.com/microsoft/TypeScript/issues/28197
