### ISSUE TITLE
Type union `ExportedDeclarations` is missing types `SourceFile` and `NamespaceExport`

### ISSUE THREAD

**Issue by velut** [dsherret/ts-morph#926]
**Describe the bug**

Type union `ExportedDeclarations` is missing types `SourceFile` and `NamespaceExport`.

Version: 9.1.0
Typescript version: 4.1.3

**To Reproduce**

To get a `SourceFile` as an exported declaration, we have to first [import a module into a single variable](https://www.typescriptlang.org/docs/handbook/modules.html#import-the-entire-module-into-a-single-variable-and-use-it-to-access-the-module-exports) using the `import * as foo` form and then we re-export that variable using `export { foo }`.

```ts
import { ExportedDeclarations, Project, ts } from 'ts-morph';

// Logs `4.1.3`
console.log(ts.version);

const project = new Project();

// Create ambient file `foo.d.ts`, contents have no importance
project.createSourceFile('foo.d.ts', `export const x: string;`);

// Create ambient file `index.d.ts`, which re-exports module `foo.d.ts`
// after namespacing it under the variable `foo`
const indexFile = project.createSourceFile(
    'index.d.ts',
    `import * as foo from './foo';
     export { foo };`
);

// `fooModule` is a `SourceFile`,
// which is missing from the `ExportedDeclarations` type union
const fooModule: ExportedDeclarations = indexFile
    .getExportedDeclarations()
    .get('foo')![0];

// Logs `SourceFile`
console.log(fooModule.getKindName());
```

To get a `NamespaceExport`, we use the [shorthand form](https://www.typescriptlang.org/docs/handbook/modules.html#export-all-as-x) `export * as foo` equivalent to the form `import * as foo; export { foo }` used previously.

```ts
import { ExportedDeclarations, Project, ts } from 'ts-morph';

// Logs `4.1.3`
console.log(ts.version);

const project = new Project();

// Create ambient file `foo.d.ts`, contents have no importance
project.createSourceFile('foo.d.ts', `export const x: string;`);

// Create ambient file `index.d.ts`, which re-exports module `foo.d.ts`
// after namespacing it under the variable `foo` using the shorthand form
const indexFile = project.createSourceFile(
    'index.d.ts',
    `export * as foo from './foo';`
);

// `fooModule` is a `NamespaceExport`,
// which is missing from the `ExportedDeclarations` type union
const fooModule: ExportedDeclarations = indexFile
    .getExportedDeclarations()
    .get('foo')![0];

// Logs `NamespaceExport`
console.log(fooModule.getKindName());
```

**Expected behavior**

`SourceFile` and `NamespaceExport` should be added to the `ExportedDeclarations` type union.

Thank you again for your time and this awesome library!

**Comment by dsherret** [comment]
Thanks @velut! I'll release this one on February 23rd with the new TS 4.2 release.

The fix here was to add only `SourceFile` to the type alias and to follow `NamespaceExport`s along to the exported source file.
