### ISSUE TITLE
skipAddingFilesFromTsConfig not exists

### ISSUE THREAD

**Issue by gillesfabre34** [dsherret/ts-morph#930]
Hi,

In your documentation ([https://ts-morph.com/setup/](https://ts-morph.com/setup/)), you talk about the option `skipAddingFilesFromTsConfig` which seems to not exist. Maybe was it renamed in `skipFileDependencyResolution` ?

Thanks
Gilles

**Comment by dsherret** [comment]
Hey @gillesfabre34, what version are you using? It should exist https://github.com/dsherret/ts-morph/blob/b9769c2a61b74894de5aaf90fdba4042ddca0854/packages/ts-morph/lib/ts-morph.d.ts#L717

**Comment by gillesfabre34** [comment]
Hi,

you are right ! :) 
I used the version 8.1.2

Thanks for your quick reply, and sorry for the disturbance caused.

Congratulations for this library, it saves my life every day !!!

Gilles
