### ISSUE TITLE
@ts-morph/common has typescript as dependencies instead of devDependencies

### ISSUE THREAD

**Issue by mercuriete** [dsherret/ts-morph#931]
Acording to this line:
https://github.com/dsherret/ts-morph/blob/b9769c2a61b74894de5aaf90fdba4042ddca0854/packages/common/package.json#L25

typescript is a dependency instead of a devDependency.

Steps to reproduce:

having a project depending on:

``` "@mikro-orm/reflection": "4.4.2", ```

```
yarn install --frozen-lockfile
yarn install --frozen-lockfile --production
```

actual behaviour:

- typescript ends in node_modules increasing the size of my Docker image.

expected behaviour:

- typescript should be removed after compilation

**Comment by dsherret** [comment]
Hey @mercuriete, since ts-morph is a wrapper around the compiler api, TypeScript needs to be a dependency of ts-morph and it uses it via ts-morph/common.

**Comment by mercuriete** [comment]
ok, if this is an intended issue...
Can you provide me documentation about how to avoid having typescript in a project in production mode?

I thought I don't need typescript after my project is compiled.

Thanks.

**Comment by dsherret** [comment]
@mercuriete the only thing would be to not depend on ts-morph.

**Comment by mercuriete** [comment]
I am not depending directly to ts-morph but indirectly.
Do you think is a problem of micro-orm?

Thanks for your support.

```
yarn why v1.22.5
[1/4] Why do we have the module "typescript"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "typescript@4.1.5"
info Has been hoisted to "typescript"
info Reasons this module exists
   - Specified in "devDependencies"
   - Hoisted from "@mikro-orm#reflection#ts-morph#@ts-morph#common#typescript"
info Disk size without dependencies: "56.1MB"
info Disk size with unique dependencies: "56.1MB"
info Disk size with transitive dependencies: "56.1MB"
info Number of shared dependencies: 0
=> Found "@nestjs/cli#typescript@4.0.5"
info This module exists because "@nestjs#cli" depends on it.
Done in 0.52s.
```

**Comment by dsherret** [comment]
Maybe. I’m not sure how it works, but looks like that would be the place to ask about this.

**Comment by mercuriete** [comment]
Thanks, you can close this issue :)

**Comment by dsherret** [comment]
No problem! 🙂 I hope you figure out this issue.
