### ISSUE TITLE
Bundle typescript.js with ts-morph and drop TypeScript dependency

### ISSUE THREAD

**Issue by dsherret** [dsherret/ts-morph#933]
See #932.

**Comment by rxliuli** [comment]
This will make ts-morph very, very big. Is it really necessary? If you need to specify the version, why not choose the exact version in the form of '4.5.0'?

**Comment by dsherret** [comment]
Yes, it’s much better and forces it to use the version of the compiler API it was written for (too many breaking changes in the compiler api). It’s actually less size than having a typescript dependency as well because it only includes typescript.js
