### ISSUE TITLE
Typescript lib files seem to be missing from the in-memory filesystem

### ISSUE THREAD

**Issue by velut** [dsherret/ts-morph#938]
(I'm not really sure if this is a bug or if I'm misunderstanding the new `libFolderPath` option)

**Describe the bug**

Typescript lib files seem to be missing from the **in-memory file system**, this causes the typechecker to infer as `any` some types that were instead correctly determined in version 9.1.0 of ts-morph.

I understand that there has been a change to how this files are handled
 
>The lib files/lib.d.ts files are now served from memory regardless of the file system host. If you want the old behaviour, specify a libFolderPath in the Project constructor's options.

but i cannot replicate the old behavior using `libFolderPath` for the in-memory filesystem.

Version: 10.0.1
Typescript version: 4.2.2

**To Reproduce**

```ts
import { Project, ts } from 'ts-morph';

// With v9.1.0: `4.1.5`
// With v10.0.1: `4.2.2`
console.log(ts.version);

// Use an in-memory filesystem
const project = new Project({ useInMemoryFileSystem: true });
const sourceFile = project.createSourceFile(
    "index.ts",
    `function foo() {
        return new Set<string>();
    }`
);

// Add all `.ts` files in the file system, on version 9.1.0
// this includes the the Typescript lib files in `node_modules`
// that enable better type checking.
project.addSourceFilesAtPaths("**/*.ts");

// With v9.1.0: `index.ts` and many other TS lib files are in the project
// With v10.0.1: `index.ts` is the only file in the project
const allFiles = project.getSourceFiles().map((f) => f.getFilePath());
console.log(allFiles);

// With v9.1.0 type is correctly inferred as `Set<string>`
// With v10.0.1 type is `any` because lib files seem to be missing
const foo = sourceFile.getFunctionOrThrow("foo");
console.log(foo.getReturnType().getText());
```

**Expected behavior**

I tried using the new `libFolderPath` option to get the old behavior back, that is loading Typescript lib files to get better type checking when using the in-memory filesystem, without success:

```ts
const project = new Project({
    useInMemoryFileSystem: true,

    // Some of the alternatives I tried without success
    // libFolderPath: '/node_modules',
    // libFolderPath: '/node_modules/typescript/lib',
    // libFolderPath: './node_modules/typescript/lib',
});
```

Am I overlooking something?

Thank you again for your help.

**Comment by dsherret** [comment]
Hey @velut, sorry about the confusion here and I will update the breaking change document to outline these details.

Previously ts-morph was including all the lib files in the root directory of an in memory file system. This meant if you added a file to the root directory, it would load in all the lib.d.ts files regardless of compiler options.

By default, the TS compiler targets ES5 and not at least ES2015, so `Set` will not be defined (same reason as if you open up a new typescript project and type `Set` you will see it doesn't exist). So now, ts-morph is acting more like the default behaviour of TypeScript.

You can now get this to work the same way you would with tsc, by including the lib files for ES2015:

```ts
const project = new Project({
    useInMemoryFileSystem: true,
    compilerOptions: {
        lib: ["lib.es2015.d.ts"],
    }
});
```

Or by targetting at least ES2015, which will cause the lib files for ES2015 to be included:

```ts
const project = new Project({
    useInMemoryFileSystem: true,
    compilerOptions: {
        target: ts.ScriptTarget.ES2015,
    }
});
```

The lib files themselves are no longer included in an in memory file system host or any file system host. They're stored in memory within ts-morph. If you'd want them in the in memory file system host, they have to be loaded in by doing `fileSystemHost.writeFileSync("/node_modules/typescript/lib/<file-name-goes-here>.d.ts", "<file-text-goes-here");`, then the `libFolderPath` could be pointed at `/node_modules/typescript/lib`. For getting the lib file text, there's an internal function in ts-morph that I could expose... would that function be useful for you?

**Comment by velut** [comment]
Thank you for pointing me in the right direction @dsherret!

[Based on the available lib files](https://github.com/Microsoft/TypeScript/tree/master/lib), the following project setup seems equivalent to the old behavior of having all lib files included in the project and solves my issue:

```ts
const project = new Project({
    useInMemoryFileSystem: true,
    compilerOptions: {
        lib: ['lib.esnext.full.d.ts'],
    },
});
```

> For getting the lib file text, there's an internal function in ts-morph that I could expose... would that function be useful for you?

For my current use case, the lib files being available to the compiler for type checking is sufficient, their actual content (for example, the definition of `Set`) is not important.

**Comment by dsherret** [comment]
@velut no problem and thanks for that additional information! I just updated the docs with it.

**Comment by yfwz100** [comment]
Is It better to describe the changes in the document (README) ?
