### ISSUE TITLE
getTypeParameters not working?

### ISSUE THREAD

**Issue by jasonkuhrt** [dsherret/ts-morph#939]
We noticed on our doc tool work that generics extraction are broken in TS 4.2. I know TS 4.2 changes how aliases are handled a bit, so not surprised. But I'm not sure how to get type parameters now...

Maybe I'm missing something, probably, or maybe there is a bug in ts-morph? The main thing is that `getTypeParameters` doesn't seem to work like it used to.

**Describe the bug**

Version: 4.2.2 TS + 10.0.2 ts-morph

**To Reproduce**

```ts
import * as tsm from 'ts-morph'
import { Project, ts } from 'ts-morph'

console.log(ts.version) // x.x.x <-- provide this

const project = new Project()
const sourceFile = project.createSourceFile(
  'foobar.ts',
  `
    export type A = Record<string,string>

  `,
)

const all = [...sourceFile.getExportedDeclarations()]

all.forEach(([name, decs]) => {
  console.log(name)

  const dec = decs[0]!
  console.log(dec.getText())

  const t = dec.getType()

  console.log('type alias dec -> type -> text', t.getText())
  console.log('type alias dec -> type -> sym -> dec -> text', t.getSymbol()?.getDeclarations()[0]?.getText())

  if (tsm.Node.isTypeAliasDeclaration(dec)) {
    const tp = dec.getTypeParameters()
    console.log(`type alias dec type parameters: ${tp.length}`)
  }

  const tr = dec.getChildrenOfKind(tsm.ts.SyntaxKind.TypeReference)[0]!

  console.log('type reference -> text', tr.getText())

  console.log('type reference -> type -> text', tr.getType().getText())

  console.log(
    'type reference -> type arguments -> text',
    tr.getTypeArguments().map((ta) => ta.getText()),
  )

  console.log('type reference -> type name -> text', tr.getTypeName().getText())

  console.log('type referene -> type -> sym -> dec -> text', tr.getType().getSymbol()?.getDeclarations()[0]?.getText())

  console.log(
    'type referene -> type -> sym -> dec -> kindName',
    tr.getType().getSymbol()?.getDeclarations()[0]?.getKindName(),
  )
})
```

Output:

```
4.2.2
A
export type A = Record<string,string>
type alias dec -> type -> text import("/Users/jasonkuhrt/projects/pakadev/paka/foobar").A
type alias dec -> type -> sym -> dec -> text {[P in K]:T;}
type alias dec type parameters: 0
type reference -> text Record<string,string>
type reference -> type -> text import("/Users/jasonkuhrt/projects/pakadev/paka/foobar").A
type reference -> type arguments -> text [ 'string', 'string' ]
type reference -> type name -> text Record
type referene -> type -> sym -> dec -> text {[P in K]:T;}
type referene -> type -> sym -> dec -> kindName MappedType
```

**Expected behavior**

Should be able to get type parameters of record via `getTypeParameters`.

**Comment by jasonkuhrt** [comment]
Hm, I realize that the get parameters on `A` being 0 makes sense...

**Comment by dsherret** [comment]
What's the expected behaviour here? `getTypeParameters()` will return the Type Alias node's type parameter declarations (so it works exclusively in the AST)

**Comment by jasonkuhrt** [comment]
@dsherret How would one go about getting the `Record` type alias and its type parameters?

**Comment by jasonkuhrt** [comment]
Not sure there is actually an issue here! Will report back if changes.

**Comment by jasonkuhrt** [comment]
Related https://stackoverflow.com/questions/66389805/how-to-extract-type-arguments-and-type-parameters-from-a-type-aliases-references

**Comment by dsherret** [comment]
I looked at this a bit and I'm not sure. I see the change between TS 4.1 and 4.2 on ts-ast-viewer.com https://ts-ast-viewer.com/#code/KYDwDg9gTgLgBDAnmYcCCcC8cBKwDG0AJgDwDOMUAlgHYDmANBdfQHxA

You may want to play around in the browser console with the `checker` object and `node` object to see if you're about to figure it out.
