### ISSUE TITLE
[Question] What's the best way to get the constructors of all the parameters of a method? 

### ISSUE THREAD

**Issue by mikealche** [dsherret/ts-morph#942]
Hey there! 

First of all, congratulations on this AMAZING AMAZING AMAZING project! 
I'm astonished by the flexibility it provides and how much easier it is than using the typescript compiler API. 

I'm a beginner to the typescript compiler API, so I still have some questions:

Say I have this example code
```
type Person = {
  firstname: string;
  age: 34;
};

class Place {
  private lat;
  private lng;
  constructor(lat: 123, lng: 543) {
    this.lat = lat;
    this.lng = lng;
  }
}

export class Animal {
  bark(toWhom: Person, howManyTimes: 4) {
    return "bark!";
  }
}
```

I want to create a program that given a class name (say `Animal`), will pick a random method of it (say `bark`) and call it with parameters that make sense. 

For that, I need to be able to 
1) Given a class name, get the class
2) Given a class, get all the methods
3) Given a specific method get all the parameters
4) Given a list of parameters, get their respective types
5) Given a list of types, get how to construct an instance of each type. 

I've managed to solve 1-4. However 5) is eluding me. 

Here's what I have so far
```
import { Project } from "ts-morph";

const project = new Project({
  tsConfigFilePath: "./tsconfig.json",
});

const sourceFiles = project.getSourceFile((f) => f.getClasses().length === 2);
const aClass = sourceFiles?.getClasses()[1]; // Animal
const methods = aClass?.getMethods();
const aMethod = methods![0]; // Animal.bark
const theParams = aMethod.getParameters();
const aParam = theParams[0]; // toWhom

const paramType = aParam.getTypeNode();
console.log(paramType?.getKindName()); // TypeReference
console.log(paramType?.getText()); // Person
```

Now I need to get "ahold" of the Person class in order to be able to read its constructor and the types of the constructor params to know how to create an instance of it. 

But how would I go about doing that?

**Comment by dsherret** [comment]
Hey @mikealche, thanks! I'm glad you like it.

In this case, use `getType()` as it will use the type checker. `getTypeNode()` will look for the AST node.

```ts
const animalClass = sourceFile.getClassOrThrow("Animal");
const barkMethod = animalClass.getMethodOrThrow("bark");
const toWhomParam = barkMethod.getParameterOrThrow("toWhom");

const paramType = toWhomParam.getType();

// won't have any though, since `Person` doesn't have a constructor (this would output something for `Place`)
for (const constructSignatures of paramType.getConstructSignatures()) {
  console.log(constructSignatures.getParameters().map(p => p.getName()));
  console.log(constructSignatures.getReturnType().getText());
}

// check the properties (outputs "firstname", then "age")
for (const prop of paramType.getProperties()) {
  console.log(prop.getName());
}
```

**Comment by mikealche** [comment]
Hi @dsherret thanks again for your answer! 

I've changed the sample code to be 
```
class Person {
  private firstname: string;
  private age: number;
  constructor(firstname: string, age: number) {
    this.firstname = firstname;
    this.age = age;
  }
}

class Place {
  private lat;
  private lng;
  constructor(lat: 123, lng: 543) {
    this.lat = lat;
    this.lng = lng;
  }
}

export class Animal {
  bark(toWhom: Person, where: Place) {
    return "bark!";
  }
}
```

So now Person is a class with a constructor. However I don't see anything logged for the first loop in the code that you wrote. Is there something that I'm missing?

**Comment by dsherret** [comment]
@mikealche oh, my bad! I mixed this up in my head and was acting like this was `typeof Person`.

In this case, you can get the parameter's type, then from the type go to the symbol and then the class declaration:

```ts
const classDecl = toWhomParam.getType().getSymbol()?.getDeclarations()[0];
if (Node.isClassDeclaration(classDecl)) {
  for (const ctor of classDecl.getConstructors()) {
    console.log(ctor.getText());
  }
}
```

**Comment by mikealche** [comment]
@dsherret you are AMAZING! thanks!!! 🚀 🚀 🚀 

I will keep hacking on my side-project and .... may come back with more questions in the future 😅

**Comment by dsherret** [comment]
@mikealche no problem! 🙂 Feel free to open another issue if you have more questions.
