### ISSUE TITLE
Can't resolve 'inspector' in '@ts-morph/common/dist'

### ISSUE THREAD

**Issue by mecirmartin** [dsherret/ts-morph#945]
Hey, i'm getting this error when on latest version of ts-morph. Reverting to @9.1.0 fixes the problem. Any ideas?

<img width="1127" alt="Screenshot 2021-03-05 at 14 28 33" src="https://user-images.githubusercontent.com/55835379/110121744-11746b80-7dbf-11eb-922a-aee89617bdc0.png">

Version: 10.0.1

**Comment by dsherret** [comment]
@mecirmartin are you compiling for the web? I forgot to add these node modules to the list of "browser" modules to turn off in ts-morph/common:

https://github.com/microsoft/TypeScript/blob/408c804103d5b4f3ce97722190eab9d428740d80/package.json#L120

Will fix it soon.

**Comment by mecirmartin** [comment]
Yeah, i'm compiling for the web, thank you very much for your hard work

**Comment by dsherret** [comment]
@mecirmartin thanks for reporting! This should be resolved now if you ensure your package manager is pulling in 0.8.1 of ts-morph/common, which it should be.
