### ISSUE TITLE
[Question] How to get name, properties and type of the properties of a type literal? 

### ISSUE THREAD

**Issue by mikealche** [dsherret/ts-morph#951]
Hi!! 

I already said it in the other question I posted, but this project is AMAZING AMAZING and AMAZING. ❤️

I'm continuing to hack on my [side project to automatically generate test suites. ](https://github.com/mikealche/morphic). Right now I'm in the part of parsing the code and building a JSON with all the info that I need (Given a class I have to get its constructors and methods and their parameters. Then for each parameter whose type is not a base type I need to do that recursively).

## Back to the question: 

Say I have this example piece of code 
```
type BarkType = {
  toWhom: string;
  age: number;
};

export class Animal {
  bark(options: BarkType): string {
    return "bark!";
  }
}
```
My code starts by parsing the `Animal` class. I have parsed the bark method and now I'm parsing its parameters. The `bark` method has a single parameter of type `BarkType`

How would I get the name, properties and type of `BarkType`? 
So far I have something that goes like this:

```
const method: MethodDeclaration; // Assume this is a handle for the declaration of the bark method.
const parameterDeclaration = method.getParameters()[0]
const parameterType = parameterDeclaration.getType();

/**
* First question:
* Here I need to fill in some logic to check that the parameterType is actually a type like the BarkType defined above.
* For example if it were an interface i'd be using parameterType.isInterface(). 
* If it were a class, i'd be using parameterType.isClass()
*
* What method should I use? is parameterType.isObject() the correct one for this case? or do I need a method like
* parameterType.isTypeLiteral() which doesn't exist yet ? 
* 
* Example code:
*/

if (parameterType.isString()) return doThingsForStrings(parameterType);
if (parameterType.isInterface()) return doThingsForInterfaces(parameterType);

// Should I be using a condition like this? 
if (parameterType.isObject()) return getNamePropertiesAndTypesOfTheProperties(parameterType);

// Or something like this:
if (parameterType.isTypeLiteral()) return getNamePropertiesAndTypesOfTheProperties(parameterType); 


/**
* Second question: 
* now that we have checked that the parameterType is of the kind that we need. 
* How do we get its name, its properties and the type of its properties
* I've been trying:
*/

const nameAttempt1 = parameterType.getSymbol()?.getDeclarations()[0].getName(); // Error getName is not a function
const nameAttempt2 = parameterType.getText(); // This works, but is it robust?

parameterType.getProperties().forEach((prop) => {
      console.log(prop.getName()); // Logs correctly "toWhom" and "age"
      // How to get the type of the properties, i.e: string and number?
    });

```

Again, sorry for my complete ignorance of this ecosystem. I'm still learning how everything works and your project is the only thing that allows me to hack on my side project.... but! I'm learning and I'll get better at it

**Comment by dsherret** [comment]
Hey @mikealche, sorry I never got around to your last question, but looks like you figured it out.

I'm not sure about your first question. It's probably best to just play around with it a bit and see what works, but what you're doing seems reasonable.

**Getting Name**

For `BarkType`, I believe you can check if the AST node type is a type reference for whether you can get its name.

```ts
const parameterTypeNode = parameterDeclaration.getTypeNode();

if (Node.isTypeReference(parameterTypeNode)) {
   // Note that this will only return the local name. If you want the declaration's
   // name then I believe you can check `parameterTypeNode.getTypeName().getDefinitionNodes()`.
   // Side note to myself: I kind of wonder if I should add a method that only uses the program
   // to do that and doesn't bother about the language service, but then that would require some
   // custom code that could get out of sync with the compiler api, I think.
   console.log(parameterTypeNode.getTypeName().getText())
}
```

**Getting Properties**

I think you just need to do what you are doing and check `parameterType.getProperties()`. This will return symbols though, so to get the type, you will need to call `prop.getTypeAtLocation(parameterDeclaration)`.

I think this will work, but I didn't test it:

```ts
const parameterType = parameterDeclaration.getType();

for (const prop of parameterType.getProperties()) {
    console.log(prop.getName()); // name
    console.log(prop.getTypeAtLocation(parameterDeclaration).getText()); // hopefully, the type
}
```

Let me know if that works or if I missed another question you had.

**Comment by mikealche** [comment]
it works!! you're a genius!! Thanks so so much again!!
