### ISSUE TITLE
insertStatements in a an ObjectLiteralExpression

### ISSUE THREAD

**Issue by slaith** [dsherret/ts-morph#958]
I want to add a comment in a variable declaration:

```typescript

const car = {
wheels: 4, //Add a comment after this line
brakes:1
}
```

I am able to get the variable declaration but can't use `insertStatements` on it. Nor am I able to use `insertStatements` to add a statement at a particular line number which i can extract from the declaration

**Comment by dsherret** [comment]
@slaith there aren't any statements here. I believe once you have the object literal expression of the variable declaration's initializer you should be able to use the `insertProperty` method to do this:

```ts
const initializer = variableDeclaration.getInitializerIfKindOrThrow(SyntaxKind.ObjectLiteralExpression);

initializer.insertProperty(1, "// comment");
```

**Comment by slaith** [comment]
Thank you for that. 
I am getting another error here retrieving the index for the property

```typescript
["wheels", "brakes", ....].map((propName)=>{
    const property = this.objExpression.getProperty(propName)
    if(property){
        const index = property.getChildIndex()-1
        this.objExpression.insertProperty(index, "//Comment");
    }
    else
    {
        this.objExpression.insertPropertyAssignment({name: propName, initializer: "{}" }
    }
}
```
My actual code is different, but there are around 7 properties currently. Properties are added at run time, so the index can change. I am reloading the expression each just to be sure. 
I get 
```

InvalidOperationError: Invalid index: The max index is 23, but 25 was specified.
    at verifyAndGetIndex (/somewhere/node_modules/ts-morph/dist/ts-morph.js:947:15)



```


Am I getting the index correctly? Interestingly, it doesn't have a problem with zero index. If I don't subtract 1, i get 
```
The max index is 23, but 24 was specified
```

It throws this error for the last one that I add.

**Comment by slaith** [comment]
Also, it seems that addProperty as a comment also adds an extra comma

**Comment by dsherret** [comment]
@slaith opened #961 and #962.

**Comment by slaith** [comment]
Thank you. Will dig into it myself if I can understand what's going on
