### ISSUE TITLE
GitHub Discussions?

### ISSUE THREAD

**Issue by Heniker** [dsherret/ts-morph#959]
Just a suggestion to consider adding GitHub discussions.
It seems like a lot of issues here are not actually issues or bug reports, but general questions about API usage.
Those questions really help in understanding of how to use this library, and I think it would be great to have a dedicated discussion panel, where questions can be categorized and easily searched.

**Comment by dsherret** [comment]
Done. Thanks!

**Comment by dsherret** [comment]
I unfortunately do not like it as much. People can filter based on the tag. I'm going to revert back to issues.

**Comment by Heniker** [comment]
Well, that's understandable. Actually, neither TypeScript or VSCode have discussions enabled. Issues it is then!

**Comment by dsherret** [comment]
@Heniker yeah, it was a good suggestion, but once I got all the issues in there I started dreading having to maintain more than one area in the repo 😅 (needing to remember to check both, having more activity due to other discussion features).

Sorry to everyone for the issue noise I created today. For future reference, I unlocked all issues that were locked in the transfer via:

```ts
const Octokit = require("@octokit/core").Octokit;

const octokit = new Octokit({
    auth: "personal-access-token-goes-here"
});

// manually bump page number and re-run
octokit.request("GET /repos/dsherret/ts-morph/issues?labels=question&state=all&per_page=100&page=1").then(issues => {
    handleIssue(0);

    function handleIssue(index) {
        const item = issues.data[index];
        if (item == null) {
            return;
        }

        console.log("Handling index " + index);
        octokit.request("DELETE /repos/dsherret/ts-morph/issues/" + item.number + "/lock").then(() => {
            setTimeout(() => {
                handleIssue(index + 1);
            }, 500);
        })
    }
});
```

**Comment by Gerrit0** [comment]
Yikes, good to know... I've been considering turning it on for TypeDoc. I think the 180 notifications just convinced me this is a terrible idea if it turns out to not be a good thing.

**Comment by dsherret** [comment]
@Gerrit0 sorry... I wasn't thinking and should have done a test with a few issues to try it out before hitting the button to convert all the issues in the questions tag. You might want to do that yourself and evaluate it. For me, I found out I just don't want another area to maintain.
