### ISSUE TITLE
How to compare 2 nodes?

### ISSUE THREAD

**Issue by Roaders** [dsherret/ts-morph#960]
Hi

I am writing a utility to dedupe interfaces from a collection of files and moving common interfaces to a new file. To do this ideally I want to compare the interfaces to see if they are the same. I can do this with `node.getText()` but differences in whitespace or comments will stop this comparison from working.

Is there a way to compare 2 nodes that removes differences in whitespace or comments?

**Comment by dsherret** [comment]
@Roaders see the discussion here: https://github.com/dsherret/ts-morph/issues/499 -- I think the code in there could be adapted to your needs.

**Comment by Roaders** [comment]
Thanks. That looks perfect. I'm familiar with the syntax of the generators used so an opportunity to learn something new!

I travelled from London to Seattle for the firs TSConf and ts-morph is by far the most useful thing I learnt about there. Thanks very much for all the hard work.

**Comment by dsherret** [comment]
@Roaders cool! I'm glad that other issue should help you out.

That's awesome and thanks for the compliment. I was lucky to be able to present it there. tsconf each year has been a lot of fun... can't wait for them to be in person again though.
